### ISSUE TITLE
Control tracks by URL parameters 

### ISSUE THREAD

**Issue by songtaogui** [lidaof/eg-react#102]
Hi, @lidaof 

I would like to link the WashU browser with different data table. For example, when jumped from a MethylC table, I would like to display only the gene annotation and the MethlC tracks, and when jumped from a Interaction table , I would like to display the HiC tracks.

Is it possible to control the show and hide of different tracks by URL parameters?  

Thank you.

Best wishes,
Songtao Gui

**Comment by lidaof** [comment]
Hi @songtaogui you can do this by using the `hub` parameter, so you can create 2 hub files, for the tracks you want to show, specify a "showOnHubLoad": true in track property.

**Comment by songtaogui** [comment]
Hi @lidaof 
I have tried the example hub parameters in the [doc](https://epigenomegateway.readthedocs.io/en/latest/url.html#hub):

http://epigenomegateway.wustl.edu/browser/?genome=hg19&hub=https://vizhub.wustl.edu/public/tmp/a.json

but non of the tracks in the json file were displayed, did I miss something?

**Comment by songtaogui** [comment]
Yes it works. Thanks! @lidaof  
👍

**Comment by songtaogui** [comment]
@lidaof  
Is `matplot` function available in version 48.2.0 ?  I have tried it in the offical site (V48.4.4), but failed to find it in my local browser (v48.2.0). Or how can I update my browser to v48.4.4?

**Comment by lidaof** [comment]
sorry for that, you need switch to `matplot` branch, when you `git clone`, `git pull`, then do `git branch matplot`, then your code should have this function.

**Comment by songtaogui** [comment]
@lidaof  I have successfully updated to v48.4.4. Thank you!

However, I have encountered a problem with using my own backend API:

I have set the backend API following the [Doc](https://epigenomegateway.readthedocs.io/en/latest/installation.html?highlight=API#setup-your-own-backend-api-optional) using refbed fromat gene annotation files (all of which can correctly displayed on the WashU Browser through URL). And it seems successfully finished:

```
This will modify the following databases in MongoDB:
    B73
    Mex
    Mo17
    SK
    mm9
Continue (y/n)? y
Loading genome B73
2019-04-17T02:19:14.861+0000    connected to: localhost
2019-04-17T02:19:14.861+0000    dropping: B73.refGene
2019-04-17T02:19:15.312+0000    imported 46430 documents
B73: done

Loading genome Mex
2019-04-17T02:19:15.620+0000    connected to: localhost
2019-04-17T02:19:15.620+0000    dropping: Mex.refGene
2019-04-17T02:19:15.947+0000    imported 31387 documents
Mex: done

Loading genome Mo17
2019-04-17T02:19:16.154+0000    connected to: localhost
2019-04-17T02:19:16.154+0000    dropping: Mo17.refGene
2019-04-17T02:19:16.545+0000    imported 38620 documents
Mo17: done

Loading genome SK
2019-04-17T02:19:16.809+0000    connected to: localhost
2019-04-17T02:19:16.809+0000    dropping: SK.refGene
2019-04-17T02:19:17.248+0000    imported 43271 documents
SK: done

Loading genome mm9
2019-04-17T02:19:17.543+0000    connected to: localhost
2019-04-17T02:19:17.544+0000    dropping: mm9.refGene
2019-04-17T02:19:18.083+0000    imported 43124 documents
mm9: done

All done
```
The gene annotation of "Mo17","SK","mm9" can be normally displayed:
![image](https://user-images.githubusercontent.com/14274330/56256658-39d81b80-60fc-11e9-83d9-748eb3a65ae1.png)


but there are no data for "B73" and "Mex":
![image](https://user-images.githubusercontent.com/14274330/56256731-7ad03000-60fc-11e9-91f0-890d0c6558d1.png)
![image](https://user-images.githubusercontent.com/14274330/56256779-aa7f3800-60fc-11e9-915c-0ae2750311d0.png)

I have checked the region in MongoDB, and it seems that these data were correctly stored:
```bash
# in mongoDB
> use B73
switched to db B73
> db.refGene.find({ "chrom": 1, "txStart": {"$gt": 46666652}, "txEnd": {"$lt": 47036087} })
{ "_id" : ObjectId("5cb6925f6a5e87c9f68d9dc4"), "chrom" : 1, "txStart" : 46667081, "txEnd" : 46670026, "cdsStart" : 46667081, "cdsEnd" : 46670026, "strand" : "+", "name" : "Zm00001d028796", "id" : "Zm00001d028796", "transcriptionClass" : "", "exonStarts" : "46667081,46669102", "exonEnds" : "46669008,46670026" }
{ "_id" : ObjectId("5cb6925f6a5e87c9f68d9d5c"), "chrom" : 1, "txStart" : 46672702, "txEnd" : 46675540, "cdsStart" : 46672702, "cdsEnd" : 46675540, "strand" : "+", "name" : "Zm00001d028797", "id" : "Zm00001d028797", "transcriptionClass" : "", "exonStarts" : "46672702,46672968,46673435,46674153", "exonEnds" : "46672879,46673364,46673563,46675540" }
{ "_id" : ObjectId("5cb6925f6a5e87c9f68d9d05"), "chrom" : 1, "txStart" : 46679328, "txEnd" : 46679813, "cdsStart" : 46679328, "cdsEnd" : 46679813, "strand" : "+", "name" : "Zm00001d028798", "id" : "Zm00001d028798", "transcriptionClass" : "", "exonStarts" : 46679328, "exonEnds" : 46679813 }
{ "_id" : ObjectId("5cb6925f6a5e87c9f68d9d64"), "chrom" : 1, "txStart" : 46732004, "txEnd" : 46733203, "cdsStart" : 46732004, "cdsEnd" : 46733203, "strand" : "+", "name" : "Zm00001d028799", "id" : "Zm00001d028799", "transcriptionClass" : "", "exonStarts" : "46732004,46733017", "exonEnds" : "46732185,46733203" }
{ "_id" : ObjectId("5cb6925f6a5e87c9f68d9d67"), "chrom" : 1, "txStart" : 46819355, "txEnd" : 46823093, "cdsStart" : 46819355, "cdsEnd" : 46823093, "strand" : "+", "name" : "Zm00001d028801", "id" : "Zm00001d028801", "transcriptionClass" : "", "exonStarts" : "46819355,46820978,46821433,46822728", "exonEnds" : "46820132,46821245,46822513,46823093" }
{ "_id" : ObjectId("5cb6925f6a5e87c9f68d9d58"), "chrom" : 1, "txStart" : 46826505, "txEnd" : 46831989, "cdsStart" : 46826505, "cdsEnd" : 46831989, "strand" : "-", "name" : "Zm00001d028802", "id" : "Zm00001d028802", "transcriptionClass" : "", "exonStarts" : "46826505,46827450,46827658,46831534", "exonEnds" : "46826946,46827539,46827727,46831989" }
{ "_id" : ObjectId("5cb6925f6a5e87c9f68d9d52"), "chrom" : 1, "txStart" : 46852702, "txEnd" : 46858687, "cdsStart" : 46852702, "cdsEnd" : 46858687, "strand" : "-", "name" : "Zm00001d028803", "id" : "Zm00001d028803", "transcriptionClass" : "", "exonStarts" : "46852702,46853234,46853870,46854031,46856832,46856994,46857217,46858202", "exonEnds" : "46853140,46853341,46853953,46856734,46856899,46857126,46857504,46858687" }
{ "_id" : ObjectId("5cb6925f6a5e87c9f68d9dbc"), "chrom" : 1, "txStart" : 46898667, "txEnd" : 46903474, "cdsStart" : 46898667, "cdsEnd" : 46903474, "strand" : "-", "name" : "Zm00001d028804", "id" : "Zm00001d028804", "transcriptionClass" : "", "exonStarts" : "46898667,46901507,46901718,46902459,46903250", "exonEnds" : "46899313,46901583,46901811,46902631,46903474" }
{ "_id" : ObjectId("5cb6925f6a5e87c9f68d9d55"), "chrom" : 1, "txStart" : 46955327, "txEnd" : 46956671, "cdsStart" : 46955327, "cdsEnd" : 46956671, "strand" : "+", "name" : "tassel_seed2", "id" : "Zm00001d028806", "transcriptionClass" : "", "exonStarts" : "46955327,46955679", "exonEnds" : "46955586,46956671" }
{ "_id" : ObjectId("5cb6925f6a5e87c9f68d9dbd"), "chrom" : 1, "txStart" : 46964052, "txEnd" : 46965897, "cdsStart" : 46964052, "cdsEnd" : 46965897, "strand" : "-", "name" : "Zm00001d028807", "id" : "Zm00001d028807", "transcriptionClass" : "", "exonStarts" : "46964052,46965712", "exonEnds" : "46964458,46965897" }
{ "_id" : ObjectId("5cb6925f6a5e87c9f68d9dbf"), "chrom" : 1, "txStart" : 47025643, "txEnd" : 47026431, "cdsStart" : 47025643, "cdsEnd" : 47026431, "strand" : "-", "name" : "Zm00001d028808", "id" : "Zm00001d028808", "transcriptionClass" : "", "exonStarts" : 47025643, "exonEnds" : 47026431 }
```
 
Now I have no idea how did these data not pass to the browser. 

Do you have any suggestions?

Thank you !

**Comment by lidaof** [comment]
I see the only difference is chromosome name `1` versus `chr1`,  can you please do a quick test that replace all chromosome name with chr prefix, includes B73.js and the mongo db file, i suspect mongodb convert chrom to integer and caused browser fetched nothing...

**Comment by songtaogui** [comment]
@lidaof  
Yes. It is the matter of numerical chr values in mongo db. 
this problem was solved after changing the chrom value to string:
```
refGene.find({}).forEach(function(x) { x.chrom = x.chrom + ""; db.refGene.save(x); } )
```

Thank you !

**Comment by lidaof** [comment]
oh, yeah, you can operate in mongodb too as you did. smart!

**Comment by umasstr** [comment]
Is it possible to hide refseq, repeatmasker, ruler etc. On a data hub (as opposed to an annotation hub)?

**Comment by lidaof** [comment]
Hi @umasstr you can use the `noDefaultTracks=1` in url, like [this link](https://epigenomegateway.wustl.edu/browser/?genome=hg19&hub=https://wangftp.wustl.edu/~dli/test/a.json&noDefaultTracks=1). let me know if it helps or not. Thanks.

**Comment by umasstr** [comment]
Works well, thanks!
