### ISSUE TITLE
Genome Comparison Highlighting  

### ISSUE THREAD

**Issue by EvoAlias** [lidaof/eg-react#104]
Highlighting is shifted to the left when you add a genome comparison, leaving a gap on the right. I think what is happening is: for instance we highlight chr1 250-750 so 500 bp from left to right. We add another genome which creates gaps, but we still highlight the first 500 bp (pixels?) so that cause a shift.

<img width="1783" alt="Screen Shot 2019-05-02 at 6 10 19 PM" src="https://user-images.githubusercontent.com/8665173/57151641-0ac9d700-6d97-11e9-9160-366dcb6c5cec.png">
<img width="1723" alt="Screen Shot 2019-05-02 at 6 10 14 PM" src="https://user-images.githubusercontent.com/8665173/57151649-10bfb800-6d97-11e9-93b4-44200ca883aa.png">

**Comment by lidaof** [comment]
fixed by 5a050a8
