### ISSUE TITLE
Gencode genes aren't visible

### ISSUE THREAD

**Issue by gracilis** [lidaof/eg-react#106]
Hi,

  The browser isn't showing the gencode v29 genes track, which is displayed by default. Without it, gene names and lengths aren't visible on the browser. CORS is enabled on the browser (Google Chrome v74.0.3729.108), so that isn't the issue. Screenshot:

![image](https://user-images.githubusercontent.com/42852986/57803994-46fa2180-771f-11e9-9147-b2f33cf40450.png)

**Comment by lidaof** [comment]
Hi @gracilis apology for this trouble. Something error happened on our API server. It should be fixed now.
Thanks for reporting.

**Comment by gracilis** [comment]
Thanks, @lidaof, it looks good!

**Comment by lidaof** [comment]
You are very welcome @gracilis !
