### ISSUE TITLE
Unable to view files -- data fetch failed 

### ISSUE THREAD

**Issue by kmualim** [lidaof/eg-react#107]
The files are located in http://mitra.stanford.edu/kundaje/projects/ABC_links/
and follow the longrange format provided in documentation. 

- Most common cause (as stated in the uWash website) is usually the webserver not enabling CORS but we've used the WashU browser + mitra webserver to view BigWig files etc before so this doesn't seem like it should be a problem with that. 

Thanks!

**Comment by lidaof** [comment]
Hi @kmualim , sorry for this trouble.
I am sure the file is formatted correctly as I put it [here](https://wangftp.wustl.edu/~dli/tmp/final_sorted_lr.txt.gz) I can visualize it in our browser.

The [test-cors.org site](https://www.test-cors.org/#?client_method=OPTIONS&client_credentials=false&server_url=http%3A%2F%2Fmitra.stanford.edu%2Fkundaje%2Fprojects%2FABC_links%2Ffinal_sorted_lr.txt.gz&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote) tells the cors might not setup correctly

if it's possible, can you try add this in the apache.conf file:

```
Header set Access-Control-Allow-Origin "*" 
Header set Access-Control-Allow-Headers: Range
Header set Access-Control-Max-Age: 86400
```

I am not 100% sure it will work or not...though....we can try some tests...

**Comment by kmualim** [comment]
We've tried those commands. I also tried submitting the file onto the old legacy browser and it doesn't seem to show -- the files have also been formatted to fit the old legacy browser format.

**Comment by lidaof** [comment]
closing for now, feel free to reopen it or open a new issue.
