### ISSUE TITLE
cannot save session in washu epigenome browser which is hosted locally

### ISSUE THREAD

**Issue by yingfeic** [lidaof/eg-react#108]
I'm working on maintaining a local version WashU genome browser here in UT Southwestern.
I've install the legacy version and the new version as well.

In the new version, I cannot save a session and retrieve it later. 
I gave it a name of the session, it showed this was saved. When I put the name again and click retrieve session, it will show "session retrieved", but nothing changed in the browser. I'm wondering if there's any setting I need to change in the server. Could you give me some suggestion?

Thanks,
Yingfei

**Comment by lidaof** [comment]
Hi Yingfei @yingfeic , for session functions you would need setup the firebase, please check the [doc](https://eg.readthedocs.io/en/latest/installation.html#firebase-setup) for more information. Feel free to let me know any issue for this. Thank you!

**Comment by lidaof** [comment]
closing for now, feel free to reopen it or open a new issue.
