### ISSUE TITLE
ChromHMM track

### ISSUE THREAD

**Issue by wzhy2000** [lidaof/eg-react#110]
I am failed to show ChromHMM tracks, can you help me find the reasons?
The URL is:
http://epigenomegateway.wustl.edu/browser/?genome=hg19&datahub=ftp://cbsuftp.tc.cornell.edu/danko/hub/histone/chrom.json

Thank you very much!

**Comment by lidaof** [comment]
Hi @wzhy2000 , sorry that our new browser is not supporting FTP protocol yet. you can use the [local track feature](https://eg.readthedocs.io/en/latest/local.html).

Also the link you sent will redirect to our old browser, which works for your file use this datahub syntax
```
# http://epigenomegateway.wustl.edu/browser/?genome=hg19&datahub=ftp://cbsuftp.tc.cornell.edu/danko/hub/histone/chrom.json
[ 
{
         "type":"categorical",
         "url":"ftp://cbsuftp.tc.cornell.edu/danko/hub/histone/k562_org_chromHMM.bed.gz",
         "name":"ChromHMM",
           "categories":{
           1:  ["TssA:Active TSS Red",              "#FF0000"],
           2:  ["TssFlnk:Flanking TSS",             "#FF4500"],
           3:  ["TssFlnkU:Flanking TSS Upstream",   "#FF4500"],
           4:  ["TssFlnkD:Flanking TSS Downstream", "#FF4500"],
           5:  ["Tx:Strong transcription",          "#007F00"],
           6:  ["TxWk:Weak transcription",          "#006400"],
           7:  ["EnhG1:Genic enhancer1",            "#C2E105"],
           8:  ["EnhG2:Genic enhancer2",            "#C2E105"],
           9:  ["EnhA1:Active Enhancer 1",          "#FFC34D"],
           10: ["EnhA2:Active Enhancer 2",          "#FFC34D"],
           11: ["EnhWk:Weak Enhancer",              "#FFFF00"],
           12: ["ZNF/Rpts:ZNF genes & repeats",     "#66CDAA"],
           13: ["Het:Heterochromatin",              "#8A91D0"],
           14: ["TssBiv:Bivalent/Poised TSS",       "#CD5C5C"],
           15: ["EnhBiv:Bivalent Enhancer",         "#BDB76B"],
           16: ["ReprPC:Repressed PolyComb",        "#808080"],
           17: ["ReprPCWk:Weak Repressed PolyComb", "#C0C0C0"],
           18: ["Quies:Quiescent/Low",              "#FFFFFF"]
         },
         "mode": "show"
         }
]

```
and this is what it looks like after loaded:
![image](https://user-images.githubusercontent.com/102806/58609060-e533ce80-826b-11e9-9d81-4a0436b5c266.png)


Hope this helps. let me know any question please. Thanks.

**Comment by wzhy2000** [comment]
Thanks a lot.

I copied and changed the example here:
https://eg.readthedocs.io/en/latest/datahub.html#example-categorical-track

Do you mean this example works on the new version? It would be helpful if the version information or old format are attached in this section.

**Comment by lidaof** [comment]
sorry for the confusion about old and new browser...
the link you sent if for new browser, the new browser doesn't support FTP protocol as specified in your datahub.
for old browser, the doc is at its wiki: http://wiki.wubrowse.org/

Hope this is clear? Thanks.

**Comment by lidaof** [comment]
feel to reopen is you need additional info. thanks
