### ISSUE TITLE
Display loops only within current window

### ISSUE THREAD

**Issue by souryacs** [lidaof/eg-react#111]
Hi @lidaof 
For the new WashU browser, it would be beneficial if I can visualize only those loops whose both start and end coordinates fall within the current window. That can be a option (checkbox). Right now interactions whose one end is within the current window are all displayed, which causes problems in manual inspection of loops. Absence of any tooltip text on the arcs makes it even harder. Please check and if possible, provide such an option to users.

**Comment by lidaof** [comment]
Hi @souryacs , it's certainly doable, I will think about this. Thanks for suggestion.

**Comment by vivekliai** [comment]
Hi @lidaof 

As asked by @souryacs, do you think you are going to add this feature soon? Old browser used to work like that so I think it should be easy to add the feature.

Best,
Vivek

**Comment by lidaof** [comment]
yes, we can add that, working on this and will update you.

**Comment by vivekliai** [comment]
Thanks Daofeng. Hopefully it will workout soon. I am in middle of my manuscript and greatly appreciate your help.

Best,
Vivek

**Comment by lidaof** [comment]
Implemented. Updated discussion on #176 . thank you!
