### ISSUE TITLE
refGene annotation track seems to display the wrong genes

### ISSUE THREAD

**Issue by ckntav** [lidaof/eg-react#113]
Hi,
Since a couple of days, I noticed that several annotation tracks display the wrong genes on WashU browser. These mistakes appear on "refGene" and "GENCODE V29 genes".
On the other side, "GENCODE V29 basic genes" and "Ensembl release 94 genes" display the expected genes.
Did I do something wrong? Is there a way to fix this by myself?

Thanks

**Comment by debugpoint136** [comment]
Hi @ckntav I suspect this is due to a recent update to the API service I performed earlier this week. Apologize for the trouble, I am going to revert back the changes, while I troubleshoot it further.

**Comment by ckntav** [comment]
It works again, thanks for your fast reply.
