### ISSUE TITLE
Question about the track upload security

### ISSUE THREAD

**Issue by kokonech** [lidaof/eg-react#114]
Hi! There is an option to upload the local tracks when setting data hub is not possible. But do I understand correctly that the local files themselves are not uploaded anywhere(e.g. huge HiC results), but the access to local data is organised? Does this operation take care about the data security? Simply, is the access available only to the current active user of the session?  I have this question since really would like to use WashU, but have no permissions to share the data that I am working on. If the data is still shared in such upload, what could be the alternative to use WashU with secure data access?

**Comment by lidaof** [comment]
Hi @kokonech, local tracks are only available for the current people with current computer. It works like first you grant the browser to access your local files, then the browser will start to read your files. The local files cannot be saved to a session or a **remote** data hub, but it can be organized to a **local** data hub with similar syntax. The **upload** in `upload local track` is a little bit confusing, we might try a different word.

So for your questions:
> But do I understand correctly that the local files themselves are not uploaded anywhere(e.g. huge HiC results), but the access to local data is organised?

Correct, local data are not uploaded anywhere.

> Does this operation take care about the data security?

There is no data transfer actually, so security should be not an issue.

> Simply, is the access available only to the current active user of the session? 

Yes, with only current computer as well.

Hope this is clear. Feel free to let me know anything.

**Comment by kokonech** [comment]
Thanks a lot for the detailed reply! This access control exactly confirms the possibility to use WashU Epi on protected data. Probably extending the documentation accordingly might be helpful for future users to be aware about this.

**Comment by lidaof** [comment]
make sense, I will update the doc! thank you! @kokonech
