### ISSUE TITLE
Problems with data hub on both legacy and new versions

### ISSUE THREAD

**Issue by albertoriva** [lidaof/eg-react#115]
I've been using the legacy browser for over a year, mainly to display my own data hubs, that are hosted on a web server I administer. The files are protected by basic authentication, so I was using putting credentials in the URL, using http://username:password@hostname/... This worked fine until a couple of weeks ago, when the browser started "dropping" tracks at random. Looking at the HTTP logs I noticed that it fails to send credentials in a random way when downloading the track files, so we basically had to keep reloading the hub until by pure chance all tracks show up (and this is feasible with a small number of tracks, but I have a hub that has 30 of them and there's no way to get them all to show up at the same time).

So I tried switching to the new browser, but I had even more trouble. First of all it seems that the new browser doesn't support credentials in URLs, so I removed authentication from my server. I also changed the syntax of the JSON file to the new format. But still, if I try to open the hub by putting its address in the URL (?genome=hg30&hub=...) nothing happens, I get the default view. If I open the "Add custom data hub" window and enter the URL there and I click the "Load from URL" button, I get the message "Error: HTTP 0". I can see that the browser sends the request for the JSON file, and my server sends it correctly, but nothing happens after that.

Finally, is the "group" option still supported in the new browser? That's very important for me, it's the main reason why I switched from the UCSC browswer to this one.

Thank you!

**Comment by albertoriva** [comment]
Update: after enabling CORS on my server, loading the track mostly works, but I only see four out of the seven tracks in my hub, the other three are ignored without any explanation.

Also my other question still stands: is there an equivalent of the "group" option? And of the "mode: thin" option?

**Comment by lidaof** [comment]
Hi @albertoriva , thanks for using the browser and sorry for the trouble.
For the legacy browser losing track issue, have you tried `Refresh cache` from validate data hub app?
![image](https://user-images.githubusercontent.com/102806/59948235-10f24080-9435-11e9-88c3-e178bb092560.png) 

For the new browser, yes, we are sorry we don't support http authentication, and the server need to enable CORS. When you load a hub, you can specify `"showOnHubLoad": true` for a certain track to be displayed by default.

Really sorry that the new browser we don't have the group attribute yet, but I will try to work on it and will update you once it's implemented.

**Comment by albertoriva** [comment]
So, I tried the Validate Datahub command and it says that everything is OK, but the Refresh cache command instead gives errors. And, although validation is successful, when I open the hub only 3 out of 7 tracks get loaded. I have screenshots and HTTP logs for all of this, but I'd rather send them to you privately since they contain authentication info; would that be possible? Thanks!

**Comment by lidaof** [comment]
Hi @albertoriva sure thing. Please send them to me at lidaof@gmail.com. Thank you!

**Comment by albertoriva** [comment]
Issue with legacy browser is fixed, thanks Daofeng!
