### ISSUE TITLE
Relative pathnames in custom data hubs?

### ISSUE THREAD

**Issue by albertoriva** [lidaof/eg-react#116]
It would be great if the "url" parameter in hub definition json file could be a relative pathname (interpreted relative to the location of the json file). That way the hub could be written in a generic way, independently of where it is ultimately hosted.

**Comment by lidaof** [comment]
Hi @albertoriva , this could be a very good feature, I will try to implement it. Thanks!

**Comment by lidaof** [comment]
Hi @albertoriva , I implemented this feature in 883f673, for the new browser. For the old browser, currently we are only maintaining it. Sorry for that.

**Comment by albertoriva** [comment]
Great, thanks! But unfortunately until you implement the "group" attribute I can't use the new browser... I guess I'll wait :)

**Comment by lidaof** [comment]
`group` attribute was also added before, forgot to update...close this one for now.
Feel free to open a new issue. thanks!
