### ISSUE TITLE
annotation track menu display issue

### ISSUE THREAD

**Issue by xzhuo** [lidaof/eg-react#117]
![image](https://user-images.githubusercontent.com/2028370/60469303-d1d8a200-9c21-11e9-973a-3d04585d555d.png)

The annotation tracks white-out after I click either "rheMac3 to hg38 blastz" or "rn5 to hg38 blastz". Is it because rheMac3 and rn5 are not built in as an optional primary genome?

**Comment by lidaof** [comment]
Thanks for reporting this bug. fixed in 74e1a1d
