### ISSUE TITLE
Can you provide the following dockerfile?

### ISSUE THREAD

**Issue by kerry1221** [lidaof/eg-react#127]
I want to create a docker image and deploy the project to the k8s environment. I want to refer to your docker file. OK?

**Comment by lidaof** [comment]
Hi @kerry1221 , sorry I actually didn't have a docker file. I basically launched a new EC2 instance with Ubuntu 16.04, clone the code, npm install and npm start following the documentation: https://eg.readthedocs.io/en/latest/installation.html

**Comment by kerry1221** [comment]
I see. Thank you for your answer. I'll try to see if I can pack a complete mirror. So you can run in any container environment

**Comment by lidaof** [comment]
Hi @kerry1221 , just wondering is K8 better than node.js?

**Comment by lidaof** [comment]
closing for now, feel free to reopen it or open a new issue.
