### ISSUE TITLE
Backend project issues，3001 monitor disappeared

### ISSUE THREAD

**Issue by kerry1221** [lidaof/eg-react#128]
I run the backend project, npm start. After a period of time, the service can not be accessed, and the port 3001 is not monitored.

**Comment by lidaof** [comment]
@kerry1221 I am guessing your mongodb process crashed? We had this situation as well, mongdb get crashed due to memory issue, then backend cannot not be connected.

**Comment by kerry1221** [comment]
Thank you for your reply. I moved mongodb to Aliyun. My reason was that I quit SSH session, and then I started node in PM2 mode. It became a daemon.

**Comment by lidaof** [comment]
That's good. I usually use screen to tmux and keep the process open.

**Comment by lidaof** [comment]
closed for now. Feel free to submit new issues.
