### ISSUE TITLE
Using long range interaction files -- no data in view range

### ISSUE THREAD

**Issue by kmualim** [lidaof/eg-react#129]
Hi, 

I'm trying to view this file located in : http://mitra.stanford.edu/kundaje/projects/GGR_skin/hic_links/sorted_indexed_d0_b1.txt.gz

I'm viewing a region chrX:155233302-155234033 that should register some links when you  `tail` command the sorted_indexed_d0_b1.txt.gz file, but no links are registered. 

I am sure to have both pairs as directed in http://wiki.wubrowse.org/Long-range

I'm just wondering if I'm doing something wrong? 

Thanks

**Comment by lidaof** [comment]
Hi @kmualim , i get CORS error and I suspect your there might be 2 `Access-Control-Allow-Origin` setup in your apache settings. if you setup in virtualhost, you don't need setup in apache.conf, vice versa..can you please double check? thanks.

Access to XMLHttpRequest at 'http://mitra.stanford.edu/kundaje/projects/GGR_skin/hic_links/sorted_indexed_d0_b1.txt.gz.tbi' from origin 'http://epigenomegateway.wustl.edu' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.

**Comment by lidaof** [comment]
Hi @kmualim again, I downloaded your files and view it locally, using the `view local tracks` function, i think i did see some interactions in the region you mentioned:
![image](https://user-images.githubusercontent.com/102806/62591245-98d0c480-b894-11e9-99eb-3f574c668b33.png)

**Comment by kmualim** [comment]
Hi @lidaof , 

Thank you so much for the quick response and the help! I managed to get it working on the old legacy genome browser! I was previously able to load longrange interact files in the legacy genome browser and upon retrieving my old session, I get this error : hg19 Missing track for reordering: 24048993070553237. Would you be able to advise? 

Thanks!

**Comment by lidaof** [comment]
Hi @kmualim sure. This error happens sometime duo to network problem. Would you share the URL for me to test as well?

**Comment by kmualim** [comment]
Hi @lidaof , 

Sure -- 
http://mitra.stanford.edu/kundaje/projects/sorted_jesse_abc.txt.gz
http://mitra.stanford.edu/kundaje/projects/k562_counts.txt.gz
http://mitra.stanford.edu/kundaje/projects/sorted_k562_1000bp_counts_links.txt.gz
http://mitra.stanford.edu/kundaje/projects/K562_CRISPRi_K.txt.gz
Any of these files

**Comment by lidaof** [comment]
Hi @kmualim seems all of your links gives 404 not found error:

```
$ curl -I http://mitra.stanford.edu/kundaje/projects/K562_CRISPRi_K.txt.gz
HTTP/1.1 404 Not Found
Date: Mon, 09 Sep 2019 18:32:02 GMT
Server: Apache/2.4.18 (Ubuntu)

```

**Comment by kmualim** [comment]
Oh yes, sorry I apologize. The cluster has been having some issues. 

Thanks for the help!
