### ISSUE TITLE
Browser not working with windows

### ISSUE THREAD

**Issue by harrica** [lidaof/eg-react#131]
I have the docker image running and it mostly works on macs but my windows users get the following error. any ideas.  Oh the browser is very nice btw.
![image](https://user-images.githubusercontent.com/45017603/65496672-d1624700-deb0-11e9-9108-81c3087168f1.png)

**Comment by lidaof** [comment]
Hi @harrica thanks for reporting. Are you using Google chrome or Edge?

**Comment by harrica** [comment]
Chrome

Richard Harvey

**Comment by lidaof** [comment]
Hi @harrica i have updated docker to our latest code on docker, https://cloud.docker.com/repository/docker/epgg/eg-react/, would you mind give it a try? thanks.

**Comment by harrica** [comment]
It would be my pleasure

might be an hour or so

Richard Harvey
rharvey@harvey-morrison.com

**Comment by harrica** [comment]
thank you so much, the update fixed it. I certainly appreciate it

**Comment by lidaof** [comment]
Thank you for your feedback! @harrica
