### ISSUE TITLE
Cannot manually specify Y-axis scale for bigWig tracks

### ISSUE THREAD

**Issue by AdrijaK** [lidaof/eg-react#134]
I can't modify bigWig track 'settings > y-axis score' which is set to 'automatic scale'.  
In contrast, it is possible to change colors, track height or smoothing window for the same track.
Has anyone seen similar issues and how can these be resolved? 

Thanks!

**Comment by lidaof** [comment]
Hi @AdrijaK , can you take a screenshot please? First you need change scale to FIXED, then you can adjust max and min values.

![image](https://user-images.githubusercontent.com/102806/67103428-b66eb400-f18a-11e9-877b-b9a2f89dac40.png)

**Comment by AdrijaK** [comment]
While making the screenshot I realized I am using the old genome browser version:
The bug is already noted in https://github.com/epgg/eg/issues/68
I am sorry for the mixup and thank you for the fast reply.

**Comment by lidaof** [comment]
Hi @AdrijaK you are very welcome and no worries.
