### ISSUE TITLE
Disable mouse cross-hairs

### ISSUE THREAD

**Issue by rakarnik** [lidaof/eg-react#135]
Is it possible to disable the cross-hairs (vertical and horizontal dotted lines following the mouse)? It is quite distracting. If there is a place in the code that I need to change, please let me know, and I am happy to do that. Thank you for the help!

**Comment by lidaof** [comment]
Hi @rakarnik, the quickest way is to disable the CSS in the file `frontend/src/components/DivWithBullseye.css` like:

![image](https://user-images.githubusercontent.com/102806/67222777-9f7eca80-f3f3-11e9-9824-6f75676c2f59.png)

**Comment by rakarnik** [comment]
Perfect, thanks @lidaof!
