### ISSUE TITLE
Disabling default tracks for genome

### ISSUE THREAD

**Issue by rakarnik** [lidaof/eg-react#136]
I am trying to use a datahub to load a default set of tracks (say for a cell type) and not load some of the default tracks (e.g. RepeatMasker). How do I go about doing that?

Thanks for the help!

**Comment by lidaof** [comment]
Hi @rakarnik, you are welcome. That's also an option on my todo list.
Are you loading the hub using URL parameter or from the UI button?

if from the UI button I think you can modify `App.js`: (remove the concat step, just overwrite the tracks), i think this will work, not tested yet

```js
addTracks(tracks) {
        const newTracks = this.props.tracks.concat(tracks);
        this.props.onTracksChanged(newTracks);
    }
```
to
```js
addTracks(tracks) {
        this.props.onTracksChanged(tracks);
    }
```
We will also add the option when load a hub while remove existing tracks very soon.

**Comment by rakarnik** [comment]
Got it. I am using the URL parameter, so the App.js method does not seem to work.

Is there a different code-path which loads the default tracks for a genome that I can disable entirely? I can add them back in via the datahub as needed.

**Comment by rakarnik** [comment]
I edited models/genomes/<genome>/<genome>.js and modified the defaultTracks variable, and got this to work. Thank you for your help @lidaof!

**Comment by umasstr** [comment]
Hi @lidaof, I'm wondering if the option to remove annotation tracks in when loading a hub was ever added. Thanks!

**Comment by lidaof** [comment]
Hi @umasstr , yes, when you load a hub, add this to url `?noDefaultTracks=1`

**Comment by umasstr** [comment]
Thanks!!
