### ISSUE TITLE
Broken contact options

### ISSUE THREAD

**Issue by mashehu** [lidaof/eg-react#138]
Hi,

Just a heads-up: the slack link expired and the google group is not open anymore (both in the readme here and on the genome browser website).

**Comment by mashehu** [comment]
I get the following notification when I go to the google group link: `This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.`

**Comment by lidaof** [comment]
i see. can you check one more time your side? @mashehu thank you so much!

**Comment by mashehu** [comment]
Yes, now the google goup link works. Thanks!
