### ISSUE TITLE
Generate epgg.js for genome browser embedding

### ISSUE THREAD

**Issue by Tong-Chen** [lidaof/eg-react#139]
Thanks for the updated version of epgg. The new version looks very cool.

I have tried to install `epgg frontend` in my Centos 7 server with some changes.

1. `mv package-lock.json package-lock.json.bak`
2. delete the dependence of `fevents` in package.json
3. change the dependent version of `typescript` to `3.4.5` (my npm version 6.12.0)
4. npm install
4. configure `.env` file with firebase information.
5. Add `SKIP_PREFLIGHT_CHECK=true` to `.env` also to skip the long check.

Then `npm start`, I can view epgg with `http://47.92.159.134:3000/`, which works well.

Then I tried to embed epgg following the instructions from http://target.wustl.edu/dli/eg/embed.html. 

In my mind, I need `epgg.js` and `epgg.css`  generated in my local `frontend`.

Then I find `"build-dist": "rm -f umd/* && cd build && cp static/js/*.js ../umd/epgg.js && cp static/css/*.css ../umd/epgg.css && cp *worker.js ../umd/ && cd ../umd && sed -i ''  's//browser/./g' *.js"` in `package.json`, which may be used to generate these two files.

However, my file tree in directory `build` looks like below

```
├── js
│   ├── encoding-indexes.js
│   ├── encoding.js
│   ├── igv.js
│   ├── igv.min.js
│   ├── igv.min.js.map
│   ├── juicebox.js
│   ├── juicebox.min.js
│   ├── juicebox.min.js.map
│   └── zlib_and_gzip.min.js
├── LICENSE.html
├── manifest.json
├── precache-manifest.c66f5915e80e069b3a16c95c64d563c0.js
├── service-worker.js
└── static
    ├── css
    │   ├── 2.e3239ded.chunk.css
    │   ├── 2.e3239ded.chunk.css.map
    │   ├── main.6d6fcfc0.chunk.css
    │   └── main.6d6fcfc0.chunk.css.map
    └── js
        ├── 2.065c0104.chunk.js
        ├── 2.065c0104.chunk.js.map
        ├── main.86af7686.chunk.js
        ├── main.86af7686.chunk.js.map
        ├── runtime-main.56ebf06b.js
        └── runtime-main.56ebf06b.js.map
``` 

I could not `cp` 3 js files to one file `epgg.js`, as the same for `epgg.css`. I wonder if there is sth I misunderstood?

Besides, the command `sed -i ''  's//browser/./g' *.js` is not working in Centos. Is it a version of `sed` in MAC?

Next, I tried the following commands to concatenate all `js`/`css` file together:

```
cat static/js/*.js >../umd/epgg.js
cat static/css/*.css >../umd/epgg.css
```

When embedding epgg using `epgg.js` generated above, it complains function `renderBrowserInElement` can not be found.

But there is `window.renderBrowserInElement` in my `embed.js`.

```javascript
function(t){404===t.status||-1===t.headers.get("content-type").indexOf("      javascript")?navigator.serviceWorker.ready.then((function(e){e.unregister().then((function(){windo      w.location.reload()}))})):Cq(e)})).catch((function(){console.log("No internet connection found. Ap      p is running in offline mode.")}))}(e):Cq(e)}))}}()):(window.React=a,window.ReactDOM=i,window.hg19      Context=ie.navContext,window.DisplayedRegionModel=At,window.BrowserScene=PT,window.Custom3DObject=      DO,window.mergeGeometries=KO), 

window.renderBrowserInElement=function(e,t){return i.render(a.create      Element(l.Provider,{store:En},a.createElement(dq,{contents:e})),t)}},135:function(e,t,n){function       r(e){return(r="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(e){return typ      eof e}:function(e){return e&&"function"===typeof Symbol&&e.constructor===Symbol&&e!==Symbol.protot      ype?"symbol":typeof e})(e)}var a=n(517).b64_sha1;function o(e){this.blob=e}function i(e,t,n,a){a||      ("object"===r(t)?(a=t,t=void 0):a={}),this.url=e,this.start=t||0,n&&(this.end=n),this.opts=a}o.pro ....
```

However, the function `window.renderBrowserInElement` in `embed.js` from http://target.wustl.edu/dli/eg/embed.html is different.

```javascript
document.getElementById("root");g?(o.render(r.createElement(a.Provider,{store:c.g},r.createElement(i.a,null)),g),Object(s.a)()):(window.React=r,window.ReactDOM=o,window.hg19Context=u.a.navContext,window.DisplayedRegionModel=l.a,window.BrowserScene=h.a,window.Custom3DObject=f.a,window.mergeGeometries=d.a),

window.renderBrowserInElement=((e,t)=>o.render(r.createElement(a.Provider,{store:c.g},r.createElement(p.a,{contents:e})),t))},function(e,t,n){"use strict";var r=n(19),o="function"===typeof Symbol&&Symbol.for,a=o?Symbol.for("react.element"):60103,i=o?Symbol.for("react.portal"):60106,c=o?Symbol.for("react.fragment"):60107,s=o?Symbol.for("react.strict_mode"):60108,u=o?Symbol.for(
```

I wonder if there is something wrong with my operations?

Thanks!

Chen Tong

**Comment by lidaof** [comment]
Hi @Tong-Chen , first all what you did is all correct. Glad you figure out the annoying fevents dependency is removable and the code also works in newer typescript. from the build-dist command you probably can tell it's trying to combine all .js and .css to single file epgg.js and epgg.css separately. It was built using v48.x...the new version of build splits the .js file as you have seen, I haven't figure that part yet...

for the sed command, it tried to remove browser in the url, i am sure CentOS should have this command as well. or you can delete the base parameter in AppRouter file.

**Comment by lidaof** [comment]
right now it's hard to tell which js files are web worker files...from the current build...

**Comment by Tong-Chen** [comment]
Thanks for your kind explanations. The `sed` command you meaning substitute `/browser`? Normally I would do using something like `sed -i 's#/browser##g' *.js`. 

Sorry, I do not understand this "right now it's hard to tell which js files are web worker files...from the current build..."?

**Comment by lidaof** [comment]
Hi @Tong-Chen , regard the sed command you are right. for the worker thing, because we are using web workers, previously the build step will generate the ****.worker.js file (now seems it dose not). I will spend some time on this issue next week.

**Comment by Tong-Chen** [comment]
Thank you!

**Comment by lidaof** [comment]
Hi @Tong-Chen sorry for the super long delay, the embed function was finally updated...please check https://github.com/lidaof/eg-react#embedding-the-browser-in-any-html-file. feel free to let me know any issues.
