### ISSUE TITLE
Failed to access to WashU browser with TypeError at https://unpkg.com/react-plotly.js

### ISSUE THREAD

**Issue by songtaogui** [lidaof/eg-react#140]
Hi,
@lidaof 
I have failed to access to my WashU browser recently (which could be normally accessed a month ago), with error messages below:

It seems that some of the online JS scripts were not-accessible during the launching of the browser , but the URLs of these JS scripts were accessible when I manually click on them. Do you have any idea on what's the problem? Is there something wrong with my internet?

Any suggestion would be grateful.

Best wishes,

Songtao Gui

**Comment by lidaof** [comment]
probably something happened with npm, I can visit your mirror nicely now actually.
can you retry? another thing is you can download the .js file and put in your local server.

![image](https://user-images.githubusercontent.com/102806/68312653-ff72a380-0078-11ea-806e-3a4d23791e55.png)

**Comment by songtaogui** [comment]
Hi,
@lidaof 

Thank you for your kindly help, I have made the js files local and now it works fine.

Considering that this issue exposed my IP, which may be insecure, so would you please delete this issue or the address in the image?

Thank you again for your kindly help.

Best wishes,

Songtao Gui

**Comment by lidaof** [comment]
sure thing, removed screenshot! @songtaogui
