### ISSUE TITLE
Unkown genome name (legacy browser)

### ISSUE THREAD

**Issue by wmegchel** [lidaof/eg-react#141]
Hi, 
since today I cannot select any genome in the **legacy** browser. I get the error "Unknown genome name mm9". Same for mm10 or hg38.

Best,
Wout

**Comment by lidaof** [comment]
Hi @wmegchel there was a database error, should be fixed now.

**Comment by wmegchel** [comment]
Yes, it is fixed. Thanks for the quick response!
