### ISSUE TITLE
Visualize local cooler file

### ISSUE THREAD

**Issue by lucasvduin** [lidaof/eg-react#146]
Hi,

Is it possible to view a local cooler file like you would with a hic file? I have a cooler file but not the raw reads, so afaik I can't construct a hic file.

Thanks in advance!

**Comment by lucasvduin** [comment]
I solved in the mean time, by using cooler dump and using the resulting file as input for juicebox Pre, using the 'short with score' input file format

**Comment by lidaof** [comment]
Very nice @lucasvduin. We don't have a cooler format based Javascript parser...that's the reason we don't have the local cooler option. Glad you figured out a way!
