### ISSUE TITLE
hg19 Missing track for reordering

### ISSUE THREAD

**Issue by ykai16** [lidaof/eg-react#150]
Hi Daofeng,

Recently when we are uploading a quantitative categorical dataset for visualization, the browser keeps returning a "hg19 Missing track for reordering" error. We used a json file for the visualization, and it worked 2 months ago. But for the same file, it is not working now. Could you point out how we could get rid of this error? Thanks!

The json file we used could be found here: http://genomebrowser-uploads.hms.harvard.edu/data/yk233/diHMM/epilogo/diHMM_epilogos.json

**Comment by lidaof** [comment]
Hi @ykai16 sorry for late reply.
Can you update your json file and replace http with https in the url links? Thank you.

**Comment by ykai16** [comment]
Thanks for the help! Just replaced http with https, but still got the same message.

**Comment by lidaof** [comment]
Hi @ykai16 sorry for that, the cgi-bin program tells this error:
```curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```
I downloaded your files to https://wangftp.wustl.edu/~dli/ykai16/, could you please give it a try?

**Comment by ykai16** [comment]
Thanks @lidaof ! I tried the files in your site and it works. Now I see where the problem is. Thanks a lot for the help!

**Comment by lidaof** [comment]
You are welcome @ykai16 !
