### ISSUE TITLE
Use HTTP or HTTPS

### ISSUE THREAD

**Issue by skotechaeng** [lidaof/eg-react#152]
Hello, I have a question about the following:  We have deployed the browser container locally and implemented TLS.  When TLS is applied all images associated with https://epigenomegateway.wustl.edu/ is not loading.  This documentation (https://epigenomegateway.readthedocs.io/en/latest/faq.html#use-http-or-https) says we can use http://epigenomegateway.wustl.edu/browser without the s.  I have the following question:

If I have the container deployed locally, can I just point to my local installation to avoid making the call out to http://epigenomegateway.wustl.edu/browser?

Any other work arounds?

**Comment by lidaof** [comment]
Hi @skotechaeng if you visit an HTTPS site, any link with HTTP cannot be accessed, but not vice versa. From HTTPS to HTTPS should be fine....for you local installation if you want completely avoid image request etc, you would need to download the images to your local instance.

(if you always points to our HTTPS links, should not be a problem in my understanding...)

**Comment by skotechaeng** [comment]
Thanks @lidaof
