### ISSUE TITLE
Genome comparison issue when switching genomes

### ISSUE THREAD

**Issue by adu345** [lidaof/eg-react#155]
![image](https://user-images.githubusercontent.com/33333772/76127020-41c7d500-5fc6-11ea-8c59-bb73f2517d7b.png)
Switching from one genome to another (here hg38 to mm10) and then using genome comparison tracks makes an incorrect comparison.
Looking at the comparison track shows that hg38 stays as the base genome instead of switching to mm10. The comparative genome is rheMac8, which is correct.
Quick fix is just refreshing the page, but this can be confusing if user is unaware.

**Comment by lidaof** [comment]
Hi @adu345 , when you switch genome, the tracks should be cleared to the default tracks of that genome, can you tell me how to reproduce this issue?
Thanks for reporting this.

**Comment by adu345** [comment]
1. Choose any genome to start with that has a genome comparison track. 
2. Display the genome comparison track.
3. Switch to another genome with a genome comparison track.
4. Display the second genome's genome comparison track.
5. Hover over the comparison track to see which genomes are being compared (may need to zoom in or out to see the popup).

**Comment by lidaof** [comment]
sorry for late reply...i think it's fixed now? @adu345

**Comment by lidaof** [comment]
closing for now, feel free to reopen it or open a new issue.
