### ISSUE TITLE
index file is not working from build folder

### ISSUE THREAD

**Issue by mang7** [lidaof/eg-react#156]
Hi @lidaof 

index.html is showing blank when I use npm run build ("build": "react-app-rewired build" )
and getting error in console as "**Error during service worker registration: TypeError: Failed to register a ServiceWorker: The URL protocol of the current origin ('null') is not supported.**"

![error](https://user-images.githubusercontent.com/3917990/76953811-58125100-6935-11ea-9b97-858ee26360d8.PNG)

I want to use build/index.html  as a static file in express(node) for authentication.
Is there any alternate or how can I fix that issue

**Comment by lidaof** [comment]
Hi @mang7 , sorry for late reply. are you able to compile it? I mean when you run `npm start`, can you start the development server?

**Comment by mang7** [comment]
Thanks @lidaof,

Yes I was able to compile it using npm run build but when I tried to open index.html file from build folder then blank page shown to me. 

I'm using node express for authentication and want to deploy react app and express app on same port. So I want to use frontend app as static file.

How can I access frontend app as a static files?

**Comment by lidaof** [comment]
Hi @mang7 , do you mean if you open index.html in a text editor and it's empty...pretty strange....
in our case, we put the entire build folder under an Apache servered folder...can you try that see if it's working?  Sorry I have no express experience...

**Comment by mang7** [comment]
Hi @lidaof,
After executing command "npm run build".
index.html contains HTML tags and files reference in build folder but nothing displayed in browser. Is there any option or setting to test build folder locally? 
Is there any changes required in .env file. I've added firebase setting in .env file before building or are you using some different scripts instead of npm build?

**Comment by lidaof** [comment]
if index.html contains html tags you should be OK, the package.json file you may need change the homepage url, currently it assumes it serves under a subfolder /browser/, you can try remove it and re-build see if it helps.

**Comment by mang7** [comment]
Hi @lidaof,
Thank for above information. I'm able to see index.html from build folder now.
Tracks are not displaying from after npm run build it was displaying when I used npm start. I've added below details in .env file 
REACT_APP_FIREBASE_KEY="my firebase key"
REACT_APP_FIREBASE_DOMAIN="my firebase domain key"
REACT_APP_FIREBASE_DATABASE="my firebase data key"
REACT_APP_FIREBASE_STORAGE_BUCKET="my storage key"
PUBLIC_URL="http://localhost:3000/"
NODE_ENV="production"
Is there anything need to be done while executing "npm run build"?
![image](https://user-images.githubusercontent.com/3917990/77454017-00d11c80-6e1e-11ea-8568-8cac421fc37d.png)

**Comment by lidaof** [comment]
i think this means it's built successfully. there is no more thing need to be done besides that. sometimes you may see the data fetch error as our API is waking. try refresh. the repeatmasker track error is weird though...can you try pull the `dev` branch and re-build.

git checkout dev
git pull origin dev
