### ISSUE TITLE
session issue

### ISSUE THREAD

**Issue by ZunpengLiu** [lidaof/eg-react#157]
Hi, lidaof!

I have one question about the function of session in App.

Does session only save the genomic location of track? not all the setting parameters?  like the absolute path of bigwig/bed files like IGV?

When I retrieve their session or uploaded the saved session, it didn't upload the local files?

Many thanks for you help!

Looking forward to your Kindly reply!

Zunpeng

**Comment by lidaof** [comment]
Hi Zunpeng @ZunpengLiu , if you mean tracks from your local computer, these tracks cannot be saved to session as web browser need permission to access uses' local files. IGV is desktop software thus doesn't have that restriction. It's a security setting for any web browser. Remote tracks can be saved to session.

**Comment by ZunpengLiu** [comment]
> Hi Zunpeng @ZunpengLiu , if you mean tracks from your local computer, these tracks cannot be saved to session as web browser need permission to access uses' local files. IGV is desktop software thus doesn't have that restriction. It's a security setting for any web browser. Remote tracks can be saved to session.

OK, I will try the remote function. Thank you for your help and patient reply!
