### ISSUE TITLE
Screenshot for long range interactions with negative scores

### ISSUE THREAD

**Issue by souryacs** [lidaof/eg-react#159]
Hi,
I am a regular user of WashU browser and love the new version. However, I found some issues in the screenshot application:
1) The screenshot does not show any long range interaction with negative score. Now, why would an interaction have a negative score, right? I wanted to visualize two categories of interactions (say categories A and B) on the same track, and therefore applied negative score to one category and positive to the other. Using the primary and secondary colors for +ve and -ve scores, I can differentiate between the two categories. 
So far so good, but when I tried to export the screenshot, the interactions with negative scores are completely removed from the visualization. Can you please check it?
2) The screenshot, when exported as pdf, shows tracks mixed with one another, with disrupted track boundaries. It would be beneficial if the pdf version of screenshot is error-free.

**Comment by lidaof** [comment]
Hi @souryacs , 
1, can you email the long range url for for me to take a look?
2, pdf conversion on client side (web browser) is tricky, can you use SVG format? you can print SVG to pdf on your computer, which I think will give better results.

**Comment by souryacs** [comment]
Hi @lidaof 
Thanks for your reply. Suppose, I specify the following two interactions:
chr1	1502499	1502501	chr1:1517499-1517501,50	3	.
chr1	1572499	1572501	chr1:1637499-1637501,-50	4	.
And then check the region chr1:1500000-1640000, set display mode "arc", max score = 50, min score = -50, and two different colors (primary and secondary).  I can visualize two interactions with different colors. But when I try to get the screenshot, the interaction with negative score disappears. Please check and let me know for any further information.

**Comment by lidaof** [comment]
Hi @souryacs , I pushed an update this morning. can you check if it's fixed on your side?

**Comment by souryacs** [comment]
Hi @lidaof 
Yes now I can see both interactions in the screenshot. Thank you so much for such a quick response. The browser is really cool and love to use it. Thanks.
