### ISSUE TITLE
Search by gene not working for yeast genome

### ISSUE THREAD

**Issue by arnavm** [lidaof/eg-react#160]
Searching by gene name does not work for the yeast genome. Not sure about the others.

**Comment by debugpoint136** [comment]
Hi @arnavm I am examining this issue. 
(ETA: Thursday 05/07. Let me know if that works)

**Comment by lidaof** [comment]
ping @debugpoint136 to take a look, thanks.

**Comment by lidaof** [comment]
sorry for the delay, this has been fixed.
Closing this one but feel free to open any new issue. Thank you!
