### ISSUE TITLE
Need to update the embedding sample code in README.md

### ISSUE THREAD

**Issue by haizi-zh** [lidaof/eg-react#161]
I need to embed the browser into my own web application, so I tried the suggested code snippet in `README.md` (https://github.com/lidaof/eg-react/blob/master/README.md#embedding-the-browser-in-any-html-file). 

However, the example doesn't work. The refGene track reads "Data fetch failed". It seems that the track tries to fetch refGene data from https://api.epigenomegateway.org , but this API server has ceased functioning. The following is the error message from the console:

```
epgg.js:1 GET https://api.epigenomegateway.org/mm10/genes/refGene/queryRegion?chr=chr5&start=51141244&end=53709994 net::ERR_CONNECTION_REFUSED
```

However, if we replace this line:
```
<script src="https://unpkg.com/epgg@latest/umd/epgg.js"></script>
```
with another js script:
```
<script src="https://target.wustl.edu/dli/eg/epgg.js"></script>
```

The problem goes away. The only difference between these two files are that, the latter fetches data from another API server: https://lambda.epigenomegateway.org/v2

I suggest you update the `README.md` and the documentation as well (https://eg.readthedocs.io/en/latest/installation.html#embedding)

**Comment by lidaof** [comment]
Yes, thank you @haizi-zh . We indeed update the API address. I will update the readme asap.

**Comment by lidaof** [comment]
closing for now, feel free to reopen it or open a new issue.
