### ISSUE TITLE
Convert Gene Symbol to Chromosome Position

### ISSUE THREAD

**Issue by godtao2** [lidaof/eg-react#162]
I need to embed the browser into my own web application,  however, the browser needs URL parameter position to specify the default genomic position. I want to get this position automatically when I input any gene symbols. How can I do this?  P.S. I saw the washu browser has the function to gene search(just click "say gene"), but how can I use this function by javascript or APIs?

**Comment by godtao2** [comment]
Thanks for your assistance! @lidaof  This API works well! By the way, does this API always exist on the internet (or just for a while)？ This function is important for my web application.

**Comment by lidaof** [comment]
This API is used by our Browser so it always exists.

**Comment by godtao2** [comment]
OK！Thanks.

**Comment by godtao2** [comment]
Sorry to disturb you again. @lidaof But I have a problem when I search the gene symbol using the API.  The error message shows that the Internal server happens error. Like below:
![image](https://user-images.githubusercontent.com/52396475/84797931-f0030200-b02c-11ea-8205-0f4a8b4e7765.png)

**Comment by godtao2** [comment]
Sorry to disturb you again. @lidaof  But I have a problem when I search the gene symbol using the API. The error message shows that the Internal server seems happens error as below:
![微信图片_20200616235844](https://user-images.githubusercontent.com/52396475/84798283-59831080-b02d-11ea-8d08-a5b8c39df690.png)

**Comment by lidaof** [comment]
yeah,,,sometimes this happens, you would need try more times. copy @debugpoint136 for checking.

![image](https://user-images.githubusercontent.com/102806/84807717-46d8ef00-afcd-11ea-9178-deaf17195163.png)

**Comment by lidaof** [comment]
closing for now, feel free to reopen it or open a new issue.
