### ISSUE TITLE
About local data hub

### ISSUE THREAD

**Issue by ddepierre** [lidaof/eg-react#163]
Hi Washu Browser team,

I've got few questions about local data hub.

Once I loaded local tracks and setted up parameters such as tracks color, Yaxis limits and whatever, can I download a hub.config.json file to reload same tracks with same parameters or do I have to write it by hand using https://eg.readthedocs.io/en/latest/datahub.html ?

I started to write a hub.config.json test file by hand, I don't really get how does smooth parameter work. On the browser, I setted it to 3 pixels, when I set it on 3 in the hub.config.json as : 
 `      {
          "filename": "my_most_beautifull_track1.bw",
          "type": "bigwig",
          "name": "track1",
          "options": {"color": "#b825b5", "height": 100,
                      "yScale": "fixed", "yMax": "7", "yMin": "0",
                      "smooth": "3"}
      },`

Loading successful but tracks were completely flat and I had to reset it to 0 then to 3 to obtain the smooth I wanted. I guess it is due to :  _"The browser will use the mean values from region [current_position - smooth, current_position + smooth]"_. 
Is the smooth computed from the current window view ? Do I have to set a current position/window which is used to compute the smooth ? What did I miss ?

Thanks,

David

**Comment by lidaof** [comment]
Hi David @ddepierre , unfortunately so far the you need to setup the options for local data hubs, I can try to code something to make the local hub downloadable after configuration.

Smooth function make the curve looks flat, it uses data from nearby `smooth` pixels to average the data, say when you set smooth as 1, at pixel 1000, it will use average of data at 999, 1000 and 1001px to represent data at 1000px, it does nothing with current position/window. Is it clear?

thanks!

**Comment by ddepierre** [comment]
Hi, 
Thanks for your answer, but I still have an issue with smooth param in hub.config.json. 
Here I compare the same bigwig track, the pink one is loaded using hub.config.json `[
      {
          "filename": "My_most_beautifull_track1.bw",
          "type": "bigwig",
          "name": "track1_configJSON",
          "options": {"color": "#b825b5", "height": 100,
                      "yScale": "fixed", "yMax": "7", "yMin": "0",
                      "smooth": "3"}
      },
]`

and green one is handly loaded and setted up.

![washu1](https://user-images.githubusercontent.com/25797403/85854806-6504d300-b7b5-11ea-8520-7646105c24ca.png)

But as you can see, it seems there is a problem with smooth function when applied from hub.config.json file and I have to reset the smooth param handly to 0 then to 3 to make the pink track looking like the green.


Here are parameters for both track, they are set the same and for pink one well recovered from json file :  
![washu2](https://user-images.githubusercontent.com/25797403/85854809-66360000-b7b5-11ea-9128-9c712f0e8749.png)
![washu3](https://user-images.githubusercontent.com/25797403/85854811-66360000-b7b5-11ea-89af-af66ffd271d3.png)

But actually I just realized the problem comes from smooth param on hub.config.json file :
 `[
      {
          "filename": "My_most_beautifull_track1.bw",
          "type": "bigwig",
          "name": "track1_configJSON_NO_SMOOTH",
          "options": {"color": "#4f75b3", "height": 100,
                      "yScale": "fixed", "yMax": "7", "yMin": "0"
                    }
      },
      {
          "filename": "My_most_beautifull_track1.bw",
          "type": "bigwig",
          "name": "track1_configJSON_SMOOTH_0",
          "options": {"color": "#6c2f9e", "height": 100,
                      "yScale": "fixed", "yMax": "7", "yMin": "0",
                      "smooth": "0"}
      },
      {
          "filename": "My_most_beautifull_track1.bw",
          "type": "bigwig",
          "name": "track1_configJSON_SMOOTH_3",
          "options": {"color": "#b825b5", "height": 100,
                      "yScale": "fixed", "yMax": "7", "yMin": "0",
                      "smooth": "3"}
      },
]`

Blue one has no smooth param on the json, purple one has smooth set to 0 and pink one has smooth set to 3 (see the hub.config.json file attach below) : 

![washu417](https://user-images.githubusercontent.com/25797403/85862695-68eb2200-b7c2-11ea-959c-21abf36d231e.png)

 `[
      {
          "filename": "My_most_beautifull_track1.bw",
          "type": "bigwig",
          "name": "track1_configJSON_NO_SMOOTH",
          "options": {"color": "#4f75b3", "height": 100,
                      "yScale": "fixed", "yMax": "7", "yMin": "0"
                    }
      },
      {
          "filename": "My_most_beautifull_track1.bw",
          "type": "bigwig",
          "name": "track1_configJSON_SMOOTH_0",
          "options": {"color": "#6c2f9e", "height": 100,
                      "yScale": "fixed", "yMax": "7", "yMin": "0",
                      "smooth": "0"}
      },
      {
          "filename": "My_most_beautifull_track1.bw",
          "type": "bigwig",
          "name": "track1_configJSON_SMOOTH_3",
          "options": {"color": "#b825b5", "height": 100,
                      "yScale": "fixed", "yMax": "7", "yMin": "0",
                      "smooth": "3"}
      },
]`

Do I missuse the smooth param in json file ?

Best,

David

**Comment by lidaof** [comment]
This looks pretty interesting/weird 😄  @ddepierre 

smooth should be a number, try use 1, 2, 3 instead of "1", "2" "3", I will cast it to integers in the code.

**Comment by ddepierre** [comment]
Aaaah ok ! it works with `"smooth": 3` ! 
Thanks a lot !

David

**Comment by lidaof** [comment]
That's great! I applied the cast, "3 "will also work on next release.

**Comment by ddepierre** [comment]
Hi, 
As you answer fast, I'm gonna benefit again.
I've got an issue with bed file loading using hub.config.json: 

I managed to hanldy load a bed file (histone modification domains calling) in blue. When I try to load the same bed file using hub.config.json script with: 

`  {
  		"filename": "The_bed_s_too_big_without_you.bed",
  		"type": "bed",
  		"name": "BED_HUBLY_LOADED",
  		"options": {"displayMode": "density", "color": "#42f542", "height": 40}
  },`

I get that: 
![whasu_5](https://user-images.githubusercontent.com/25797403/86242082-6282ee80-bba4-11ea-8251-b54c9d384a56.png)
 
What did I miss ?

BTW, the dynamic plot is so great ! Thanks for that ! Is there a way to add it in the hub.config.json file ?

Best,

David

**Comment by lidaof** [comment]
Hi @ddepierre David, for bed track, you did upload put the .tbi file together with the bed.gz and upload the entire folder? It should be work as I tested from my side. thanks for using dynamic plot, it can be used in local hub as well.

this is my files in the folder I am going to upload:
![image](https://user-images.githubusercontent.com/102806/86251584-ac091480-bb77-11ea-8db1-5d300b63362e.png)

and this is the content of hub.config.json:

```json
[
    {
        "filename": "TW551_20-5-bonemarrow_MRE.CpG.bigWig",
        "type": "bigwig",
        "name": "a bigwig track",
        "options": {"color": "red", "smooth": "4"}
    },
    {
        "filename": "scATAC.bed.gz",
        "type": "bed",
        "name": "a bed track",
        "options": {"displayMode": "density", "color": "#42f542", "height": 40}
    },
    {
    	"filename": "a.dbg.gz",
    	"type": "dbedgraph",
   		 "name": "a dbedgraph track",
	    "options": {
	        "dynamicLabels": ["stage1","stage2","stage3","stage4","stage5","stage6","stage7","stage8","stage9","stage10"],
	        "dynamicColors": ["red", "blue", "#00FF00", 0],
	        "useDynamicColors": true
	    	}
    }
]
```  

and the results:
![image](https://user-images.githubusercontent.com/102806/86251791-f25e7380-bb77-11ea-911d-55c2617cecd6.png)

let me know if it doesn't work for you, thanks!

**Comment by lidaof** [comment]
closing for now, feel free to reopen it.
