### ISSUE TITLE
Tracking clicks and page view

### ISSUE THREAD

**Issue by mang7** [lidaof/eg-react#167]
Hi @lidaof ,

Have you written code to track page view and click events in this application.?

**Comment by lidaof** [comment]
Hi @mang7 , if you mean which buttons use clicked? no. I do have a google analytics account linked for user access stats..

**Comment by mang7** [comment]
> Hi @mang7 , if you mean which buttons use clicked? no. I do have a google analytics account linked for user access stats..

**Comment by mang7** [comment]
Hi @lidaof , It means application is tracking if user clicks on  Apps, Tracks, settings in nav bar dropdown? Application only track page view if user go to different route

**Comment by lidaof** [comment]
Hi @mang7, we don't track that behavior... actually I am not sure how to do that... What do you need?

**Comment by lidaof** [comment]
closed for now, feel free to open new issues.
