### ISSUE TITLE
Unable to Add Remote Data Hub

### ISSUE THREAD

**Issue by ericaenjoy3** [lidaof/eg-react#169]
Hi,

With the [WashU Genome Browser](https://epigenomegateway.wustl.edu/browser/) (hg19), clicking the 'Load from URL' icon using the remote hub url of a dummy data file (https://liuy22.u.hpc.mssm.edu/washu/dummy.json) does not generate any response.

I also tried uploading the same datahub file from my local machine, and no response was seen either. 

I am wondering if you may please care to help with this?

Warmly appreciated,

Yiyuan

**Comment by lidaof** [comment]
H Yiyuan @ericaenjoy3 ,

The data hub is an array of json objects, can you replace your file with following content:

```json
[
{
    "type": "bigwig",
    "name": "example bigwig",
    "url": "https://vizhub.wustl.edu/hubSample/hg19/GSM429321.bigWig",
    "options": {
        "color": "blue"
    }
}
]
```
let me know if it's not working.

**Comment by lidaof** [comment]
And also thank you for reporting this issue. Next release it will print this message instead of doing nothing. Thank you again! @ericaenjoy3 

![image](https://user-images.githubusercontent.com/102806/89066119-7bf99080-d332-11ea-839f-b91fe464c867.png)

**Comment by ericaenjoy3** [comment]
Thanks very much for your prompt help!
