### ISSUE TITLE
Remove saved session

### ISSUE THREAD

**Issue by LaureTomas** [lidaof/eg-react#171]
I'm using the old version of the washU browser (http://epigenomegateway.wustl.edu/legacy/) because I use the session link to share it with my colleagues, but I can't remove a saved session.

How can I remove a saved session? Since with the ID it appears all the saved session under this ID, but I only want to keep one of them

**Comment by lidaof** [comment]
Hi @LaureTomas,  we removed that `delete session` function as everyone can delete that once session Id become public. I can manually delete them for you. You can email me the session id and the ones you want to remove.

**Comment by LaureTomas** [comment]
Thank you so much, I will email you the specific sessions

**Comment by lidaof** [comment]
closed for now, feel free to open new issues.
