### ISSUE TITLE
Enabling Options of 'Aggregate method' and 'Smooth' for bigWig Tracks in an Embedded Browser

### ISSUE THREAD

**Issue by ericaenjoy3** [lidaof/eg-react#172]
Hi @lidaof,

I noticed that in an embedded WashU Epigenome browser, the options of 'Aggregate method' and 'Smooth' are missing from the option menu when right clicked on a bigWig track, whereas these options are present in the official browser.

Placing "options": { "aggregateMethod": "MEAN", '"smooth": 0 } in the 'embed.html' would introduce a bug. Would you please be so kind to look into this? Many thanks!

The official browser:

![washu_smooth](https://user-images.githubusercontent.com/6052159/89726861-7fa1ad00-d9ed-11ea-9204-334feee8de97.png)

The embedded browser:
![washu_nonsmooth](https://user-images.githubusercontent.com/6052159/89726868-9ba54e80-d9ed-11ea-8028-8aa5ee53eb29.png)

**Comment by lidaof** [comment]
Hi @ericaenjoy3 , correct, the embedded version is based on version 48 of the codebase, at later I was trying to make a new embedded version but get stuck in one error. I will recheck this.

**Comment by ericaenjoy3** [comment]
Hi @lidaof, many thanks! Would you please keep me informed of an update? Thanks again!

**Comment by lidaof** [comment]
Sure, once I figured out that issue I will update the embedded scripts.
