### ISSUE TITLE
SNP Annotation Track in an Embedded Browser

### ISSUE THREAD

**Issue by ericaenjoy3** [lidaof/eg-react#173]
Hi @lidaof, 

As SNP track type is supported in the WashU Epigenome Browser (https://epigenomegateway.readthedocs.io/en/latest/datahub.html#type), I specified {"type": "snp", "name": "Ensembl SNPs", "genome": "hg19"} in the json configuration part of the embedded html file, and this led to a bug of 'unknown track type: "snp" '. In an essence, I am trying to load the 'variation' annotation track ('Snps from Ensembl'). How would you recommend achieving that in the embeded browser? Thanks.

**Comment by lidaof** [comment]
sorry for that @ericaenjoy3, that function is not available on the embedded scripts. For now, I would recommended using `iframe` instead, this approach you create datahub dynamically, and load the data hub through hub url in an iframe. Example: https://wangftp.wustl.edu/~dli/test/eg_iframe.html, using this approach you are always using the latest version of the browser.

Would this work for you?

**Comment by ericaenjoy3** [comment]
Hi @lidaof, my apologies for the delayed response. Do you know why your url (https://epigenomegateway.wustl.edu/browser/?genome=hg19&hub=https://wangftp.wustl.edu/~dli/test/a.json) works perfectly with data track retrieval but mine (https://epigenomegateway.wustl.edu/browser/?genome=hg19&hub=https://liuy22.u.hpc.mssm.edu/washu/dummy.json) failed without any error message? Many thanks!

**Comment by ericaenjoy3** [comment]
Hi @lidaof, I figured out that in my json file missed '"showOnHubLoad": true', and with the option set true, it works. Many thanks!

**Comment by lidaof** [comment]
nice you figured it out!
