### ISSUE TITLE
Remote tracks 

### ISSUE THREAD

**Issue by umasstr** [lidaof/eg-react#174]
I am attempting to upload a remote data hub. The JSON files are recognized, but tracks are not displayed. My bigwigs and bigbeds, however, _can_ be displayed if uploaded individually. I cannot find any formatting issues with my JSON (https://dl.dropboxusercontent.com/s/r8lgzgkxk4faigz/hub.config.json)

To rule out formatting issues, I also tried to upload the JSON from issue #169 (https://liuy22.u.hpc.mssm.edu/washu/dummy.json). There is no error listed, the browser just remains empty.

![image](https://user-images.githubusercontent.com/44478133/90574043-f1b08980-e185-11ea-89f4-1fb61a02e586.png)
 
Thank you for your help.

**Comment by lidaof** [comment]
Hi @umasstr there is one option to specify track to be display when hub loaded, by default the tracks are hidden. please check this https://eg.readthedocs.io/en/latest/datahub.html#showonhubload

for example, change your first track to :

```json
{
"url": "https://dl.dropboxusercontent.com/s/r5oxrmd5ci35gd9/EM_Yap.dup.bw",
"type": "bigWig",
"name": "YAP EM",
"options": {
"color": "#D0021B"
},
"showOnHubLoad": true
}
```

this default behavior makes loading hub fast when the hub contains hundreds of tracks.

**Comment by umasstr** [comment]
Hi @lidaof, the JSON has been updated, but produces "Cannot load the hub. Error: HTTP 0"

**Comment by lidaof** [comment]
wried...it's working here

![image](https://user-images.githubusercontent.com/102806/90578480-080c1480-e189-11ea-8da7-c61cc970cd09.png)

![image](https://user-images.githubusercontent.com/102806/90578501-15290380-e189-11ea-92cb-461c5fbbb10c.png)

**Comment by umasstr** [comment]
Thanks for testing this out. Worked in an incognito tab.

Thanks for the help!!
