### ISSUE TITLE
Issue with WashU browser

### ISSUE THREAD

**Issue by vivekliai** [lidaof/eg-react#176]
Hi,

We still uses the old (legacy) version of WashU browser as several features are better compared to new (Display loops only within current window and Display loops with scores in a specified range). Unfortunately for last few months, the legacy version is also not working properly. Tracks are arbitrarily not loaded, or sometimes partially loaded (ChIP-peaks or Hi-C contacts are randomly missing). So, it would be nice if you can fix this issue with the legacy browser to  ensure if all tracks can be uploaded properly. 

Or is it possible to add these two features to the  new WashU browser: Display loops only within current window and Display loops with scores in a specified range?

We will greatly appreciate your help.

Thanks,
Vivek

**Comment by lidaof** [comment]
Sure, I will work with this 2 features. thanks for suggestion @vivekliai. for old browser, try reduce number of tracks, or send me your hub I can take a look

**Comment by lidaof** [comment]
Hi @vivekliai please refresh to v52.1.0, right click on longrange or hic tracks should bring you the new configurations:

![image](https://user-images.githubusercontent.com/102806/92974980-f991df80-f44c-11ea-82fa-f75a9146e596.png)


I tested they seem work fine :)
but let me know if there is any issue. Thank you so much.

**Comment by vivekliai** [comment]
Thanks Daofeng. Your help is greatly appreciated. 

If possible, can you also add the option of add to all track as used to be in legacy version(it used to apply same setting to all tracks). I am attaching the picture of that. 

Thanks again,
Vivek

**Comment by lidaof** [comment]
Hi @vivekliai , you can hold shift while clicking the track (multiple selection), then you can right click to do operation on multiple tracks.

**Comment by vivekliai** [comment]
Thanks for suggestion Daofeng.

I looked at the data in current view (no expansion) it removed majority of the outside interaction but leaves the interaction which is going towards right side of out of view. I am sending you one of the track.

Thanks,
Vivek

**Comment by lidaof** [comment]
Yes, that's correct, because one of the anchor point is still in the view window, right?

**Comment by vivekliai** [comment]
Hi Daofeng,

That’s true. But it’s important to get only current view (that mean only those where both dataset in the current view) specially when you are saving the screen shot like legacy version. The option which you added certainly removes all the interaction where out of frame data point is left side of current frame but does not remove if out of frame data point is right side of current frame.

Best,
Vivek

**Comment by lidaof** [comment]
Sure, I added another option, please refresh give it a try. Thank you!

![image](https://user-images.githubusercontent.com/102806/92985786-73d95880-f47b-11ea-822f-8ec4d4cf638d.png)

**Comment by vivekliai** [comment]
Thanks Daofeng. Greatly appreciated.

Best,
Vivek

**Comment by souryacs** [comment]
Hi @lidaof 
With respect to these two options: 1) data in current view, 2) both anchors in view window, do you have corresponding long range track options which I can put in the datahub .json file? Currently individual tracks need to be manually adjusted, so any such track option would be very useful to handle a large number of tracks.

**Comment by lidaof** [comment]
Hi @souryacs sorry for missing that in docs. this 2 properties in `options` are `fetchViewWindowOnly` and `bothAnchorsInView`, you can set them as `true` in your data hub file.

**Comment by souryacs** [comment]
Thanks @lidaof for your quick response. I've checked it and it's working fine. Really helpful. Many thanks.

**Comment by lidaof** [comment]
You are welcome @souryacs
