### ISSUE TITLE
Remote tracks not loading

### ISSUE THREAD

**Issue by grace-hansen** [lidaof/eg-react#177]
I cannot currently load remote tracks from a server. If I load them locally they load fine; however if I load them from the server I get a 'data fetch failed' error. I'm loading HiC data in longrange format by loading the *lr file from the server; there is a *lr.tbi file with a matching name in the same directory.

**Comment by lidaof** [comment]
Hi @gracilis it's likely a CORS issue, would you mind send me the url?  also check here maybe: https://eg.readthedocs.io/en/latest/tracks.html#configure-your-webserver-to-enable-cors?

**Comment by lidaof** [comment]
Sorry about that @gracilis , would you mind DM me your track url? thanks

**Comment by lauzikaite** [comment]
Hello, I've been having the same issue. The bigwig is loaded successfully from local storage, but not remote. However, the same URL works with UCSC genome browser. Would you mind checking my url please? Thank you!
http://bioinf.stemcells.cam.ac.uk/test/test.bw

**Comment by lidaof** [comment]
Hi @lauzikaite , the reason is that you need enable CORS on your apache serve, please check https://eg.readthedocs.io/en/latest/tracks.html#configure-your-webserver-to-enable-cors, let me know if you need more info. Thanks.

**Comment by lauzikaite** [comment]
Thanks so much, @lidaof, rebooting the apache server helped

**Comment by lidaof** [comment]
nice! thanks for the feedback! @lauzikaite
