### ISSUE TITLE
Rna-Sea data

### ISSUE THREAD

**Issue by UgoBor** [lidaof/eg-react#179]
Hi,
is it possible to visualize with your browser RNASeq data? 
I am thinking at a track where the genes are color coded depending if they are up or down regulated and, possibly, visualized with a scale of colors related to the fold change values.
thank you

**Comment by lidaof** [comment]
That's a great idea! @UgoBor . I will think how to implement this.
we currently don't support this visualization, right now users are formatting RNA-seq data to bigWig or bedGraph values over exons and displayed them as numerical track.
