### ISSUE TITLE
Cistrome public tracks

### ISSUE THREAD

**Issue by umasstr** [lidaof/eg-react#183]
Hi Daofeng,

The cistrome data browser has enabled users to view track files on WashU. Their one-click redirect to a datahub works well. 
I would like to superimpose these tracks onto my data or others fetched from Cistrome, but the tracks will not load onto my session as a remote track. For example:

1. I search for some TF on Cistrome Data Browser > Visualize > Wash U ([sample link](http://epigenomegateway.wustl.edu/browser/?genome=mm10&hub=http://dc2.cistrome.org/api/datahub/43035&gftk=refGene,full)) 

2. The link loads a browser session as a remote data hub 

3. I find the remote track link ([sample](http://dc2.cistrome.org/genome_browser/bw/43035_treat.bw)) and try to load this as a remote track file on my own washu browser session. But the track does not load. 

Do you know why this doesn't work?

Thanks,
Tomás

**Comment by lidaof** [comment]
Hi @umasstr, can you paste the error log from your web browser from the console window? it should be working for any browser instance.

**Comment by umasstr** [comment]
Hi Daofeng,
It looks like chrome was silently blocking the upload (probably due to http), producing the "data fetch failed" error. I'm not sure why this was unique to my non-cistrome. 
Thanks!
