### ISSUE TITLE
Request to add calJac3 genome

### ISSUE THREAD

**Issue by MBrancoLab** [lidaof/eg-react#184]
Hi,

Any chance the marmoset's calJac3 assembly could be added to the browser?

Thanks

**Comment by lidaof** [comment]
Sure, I will work on it and let you know once finished. @MBrancoLab

**Comment by MBrancoLab** [comment]
Fantastic. Much appreciated.

**Comment by xzhuo** [comment]
Hi Daofeng, calJac3 is included in my latest pull request (along with the calJac3 -> hg19 alignment track). @MBrancoLab please let us know if you need other alignments.

**Comment by lidaof** [comment]
yeah, i just saw that, I will make the merge soon

**Comment by lidaof** [comment]
Please refresh the browser, the calJac3 is added. feel free to let me know any question @MBrancoLab

**Comment by MBrancoLab** [comment]
I see it. Many thanks for the swift action.
