### ISSUE TITLE
"Data fetch failed" when loading remote tracks

### ISSUE THREAD

**Issue by mireia-bioinfo** [lidaof/eg-react#188]
I am trying to load some custom longrange tracks from our webserver but I always get the "Data fetch error". However, when I load them locally it displays perfectly. An example track would be this one: [pasqualilab.upf.edu/gbrowser/PIRB_tracks_hg19/PC-HiC.PI.Interactions.visualization_only.txt.gz](pasqualilab.upf.edu/gbrowser/PIRB_tracks_hg19/PC-HiC.PI.Interactions.visualization_only.txt.gz).

We are using an Ubuntu server with apache and followed the instructions in the manual to enable CORS (https://eg.readthedocs.io/en/latest/tracks.html#configure-your-webserver-to-enable-cors).  Any idea on which might be the problem?

**Comment by lidaof** [comment]
Hi @mireia-bioinfo , if you load it fine with local file mode means the file format is correct. While I can also load your file using the url you provided..

![image](https://user-images.githubusercontent.com/102806/105194360-1fb44400-5aff-11eb-9ef3-69a6ccacb17f.png)

**Comment by mireia-bioinfo** [comment]
Great, I guess we managed to fix the problems on the server side! Thanks!
