### ISSUE TITLE
more track configurations, y-axis scale, summary method, logarithm, background color etc. 

### ISSUE THREAD

**Issue by lidaof** [lidaof/eg-react#19]

**Comment by lidaof** [comment]
summary method, logarithm still need to be implmented

**Comment by peterch405** [comment]
Could you also please add matplot from the previous version? http://wiki.wubrowse.org/Matplot

**Comment by lidaof** [comment]
Hi @peterch405 , thanks for mention that.
Yeap, it's on out to-do list. Will update this issue if there is any update.

**Comment by lidaof** [comment]
Hi @peterch405, sorry for late reply...the matplot track is available. Select >=2 numerical track, right click, you can see the `Apply matplot` button.

Almost all of this are implemented, close this one for now.
