### ISSUE TITLE
share tracks like UCSC genome broswer?

### ISSUE THREAD

**Issue by yancychy** [lidaof/eg-react#190]

**Comment by lidaof** [comment]
Hi, I guess you probably figured it out, you can check more from here: https://eg.readthedocs.io/en/latest/url.html. thanks.

**Comment by yancychy** [comment]
Thanks. I have shared it. But the resoltion is 5kb only. Hope it can be improved in furture.

**Comment by lidaof** [comment]
do you mean resolution? or region?
