### ISSUE TITLE
Finding the methylation sites of genes

### ISSUE THREAD

**Issue by Volkan51** [lidaof/eg-react#191]
Hello, 
I'm new to your site. I'm trying to use WASHU EPIGENOME BROWSER and learn shortcuts. But I haven't got the information I wanted yet. How can I find out about the CDHR3 gene I'm interested in, which nucleotides of the gene are methylated and is there a tissue-specific difference in this methylation? Thank you in advance for your help.

**Comment by lidaof** [comment]
Hi @Volkan51, this is a little bit complex question. You would need to collect the data you interested and put them into the browser, then you can located to the gene you interested, check the methylation signal, you can find out if the gene is methylated or not. For check tissue specific, you need find methylation data from different tissues then check again, if only one tissue show different pattern, you may tell there is a tissue specific methylation pattern for the gene.

[This paper](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-017-4115-6) published by our lab may give you some hints.

Hope this helps.

**Comment by Volkan51** [comment]
Hi @lidaof,
The article published by your lab was indeed instructive and helpful. I'll do some more research. 
Thank you for your help.

**Comment by lidaof** [comment]
Closing this one but feel free to open any new issue. Thank you!
