### ISSUE TITLE
Installation problems on RHEL 7.3

### ISSUE THREAD

**Issue by albertoriva** [lidaof/eg-react#198]
I'm trying to install the browser locally on a RHEL 7.3 server. When I run `npm install` I get the following error:

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

Which seems to indicate that fsevents is only available for Darwin. If I retry adding the `--force` option, I can get to the end of the command (of course, with warnings saying that fsevents is skipped), but then when I do `npm start` I get:

> epgg@53.1.0 start /usr/local/apps/eg-react/frontend
> react-app-rewired start

sh: react-app-rewired: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! epgg@53.1.0 start: `react-app-rewired start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the epgg@53.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-02T17_38_33_217Z-debug.log

Is there a way to fix this?

**Comment by lidaof** [comment]
Hi @albertoriva thanks for the interest in the browser.  I will try to find one RHEL server do this as well.
By the way, which node version are you using? just in case you were using an old version. version 12 above should be fine.

**Comment by lidaof** [comment]
Hi @albertoriva 
I found a RHEL server on our IT cloud server, i installed node v14 and tried compile the code without issue, could you please give it a try?

```bash
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.9 (Maipo)
# remove system nodejs (optional)
sudo yum remove nodejs
#install n for node version control
curl -L https://git.io/n-install | bash
source .bashrc
$ node -v
v14.17.0

# get the browser code go to frontend folder
git clone https://github.com/lidaof/eg-react.git
cd eg-react/frontend/
npm install --force
npm install react-app-rewired
npm start
```

**Comment by albertoriva** [comment]
Hi @lidaof and thanks for getting back to me so quickly. I'm using the latest version of node, just dowloaded, v14.17.0:

```
# node -v
v14.17.0
```

But I think I know what the problem is - this line:

```
npm install react-app-rewired
```

did not appear in your instructions. I ran it, and now I can run the start command. I'm getting the error you mentioned, but I'm going to run your fix and see what happens.

Thank you!

**Comment by lidaof** [comment]
yeah, sorry about that....`react-app-rewired` is listed in package.json somehow sometimes we need install it again.

We are working on refactor some part of the code for the grouping feature...hopefully we can get this feature to be added soon. Thanks!
