### ISSUE TITLE
Legacy Browser "Unknown genome name" - 20210623

### ISSUE THREAD

**Issue by LaureTomas** [lidaof/eg-react#200]
Hello

I've been using the Legacy Browser a lot for sharing session with my colleagues but suddenly we are unable to load any session because we get always the same message: "Unknown genome name" for any genome that I try to load. I tried changing the internet network, the internet browser and the computer and nothing works.

Do you know why this is happening?

Thanks in advance.

**Comment by lidaof** [comment]
Hi @LaureTomas there was some issue with the mysql service. I restarted it, should be back now. let me know if its' still not working?

**Comment by LaureTomas** [comment]
Perfect! everything works fine now.
Thank you! @lidaof
