### ISSUE TITLE
Load local data when embedding?

### ISSUE THREAD

**Issue by wangjk321** [lidaof/eg-react#201]
Hi, very nice tools.

I have used WasU browser for many years. Recently I tried to embed the WashU to my own web app (Django-based). I successfully follow your tutorial (https://eg.readthedocs.io/en/latest/installation.html#embedding). I can visualize remote data via the "url" option (i.e. ChIP-seq and Hi-C ).  

``` javascript
{
            "type": "bigWig",
            "name": "ChipSeq of Heart",
            "url": "https://www.encodeproject.org/files/ENCFF641FBI/@@download/ENCFF641FBI.bigWig",
            "options": { "color": "red" },
            "metadata": { "Sample": "Heart" }
        }
```

However, when I tried to load local files in my project,  I tried to use the absolue path (ie. http://127.0.0.1:8000/static/CTCF.bw):
- For ChIP-seq, the data is loaded without error, but the visualization panel just show blank.
- For Hi-C, data fecth failed. with error:

```
ERROR: range-byte header was ignored for url: /static/fileurl/MCF7.hic?someRandomSeed=0.p03zyq594pb
    at handleError (igv.js:39915)
    at XMLHttpRequest.xhr.onload (igv.js:39851)
```

Is there any option instead of "url" to load local files?

**Comment by lidaof** [comment]
Hi @wangjk321 i see you are actually loading files in URL...is it caused by CORS? have you enabled CORS in your Django app? (just a guess, not 100% sure)

**Comment by wangjk321** [comment]
Thanks for your quick reply!

I can use remote URL with enabled CORS on other server. I know that:

> Because of JavaScript's same-origin security policy, if data files do not reside on the same server must be configured to CORS.

But in my case, the embeded WashU browser and my data are on the same server. So I am wondering whether it is possible to load local file NOT via URL, which is faster for my web app. I tried `"url": "/static/CTCF.bw",` but failed. Anyway, if the embedding API does not support local file, that's fine. I just want to know whether it is possible...

**Comment by lidaof** [comment]
@wangjk321  I see, unfortunately that won't be possible based on my understanding. web app doesn't have access to user's local files unless user upload it/them through the File API.

**Comment by wangjk321** [comment]
Thank you anyway!! I'll use another server to hold my data.

**Comment by lidaof** [comment]
you are very welcome~ @wangjk321
