### ISSUE TITLE
Browser not loading

### ISSUE THREAD

**Issue by carlacohen** [lidaof/eg-react#204]
Hi there, sorry this is a bit of a stupid issue but I am totally stuck. I am a regular user of the WashU Epigenome browser but at the moment it won't load at all (https://epigenomegateway.wustl.edu/browser/). I have tried clearing cookies but that didn't help. Seems to be specific to this one PC. Any ideas? I really need to resolve this quickly as we are making figures for a paper! Many thanks, Carla

**Comment by lidaof** [comment]
Hi @carlacohen it works well with me on one iMac and Macbook pro. Do you have a screenshot? timing out of loading? or some other error? have you tried hard reload: https://eg.readthedocs.io/en/latest/faq.html#hard-reload ?

**Comment by carlacohen** [comment]
Hi @lidaof , thanks for the quick reply. I am using a Windows PC but I have been using for ages without any problems. 
It is literally just not loading at all so I don't seem to be able to do the hard reload.
![WashU_error](https://user-images.githubusercontent.com/76097605/127503221-1897ea7f-9c0a-42fb-9c52-dc818364967c.png)

**Comment by lidaof** [comment]
Hi @carlacohen looks like this is a connection problem..can you try our aws mirror: https://epigenomegateway.org/browser/ ?
thanks!

**Comment by carlacohen** [comment]
OK, the mirror is working for the main browser. But do you have one for the legacy browser? Unfortunately all my hubs are built on the legacy version. Also, do you have any idea why this is happening? Thanks

**Comment by lidaof** [comment]
Hi @carlacohen I am not sure, I guess a network issue in your side maybe? legacy version can be found at https://epgg-test.wustl.edu/browser/ and http://epigenomegateway.wustl.edu/legacy/. most of the legacy hubs can be viewed in new version without issue...maybe give it a try?

**Comment by carlacohen** [comment]
Thanks I’ll have a play tomorrow and see how it goes.
Carla

On 29 Jul 2021, at 20:20, Daofeng Li ***@***.***> wrote:

﻿

Hi @carlacohen<https://github.com/carlacohen> I am not sure, I guess a network issue in your side maybe? legacy version can be found at https://epgg-test.wustl.edu/browser/ and http://epigenomegateway.wustl.edu/legacy/. most of the legacy hubs can be viewed in new version without issue...maybe give it a try?

**Comment by carlacohen** [comment]
Hi Daofeng,
Just wanted to let you know that I have found the solution! I have updated my Intel graphics card and that has resolved the issue.
I thought I would let you know in case anyone else has the same problem.
Many thanks for all your help with this, and generally for making such a great freely available resource for us to visualise our data ☺
Best wishes,
Carla

**Comment by lidaof** [comment]
Hi @carlacohen , that's good to know. Thanks for the update!
