### ISSUE TITLE
Kept getting "you are currently office" which stop me use web tracks

### ISSUE THREAD

**Issue by shangl02** [lidaof/eg-react#213]
Hi there, I kept getting this message "You are currently offline, so tracks on web won't load. But you can still use the Local Track and Local Text Track functions."  

Tried both online version (http://epigenomegateway.wustl.edu/browser) and local mirror (http://localhost:3000), but neither work.  Thus url parameter doesn't work. Any suggestions？

![image](https://user-images.githubusercontent.com/80838660/136586539-b3f8f4d6-2f9e-4524-84d9-f3fc59628879.png)

**Comment by lidaof** [comment]
Hi @shangl02 not sure why this error. did you accidentally enable offline in network tab?

![image](https://user-images.githubusercontent.com/102806/136588571-2f89d248-cc85-41ef-8498-685acb81fd49.png)

**Comment by lidaof** [comment]
Hi @shangl02 yes, code is here: https://github.com/epgg/eg
the docs site right now is offline, I am asking the admin.

**Comment by lidaof** [comment]
Hi @shangl02 sorry for late reply, it should be `coordinate`
```
A variety of coordinate formats can be used to define view range:
single basepair: &coordinate=chr1:5932545
region: &coordinate=chr1:3333-44444
```

**Comment by shangl02** [comment]
@lidaof awesome! found that in browser/js/sukn.js
BTW, the wiki site is still inaccessible. Thanks a lot!
![image](https://user-images.githubusercontent.com/80838660/136806892-aa946886-aa5e-4201-9090-d47c5ca29456.png)

**Comment by shangl02** [comment]
Hi @lidaof, thanks for the help.

I still kept getting error for both react and legacy browser due to the network setting in my organization. Thus is trying to explore the local track and hub option. Does the local track and hub support url parameters to define genome, position and file location? I could not find relevant info in the doc site.

Thanks.

**Comment by shangl02** [comment]
Hi @lidaof, 

In using react browser, I get this error
![image](https://user-images.githubusercontent.com/80838660/137745157-bd5223a2-1bbc-4125-8108-4e2a7e27cf61.png)

While legacy browser doesn't pop "you are offline" error, but keep getting "timeout"
![image](https://user-images.githubusercontent.com/80838660/137747574-35cf7713-02f6-49e8-98c3-2f1ea0382f31.png)

**Comment by lidaof** [comment]
can you try this one instead https://enable-cors.org/server_iis7.html?
i think the json is ok, the browser complains CORS issue with bigwig file.

I don't have IIS environment...hard to test this :)

**Comment by lidaof** [comment]
Hi @shangl02 I don't have PC right now so cannot test this...sorry about that...

for your latest comment, it's because `track` is not recognized by the browser, it's been ignored and there is no error then.

**Comment by shangl02** [comment]
> Hi @shangl02 I don't have PC right now so cannot test this...sorry about that...
> 
> for your latest comment, it's because `track` is not recognized by the browser, it's been ignored and there is no error then.

oops. kept thinking "track" as an url parameter. Sorry :)

**Comment by lidaof** [comment]
@shangl02 you are welcome! Glad you solved it by switch to Apache!
