### ISSUE TITLE
Visualization questions

### ISSUE THREAD

**Issue by mozesjacobs** [lidaof/eg-react#216]
Hello,

I am a researcher working in William Noble's lab at the UW on a package called PASTIS (https://github.com/hiclib/pastis), which infers 3d chromatin structures from Hi-C matrices. I am currently running a matrix (https://data.4dnucleome.org/files-processed/4DNFI9YAVTI1/) through our program, and I have some intermediate results. Namely, I have the coordinates of the structure output by PASTIS. I wanted to visualize the structure, so I converted it to the .g3d format and loaded into the genome browser.

I had a couple questions:

1) How can I select just one chromosome, or a subset of chromosomes, to be viewed (and choose their colors)? I've played around with the settings on the browser, but I haven't figured this out.

2) Can I disable the lines in the structure so that only the spherical beads are shown? Referencing the lines on the left side of the image below. I would like it to just be a view like on the right side with the beads.
<img width="659" alt="Screen Shot 2021-10-20 at 7 27 13 PM" src="https://user-images.githubusercontent.com/58749087/138200634-1b58af7a-2655-4044-8d60-4109bd9ea2bf.png">

3) Any idea what this clump structure is that I'm seeing in the image below? It's hard to see if it's also there in matplotlib (since 3d visualization isn't as good there), so I can't really tell.

<img width="282" alt="Screen Shot 2021-10-20 at 7 15 39 PM" src="https://user-images.githubusercontent.com/58749087/138199542-214c2b09-8676-4a9b-b9a3-f2794f3b92b4.png">

I have attached a visualization in matplotlib as well, though due to the size of the structure it's not a very clear image.

<img width="437" alt="Screen Shot 2021-10-20 at 7 26 39 PM" src="https://user-images.githubusercontent.com/58749087/138200572-8d227117-7b7a-43a1-bdfe-234078832b4d.png">

Here is a link to the .g3d structure: https://drive.google.com/file/d/1waDp8uQiV4-7ii34l5UHBizvZVFYMLtR/view?usp=sharing

And here is a link to the corresponding structure output by PASTIS: https://drive.google.com/file/d/1CoLsggztXk0D7M0jWqw_yzqO0zSIyW21/view?usp=sharing

Thank you!
Mozes

**Comment by lidaof** [comment]
Hi Mozes @mozesjacobs , very nice to hear from you! Thanks for the interest!

I checked the g3d file, seems the chromosome name is not correct, the 3d module in the browser is linked to browser region, so the region in the browser will be used to highlight the 3d structure. and also the resolution is 20000, but start of each bin/row is not like separated by 20000*x
```
chrChr01        1       -0.0976270078546495     -0.43037873274483895    -0.20552675214328775    s
chrChr01        1       -0.5236984805493223     -0.5079094495430907     0.7987885945931865      s
chrChr01        2       -0.08976636599379373    0.15269040132219058     -0.29178822613331223    s
chrChr01        2       0.5758138740155656      0.8449078166270354      0.828311980773045       s
```


> 1. How can I select just one chromosome, or a subset of chromosomes, to be viewed (and choose their colors)? I've played around with the settings on the browser, but I haven't figured this out.

typically when you change the browser region to entire chromosome, you can see the regions in 3d you want, for subset of chromosomes, you can run a region set view and 3d structure will update as well. maybe  i can add options to allow customized highlighting. I will think about this.

> 2. Can I disable the lines in the structure so that only the spherical beads are shown? Referencing the lines on the left side of the image below. I would like it to just be a view like on the right side with the beads.
> 

will add that option, right now cannot do that.

> 3. Any idea what this clump structure is that I'm seeing in the image below? It's hard to see if it's also there in matplotlib (since 3d visualization isn't as good there), so I can't really tell.

the 3d display is very strange though...we are using [3dmol.js](https://github.com/3dmol/3Dmol.js/) to display 3d structures, we used the x, y, and z coordinates internally and fit into 3dmol.js for display...

previously we used to display some g3d data come from pastis output which looks better..
![image](https://user-images.githubusercontent.com/102806/138205958-232bd331-4a5f-4bce-8849-f4b3dc7f4086.png)

I will play with your pastis output file see if we can figure something out.

**Comment by lidaof** [comment]
Hi @mozesjacobs, yes, I worked on it the other day...somehow forgot to reply...sorry about that.

like I mentioned I see duplicated lines in the file, so what I did is that I separated the lines based on the 2nd column of the .g3d file you provided, that I generated 2 .g3d file...after load them to the browser, i can see the structure from the core part, while there are many outlines....need to figure out a way to remove them..

here is the view I got with the 2 files I generated, also attaching the files.

![image](https://user-images.githubusercontent.com/102806/140788226-858702e0-8669-44ca-ac6d-003a50aa71ea.png)

[a.txt](https://github.com/lidaof/eg-react/files/7498830/a.txt)
[b.txt](https://github.com/lidaof/eg-react/files/7498831/b.txt)

command to generate the g3d file `g3dtools load a.txt -o aa`

**Comment by mozesjacobs** [comment]
Awesome, I'll take a look at them. Thank you!

**Comment by mozesjacobs** [comment]
Does this browser support viewing of diploid structures?

**Comment by lidaof** [comment]
Hi @mozesjacobs in the last column you can specify different haplotypes or categories,  the 3d viewer will display them as separated 3d models, and they can be toggled for display or hide.

**Comment by mozesjacobs** [comment]
Ok, thanks

**Comment by lidaof** [comment]
Hi @mozesjacobs i am closing this one, but feel free to open any new issue :) Thank you!
