### ISSUE TITLE
Data fetch failed...using original server

### ISSUE THREAD

**Issue by storytc** [lidaof/eg-react#218]
Hi,
I tried to upload a `methylc` file from local tracks using original server: http://epigenomegateway.wustl.edu/browser/
but it gave me "data fetch fialed" error message.
I have tried another dataset in the same format(methylc), and it worked.
But I processed the two datasets in parallel...and I double checked the two datasets.
Thanks and hope for your advice!

Best,
Arial.

**Comment by storytc** [comment]
I figured it out!
Just using a little number transform trick....
Thanks!
Best,
Arial.

**Comment by lidaof** [comment]
Glad you figured it out!
