### ISSUE TITLE
showOnHubLoad = False

### ISSUE THREAD

**Issue by joreynajr** [lidaof/eg-react#219]
Hi, Is it possible to use **"showOnHubLoad": false**? I have a lot of data within a datahub which I want listed in my JSON but not preloaded into the browser. I have tried using **"showOnHubLoad": false** so far but it hasn't worked. 

Thanks!

**Comment by lidaof** [comment]
Hi @joreynajr by default the `showOnHubLoad ` property is false, if you didn't specify it the tracks won't be loaded...but what you are doing should be right, mind send me directly your hub for testing?

**Comment by lidaof** [comment]
Closing this for now. Feel free to open any new issue.
Thank you!
