### ISSUE TITLE
Request to add xenTro10 genome.

### ISSUE THREAD

**Issue by hzjsxu** [lidaof/eg-react#220]
Hello, Can you add the Xenopus Tropicalis's xenTro10 assembly to the Washu browser?

**Comment by lidaof** [comment]
Hi @hzjsxu sure thing, I will add it in the next few days.

**Comment by hzjsxu** [comment]
OK! Much appreciated.

**Comment by lidaof** [comment]
Hi @hzjsxu the `xenTro10` genome is added. please refresh the browser to check it. Feel free to let me know any question. Thanks.

**Comment by hzjsxu** [comment]
Hi @lidaof , I have tried to add xenTro10 genomes myself using docker images, but I don't know how to import the gene track file and it always gives this error? How can I solve it?

![image](https://user-images.githubusercontent.com/45815139/144174098-103c1f6f-379a-434e-8eec-0eaaf9db7089.png)


Or can you also update docker images if convenient?

**Comment by lidaof** [comment]
can you open the browser console so I can check the error message?  in you docker container you can do a `git pull` to fetch the latest code then it should work.

I will do the docker update sometime next week and will let you know.

**Comment by hzjsxu** [comment]
Ok，it works well after using git pull to get the latest code. Thanks very much!

**Comment by lidaof** [comment]
great! good to know. I am closing this one. Feel free to open a new issue if you have other question.
