### ISSUE TITLE
Height of Hi-C tracks?

### ISSUE THREAD

**Issue by gitgitmonkey** [lidaof/eg-react#221]
How can I decrease the height of Hi-C arcs in the new browser to a height similar to the legacy browser? In the new browser, the Hi-C tracks are too high, they take up almost the whole screen in a laptop.
I know I can decrease the track height, but then the arcs are cut off. In the legacy browser, the arcs are re-scaled to fit the track height.
Thank you!

**Comment by lidaof** [comment]
Hi @gitgitmonkey that's right, I will add that option and update you. Thank you!

**Comment by lidaof** [comment]
Hi @gitgitmonkey, sorry for the delay, I was struggled a while with the geometry :) The old browser show heatmap style adjusted with track height. I have tried to implement in both heatmap and arc, with the new option in the screenshot below..I have tested seems it's working, feel free to let me know if there is any issue you may find. Thank a lot.

![image](https://user-images.githubusercontent.com/102806/146627873-d8794c0d-b899-4b1e-8ae5-75052543ba8f.png)

**Comment by gitgitmonkey** [comment]
I apologize for the super late reply! I went out on vacation and missed Github's email with your reply.
I don't see this option "Scale with height" at http://epigenomegateway.wustl.edu/browser/ 
Will it only be available for local installations of the browser?
Thank you.

**Comment by lidaof** [comment]
no worries @gitgitmonkey . possible your computer cached old files, can you try hard reload please https://eg.readthedocs.io/en/latest/faq.html#hard-reload? let me know if problem still there. Thank you!

**Comment by gitgitmonkey** [comment]
I did a hard reload and still can't see the option. I am loading a longinteract file.

**Comment by lidaof** [comment]
@gitgitmonkey you are right, sorry! my bad. I applied to long range tracks now. should be able to see it after refresh.

**Comment by gitgitmonkey** [comment]
Thanks, I can see it now and it works!
Is the .json option to scale "clampHeight":true? I am setting it in a .json session file loaded remotely but I can't make it scale with height and only show interactions that have both ends in the window ("bothAnchorsInView":true).

**Comment by lidaof** [comment]
yes, you are right, you can use `clampHeight` in the options and set it to true. would you mind share your json file?  you can send it to me directly and I can test for you...as I tested my side it works with this example hub (partially copied):

```json
{
        "name": "Broad/MIT/UMass K562 Hi-C (100kb pearson correlation)",
        "type": "longrange",
        "label": "Broad/MIT/UMass K562 Hi-C (100kb pearson correlation)",
        "options":
        {
            "height": 500,
            "label": "Broad/MIT/UMass K562 Hi-C (100kb pearson correlation)",
            "bothAnchorsInView": true,
            "clampHeight": true,
            "fetchViewWindowOnly": true
        },
        "url": "https://egg.wustl.edu/d/hg19/K562_pearson_100kb.gz"
}

```

**Comment by gitgitmonkey** [comment]
I forgot to put these options inside "options":, it's working now!
Thanks a lot!
