### ISSUE TITLE
Add new species

### ISSUE THREAD

**Issue by zhanglp996** [lidaof/eg-react#228]
Hello!
    The browser is very good but there are no species that I research .Can you add the Brassica rapa genome to WashU epigenome browser ?And I can  provide the genome file to you.
Thank you very much!

**Comment by lidaof** [comment]
Hi @zhanglp996 yes, please provide the genome files. thanks.

**Comment by zhanglp996** [comment]
> Hi @zhanglp996 yes, please provide the genome files. thanks.

Hello,you can download Brapa_genome_v3.0 from the website http://39.100.233.196:82/download_genome/Brassica_Genome_data/Brara_Chiifu_V3.0/Brapa_sequence_v3.0.fasta.gz
and Brapa v3.0 annotation file from the website
http://39.100.233.196:82/download_genome/Brassica_Genome_data/Brara_Chiifu_V3.0/Brapa_genome_v3.0_genes.gff3.gz
If you meet problem in downloading files ,please provide a email address and I will send the files to you .
Thank you very much!

**Comment by lidaof** [comment]
Hi @zhanglp996 i was able to download both files and will work on it. Will let you know once it's added to the browser. thanks.

**Comment by zhanglp996** [comment]
Thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nelle ***@***.***&gt;; 
发送时间: 2022年1月6日(星期四) 上午10:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lidaof/eg-react] Add new species (Issue #228)





 
Hi @zhanglp996 i was able to download both files and will work on it. Will let you know once it's added to the browser. thanks.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lidaof** [comment]
Hi @zhanglp996 the brapa genome is added to the browser, please let me know if you have any question. Thank you!

**Comment by zhanglp996** [comment]
> Hi @zhanglp996 the brapa genome is added to the browser, please let me know if you have any question. Thank you!

No problem,
Thank you very much!
