### ISSUE TITLE
Data fetch failed from Dropbox

### ISSUE THREAD

**Issue by umasstr** [lidaof/eg-react#235]
I have been loading remote tracks from dropbox for two years, but suddenly these tracks no longer load. I don't think that this is an issue with the washu browser because tracks from other remote sources (cistrome e.g.) work fine. I would really appreciate if anyone has any information as to why links such as [this one](https://dl.dropboxusercontent.com/s/86gvkex6s9e984m/cCRE-PLS.bb) no longer fetch.

Interestingly, I can still load config files as part of the browser address using dropbox (i.e. http://epigenomegateway.wustl.edu/browser/?genome=mm10&hub=<my DB link>

Thanks for the help!

**Comment by lidaof** [comment]
Hi @umasstr are you using the current browser or legacy version?
i tried your bb file with current browser it can be loaded.

**Comment by umasstr** [comment]
Hi @lidaof, thank you very much for your quick reply. Is v53.5.2 the latest version? If so, then adding the bigbed as a remote track failed in my hands. If I download the track and load locally, I have no issues. 

![image](https://user-images.githubusercontent.com/44478133/152991666-6b497f57-66de-40c6-9aa1-512f51f1f2b8.png)

**Comment by lidaof** [comment]
Hi @umasstr yes, you are using the latest version. weird I was able to load your bigbed file from your dropbox url.

![image](https://user-images.githubusercontent.com/102806/153018287-3154a034-59d8-4179-b269-9790063961d2.png)

**Comment by lidaof** [comment]
can you open the chrome console tab to see if there is any error message?

**Comment by umasstr** [comment]
Thanks for the tip. Any idea how to bypass CORS security or why this only happened recently?

![image](https://user-images.githubusercontent.com/44478133/153029488-9a030e32-1df8-4bdf-b938-799c10ed6fc2.png)

I get the same error on other web browsers and still find it odd that washu has no problem fetching the json via dropbox.

**Comment by lidaof** [comment]
I was thinking maybe you are access the http site of the browser might cause this issue...but it works on my side even on http site....not sure why...my chrome console tab has no such error message and we are accessing same file url...so strange...

![image](https://user-images.githubusercontent.com/102806/153031521-e3d9ecb8-9ba2-4fe9-bad3-fa0ffe56400d.png)

**Comment by umasstr** [comment]
Thank you for testing the file out yourself. I have no idea what's going on because I attempted this on multiple networks and computers. BUT, given your input, I tried to browse my remote files on my phone and tablet...both worked! This is very strange, indeed.

I suspect this is isolated to my machines and not affect my collaborators. As always, thanks for supporting this wonderful tool.

**Comment by lidaof** [comment]
you are very welcome @umasstr .
