### ISSUE TITLE
Setting position

### ISSUE THREAD

**Issue by gitgitmonkey** [lidaof/eg-react#245]
Hi, I created a remote .json session that I can display by passing the session file in the browser URL.
However, I can't set the initial view/position.

http://epigenomegateway.wustl.edu/browser/?genome=hg19&sessionFile=https://removehost/session.json&position=chr1:123-456
doesn't work, it doesn't show the session tracks. &position=chr1:123-456 alone works.

I don't see how to set the initial view in the session file, since it seems there's no way to specify the chromosome in
"viewInterval":{"start":1260710424,"end":1261030792},

I also tried removing viewInterval, thinking it's overriding &position=chr1:123-456 but then no tracks are displayed.

How can I use a remote .json session file and specify the initial position?
Thanks.

**Comment by xzhuo** [comment]
have you tried using the datahub json file instead of the session file? like:
`http://epigenomegateway.wustl.edu/browser/?genome=hg19&hub=https://remotehost/hub.json&position=chr1:123-456`

**Comment by lidaof** [comment]
Hi @gitgitmonkey as @xzhuo mentioned, `position` URL parameter can work with `hub`, the viewInterval in sessionFile will be used but if it's absent the default region for the genome in sessionFile will be used...I guess we need make some logic changes in the code to make position also work with sessionFile, I will take a look.
Thanks.

**Comment by gitgitmonkey** [comment]
Thanks for the quick reply!
I tried using hub= instead of sessionFile= and then the tracks won't load.
My track file is very paired down, with only one track.

**Comment by lidaof** [comment]
Hi @gitgitmonkey np! 

for your initial question, a quick solution is that you can load your session, navigate to the region you want, and download a new sessionFile to use in URL.

regarding the hub URL parameter link, the sessionFile and datahub file have different syntax, sessionFile contains more information than data hub file, for your case, you need copy the tracks array out from the sessionFile to a different file. for example, from this [sessionFile](https://wangftp.wustl.edu/~dli/test/eg-session--1692c5f0-c392-11e9-829c-912864922e1e.json), you can copy:
```json
[
{
"name": "refGene",
"type": "geneannotation",
"label": "refGene",
"options": {
"label": "refGene"
},
"url": "",
"metadata": {
"Track type": "geneannotation"
},
"isSelected": false,
"fileObj": "",
"files": [],
"tracks": [],
"genome": "mm10"
},
{
"name": "gencodeM19Basic",
"type": "geneannotation",
"label": "gencodeM19Basic",
"options": {
"label": "gencodeM19Basic"
},
"url": "",
"metadata": {
"Track type": "geneannotation"
},
"isSelected": false,
"fileObj": "",
"files": [],
"tracks": [],
"genome": "mm10"
},
{
"name": "Ruler",
"type": "ruler",
"label": "Ruler",
"options": {
"label": "Ruler"
},
"url": "",
"metadata": {
"Track type": "ruler"
},
"isSelected": false,
"fileObj": "",
"files": [],
"tracks": []
},
{
"name": "RepeatMasker",
"type": "repeatmasker",
"label": "RepeatMasker",
"options": {
"label": "RepeatMasker"
},
"url": "https://vizhub.wustl.edu/public/mm10/rmsk16.bb",
"metadata": {
"Track type": "repeatmasker"
},
"isSelected": false,
"fileObj": "",
"files": [],
"tracks": []
},
{
"name": "MeDIP",
"type": "bigwig",
"label": "MeDIP",
"options": {
"label": "MeDIP",
"color": "#d11c6e"
},
"url": "https://wangftp.wustl.edu/~dli/test/TW463_20-5-bonemarrow_MeDIP.bigWig",
"metadata": {
"sample": "bone",
"assay": "MeDIP",
"Track type": "bigwig"
},
"isSelected": false,
"showOnHubLoad": true,
"fileObj": "",
"files": [],
"tracks": [],
"datahub": "Custom hub"
},
{
"name": "MRE",
"type": "bigwig",
"label": "MRE",
"options": {
"label": "MRE"
},
"url": "https://wangftp.wustl.edu/~dli/test/TW551_20-5-bonemarrow_MRE.CpG.bigWig",
"metadata": {
"sample": "bone",
"assay": "MRE",
"Track type": "bigwig"
},
"isSelected": false,
"fileObj": "",
"files": [],
"tracks": [],
"datahub": "Custom hub"
}
]
```
and save it to a different file like hub.json then use `?genome=mm10&hub=http://xxx/hub.json&position=chr1:123-456`, you will need `genome`  in parameter with hub URL.

**Comment by lidaof** [comment]
I will also update the logic in the code, so after next update the position will work with sessionFile (hopefully Friday sometime, will update in this issue).

**Comment by gitgitmonkey** [comment]
Thanks!
The problem was the lack of "showOnHubLoad": true, in my hub.
I was following this example https://epigenomegateway.readthedocs.io/en/latest/datahub.html
and there is no mention to "showOnHubLoad": true.
&position= in the URL now works.

**Comment by lidaof** [comment]
Good catch, I think we need put showOnHubLoad top in the docs..
https://epigenomegateway.readthedocs.io/en/latest/datahub.html#showonhubload

**Comment by lidaof** [comment]
Thanks for bring this issue to our attention @gitgitmonkey !
Related code has been updated, will push to public site next time (Friday sometime)
Closing this for now. Feel free to open any new issue.
