### ISSUE TITLE
Password protected files (Apache/digest or basic)?

### ISSUE THREAD

**Issue by gitgitmonkey** [lidaof/eg-react#247]
I have a hub that works fine with remote files in my server that are not password protected.
When I tried to add files using this syntax: https://user:password@host.edu/file.bw, the tracks don't show.
This syntax works fine in the UCSC genome browser. I'm running an Apache server with both digest and basic authentication, so I can use either.
How can I use remote files that aren't public?
Thank you!

**Comment by lidaof** [comment]
Hi @gitgitmonkey would you please email me a link for me to troubleshoot? Getting this fixed should be a pretty helpful feature.

**Comment by gitgitmonkey** [comment]
I ended up finding a workaround. I symlinked the files to an open directory and renamed them with random characters. So the files themselves are anonymous and likely useless to other people. The hub .json is password protected and it's the only place where the files are identified.

**Comment by lidaof** [comment]
That's pretty smart!

**Comment by lidaof** [comment]
close for now, feel free to open new issue. thank you!
