### ISSUE TITLE
embedding browser to any webpage

### ISSUE THREAD

**Issue by lidaof** [lidaof/eg-react#25]

**Comment by hitz** [comment]
+1

**Comment by lidaof** [comment]
Hi Ben @hitz,

Currently we have make the embedding function to work with regular html,
see example here http://target.wustl.edu/dli/eg/embed.html I am embedding 2 bigWig tracks from ENCODE data portal:

![image](https://user-images.githubusercontent.com/102806/48157247-c0a6e380-e294-11e8-8089-3dd4ace8617f.png)

You can right click the page to see page source, core parts are:

```  <h1>Embedding test</h1>
  <div id="embed"></div>
  <h2>some other headings</h2>

  <script>
    const container = document.getElementById('embed');
    const contents = { 
        "genomeName": "mm10", 
        displayRegion: "chr5:51997494-52853744",
        "trackLegendWidth": 120, 
        "isShowingNavigator": true,
        "tracks": [
          { 
            "type": "bigWig", 
            "name": "ChipSeq of Heart", 
            "url": "https://www.encodeproject.org/files/ENCFF641FBI/@@download/ENCFF641FBI.bigWig", 
            "options": { "color": "red" }, 
            "metadata": { "Sample": "Heart" }
          },
          { 
            "type": "bigWig", 
            "name": "ChipSeq of Liver", 
            "url": "https://www.encodeproject.org/files/ENCFF555LBI/@@download/ENCFF555LBI.bigWig", 
            "options": { "color": "blue" }, 
            "metadata": { "Sample": "Liver" }
          }
        ], 
        "metadataTerms": ["Sample"], 
        "regionSets": [], 
        "regionSetViewIndex": -1, 
      };
      renderBrowserInElement(contents, container);
  </script>```

**Comment by lidaof** [comment]
ongoing effect is being made for making the package as a React component, will update.

**Comment by Parul-Kudtarkar** [comment]
@lidaof any updates coming soon on this feature? 
Thanks! Parul

**Comment by lidaof** [comment]
Hi @Parul-Kudtarkar , right now the embedding can be done in one webpage. Making the entire browser as one React component is still under development. Sorry for that, if there is any update, will update you and on this thread.
