### ISSUE TITLE
Genome comparison shifts on screenshot

### ISSUE THREAD

**Issue by MBrancoLab** [lidaof/eg-react#252]
Hi,
I'm loving the genome comparison annotation, but I encountered an issue. When I use the screenshot app, the tracks from the query species get shifted and resized. As an example, this is what I see on the browser:
<img width="1758" alt="Browser_view" src="https://user-images.githubusercontent.com/33059644/159456151-71c319ec-f3af-4aab-917e-d77c97d64b69.png">

And this is how it gets displayed on the screenshot:
<img width="1765" alt="Screenshot" src="https://user-images.githubusercontent.com/33059644/159456119-e799565e-0724-44a1-be13-6864c1060af9.png">

A fix would be much appreciated.
BW,
Miguel

**Comment by lidaof** [comment]
Hi @MBrancoLab this issue should be fixed by ff84c3e, feel free to let me know any questions. Thanks for catching this!

**Comment by MBrancoLab** [comment]
Fantastic! Thank you for the speedy fix.

**Comment by lidaof** [comment]
You are welcome, close this one now. Feel free to open any new issue. Thanks!
