### ISSUE TITLE
No bundle Id for uploaded session or remote session?

### ISSUE THREAD

**Issue by gitgitmonkey** [lidaof/eg-react#258]
When I use sessionFile= or upload a session file, there is no bundle Id, so I can't save and share the session.
I want to be able to provide a link or session file to collaborators, and let them modify and save their sessions and share them so we can collaborate.
Is there any way I can do this or I have to manually create tracks for tens of files to be able to share a bundle Id?
Thanks.

**Comment by lidaof** [comment]
Hi @gitgitmonkey if I understand you correct, you need click the Save session button. For example, I use this link https://epigenomegateway.wustl.edu/browser/?genome=hg19&hub=https://wangftp.wustl.edu/~dli/test/a.json, I can open the Apps->Session, Save the session, then I load the same hub link with session id: 6e9b8d50-b218-11ec-ba7e-119adc64fb6b

**Comment by gitgitmonkey** [comment]
Apparently, it was a temporary bug. When I uploaded a session file, there was no bundle ID like, for example, e4c1d0a0-b43b-11ec-865d-c70d00ba148e.

I get a lot of inconsistent behavior in this new browser. For example, I have a hub file that doesn't always load in Brave browser, but loads fine in Firefox. Then remote Hi-C tracks load and bigwig tracks don't (I can download the files, the server is working fine). Right now the tracks load fine if I use a bundle ID but don't load if I use the hub json file using the same browser.

**Comment by lidaof** [comment]
Hi @gitgitmonkey, I will look into it. FYI, a session bundle id is generated each time when you visit the browser, but it won't save the session to our Firebase database unless you click the Save session button in the Apps menu.

**Comment by gitgitmonkey** [comment]
Yes, I understand. I just couldn't see any bundle ID at that time, not sure why. Now I see it when I load my hub or upload a session.
Thanks!

**Comment by lidaof** [comment]
That's great to know! thanks @gitgitmonkey

**Comment by gitgitmonkey** [comment]
I'm having the same problem again: no session bundle ID. I loaded a remote sessionFile and I get no bundle ID. I've tried different browsers and new tabs:
https://imgur.com/a/6EwMRYF

This doesn't happen when I start the browser without a remote sessionFile.

**Comment by lidaof** [comment]
Hi @gitgitmonkey, thank you so much for reporting this problem. Can I ask you how to reproduce this in more detail?
I downloaded a session file and reuploaded it and I can see the session id there. In the session file you downloaded, do you see the bundle id like in the screenshot below:

<img width="451" alt="image" src="https://user-images.githubusercontent.com/102806/163850804-012fb4be-7f74-405f-8a32-a1323b9a92a6.png">

**Comment by gitgitmonkey** [comment]
I did not download a session file, I created one manually and without a bundleId. I thought bundleIds were created by the browser on the fly.
I added that section to my session file and now it shows the bundle Id that I specify.
Thanks!

**Comment by lidaof** [comment]
Hi, @gitgitmonkey that explained it! Thank you!
I guess we need to add the logic that if the bundle id is empty then we should generate one randomly.

**Comment by lidaof** [comment]
close for now, feel free to open new issue. thank you!
