### ISSUE TITLE
Add a new genome to the API

### ISSUE THREAD

**Issue by Boer223** [lidaof/eg-react#260]
Hi, 
Can you help me to add my genome and gene annotation to your public api, and I want to use it to build the epigenome browser for my genome.

Here is my 2bit format genome and gene annotation files:
genome: http://205.185.113.78/public/epigenome_browser/Westar/Westar.2bit
gene annotation: http://205.185.113.78/public/epigenome_browser/Westar/Westar.gene.mRNA.bed

Thank you!

**Comment by lidaof** [comment]
HI, @Boer223 sure we can do that. should I use `westart` as your genome name? do you have more information about this genome assembly?

**Comment by Boer223** [comment]
@lidaof Yes, it's a cultivar of Brassica napus, but now the genome hasn't been published. I only want to use the API to build my own epigenome browser.

**Comment by lidaof** [comment]
Hi @Boer223 i understand now, so you only want us add the gene data to our API? we can do that. would you please format your data (`Westar.gene.mRNA.bed`) to our [refbed format](https://eg.readthedocs.io/en/latest/tracks.html#refbed) ?

**Comment by Boer223** [comment]
@lidaof Yes, and is there any scripts to format the bed or gff3 format to refbed format?

my gff3 format:
```
##gff-version 3
chrA01	maker	gene	107668	109795	.	-	.	ID=westarA010000010;Name=westarA010000010
chrA01	maker	mRNA	107668	109795	.	-	.	ID=westarA010000010-mRNA-1;Parent=westarA010000010;Name=westarA010000010
chrA01	maker	exon	109777	109795	.	-	.	ID=westarA010000010-mRNA-1.exon1;Parent=westarA010000010-mRNA-1
chrA01	maker	CDS	109777	109795	.	-	0	ID=cds.westarA010000010-mRNA-1;Parent=westarA010000010-mRNA-1
chrA01	maker	exon	109348	109595	.	-	.	ID=westarA010000010-mRNA-1.exon2;Parent=westarA010000010-mRNA-1
chrA01	maker	CDS	109348	109595	.	-	2	ID=cds.westarA010000010-mRNA-1;Parent=westarA010000010-mRNA-1
chrA01	maker	exon	108347	108410	.	-	.	ID=westarA010000010-mRNA-1.exon3;Parent=westarA010000010-mRNA-1
chrA01	maker	CDS	108347	108410	.	-	0	ID=cds.westarA010000010-mRNA-1;Parent=westarA010000010-mRNA-1
chrA01	maker	exon	107668	107696	.	-	.	ID=westarA010000010-mRNA-1.exon4;Parent=westarA010000010-mRNA-1
```
my bed format
```
Uncluster	817348	819562	westarUncluster0000010	0	-
Uncluster	843209	852717	westarUncluster0000020	0	-
Uncluster	1613348	1615395	westarUncluster0000030	0	-
```

**Comment by lidaof** [comment]
Hi @Boer223 , yes, we have some scripts [here](https://github.com/lidaof/eg-react/tree/master/backend/scripts), i guess you can check those with gff in the name. let me know if you need any help.

**Comment by Boer223** [comment]
Thank you for your scripts! I have converted the gene annotation to refbed format successfully, and it's now here:
http://205.185.113.78/public/epigenome_browser/Westar/Westar.gene.refbed

**Comment by lidaof** [comment]
Hi Xiaobo @Boer223 , the data has been added to our API, you can use [this link](https://lambda.epigenomegateway.org/v2/westar/genes/gene/queryRegion?chr=chrA01&start=119169&end=196860) for a quick testing. when you add the track to your genome, you can add this as the gene track model:
```js
new TrackModel({
        type: "geneAnnotation",
        name: "gene",
        genome: "westar",
    }),
```

**Comment by Boer223** [comment]
@lidaof Many thanks for your API. I have built the epigenome browser for my genome successfully. 

<img width="1923" alt="image" src="https://user-images.githubusercontent.com/19387444/163670463-cee60e11-5f9f-4bf5-a2d9-f92b7a44dd5f.png">

**Comment by lidaof** [comment]
@Boer223 you are very welcome, and it looks very nice!
