### ISSUE TITLE
Tracks not loading from hub

### ISSUE THREAD

**Issue by albertoriva** [lidaof/eg-react#262]
Hello,

I am trying to load three tracks from a hub with the following definition:

[
    {
        "type": 'bigbed',
        "name": 'CEM-W-C_peaks',
        "height": 50,
        "group": 2,
        "colorpositive": "#000000",
        "colornegative": "#000000",
        "horizontalLines": [{"value": 0, "color": "#000000"}],
        "mode": "thin",
        "url": "https://bw:bw@lichtlab.cancer.ufl.edu/reports/NSD2/NS1813-dasa//NS1813/CEM-W-C/CEM-W-C.bbed"
    },
    {
        "type": "hammock",
        "mode": "barplot",
        "name": "CEM-W-C_ham",
        "url": "https://bw:bw@lichtlab.cancer.ufl.edu/reports/NSD2/NS1813-dasa//NS1813/CEM-W-C/CEM-W-C.bed.gz"
    },
    {
        "type": "bigwig",
        "name": "CEM-W-C",
        "height": 50,
        "group": 1,
        "colorpositive": "#000000",
        "colornegative": "#000000",
        "horizontalLines": [],
        "mode": "show",
        "url": "https://bw:bw@lichtlab.cancer.ufl.edu/reports/NSD2/NS1813-dasa//NS1813/CEM-W-C/CEM-W-C.bw"
    },
]

I've verified ll three track files are correctly accessible. When I load it, the bigbed track loads but says that it doesn't contain any data. The hammock track gives an error ("missing track for reordering") and only the bigwig track displays correctly.

If I look in the server logs, the browser only sends a request for the bigwig file, and doesn't send any request for the other two files.

What is going on? 

Thank you!

**Comment by lidaof** [comment]
Hi @albertoriva i think this syntax and password protected URL works for the legacy browser, just want to confirm you are using the legacy browser? i am testing it.

**Comment by lidaof** [comment]
apache log says:

```
[Sun Apr 24 21:50:03.073040 2022] [cgi:error] [pid 5751] [client 128.252.217.134:35637] AH01215: tabix file error: https://bw:bw@lichtlab.cancer.ufl.edu/reports/NSD2/NS1813-dasa//NS1813/CEM-W-C/CEM-W-C.bed.gz: /usr/lib/cgi-bin/subtleKnife
```
sorry, I haven't review the legacy code for a long time, still troubleshooting..

**Comment by albertoriva** [comment]
Yes, sorry - it's the legacy browser.

Thanks,

Alberto
