### ISSUE TITLE
Track number limit?

### ISSUE THREAD

**Issue by umasstr** [lidaof/eg-react#263]
Hi @lidaof ,

I didn't notice any comments in the documentation, but is there a limit to the number of tracks that can be displayed? Some observations on my end from a hub with 60 tracks:

1. Individually, all of the tracks load without issue on the latest browser and the old containerized browser (52.1.0). 
2. Tracks will, at random, fail to load in local container and on the web browser.  (see screenshots below)
3. Fewer tracks load successfully on web vs. local browser. 
4. Perhaps unsurprisingly, the web browser gives an HTTP 429 error. I don't know how I would fix this.
5. The local container gives an "Uncaught RangeError: byte length of Int32Array should be a multiple of 4". I have no idea what this is referring to.

Have you been able to load >20 or so tracks? Thanks for the advice! 

![image](https://user-images.githubusercontent.com/44478133/165613661-13b76248-d355-4c0d-8b20-6002f8aed4f2.png)

![image](https://user-images.githubusercontent.com/44478133/165615281-bea08a84-c834-488e-bfeb-b7f707e30407.png)

**Comment by lidaof** [comment]
HI @umasstr 4 and 5 is a little bit strange i never saw them before. possible to share a session id for me to take a look?
do you have any limitation on number of concurrent requests in your web server?

We do see screenshots with >40 tracks loaded.

**Comment by umasstr** [comment]
Thanks, @lidaof  for the help troubleshooting. It seems that your intuition was correct. I can load no more than 40 tracks at once due to server caps. 

For others facing difficulties loading several tracks, I recommend using Google Chrome and checking the console (F12) for the below errors. In my case, these errors arise from too many requests coming in at the same time. 

> HTTP 429
> Uncaught RangeError: byte length of Int32Array...

**Comment by lidaof** [comment]
this is very helpful! Thank you for sharing this @umasstr!
