### ISSUE TITLE
bigwig help

### ISSUE THREAD

**Issue by mozesjacobs** [lidaof/eg-react#265]
Hello,

I am trying to use a bigWig track to color certain beads in the structure as LADs and certain ones as not LADs. I am able to successfully upload both the bigWig file and my structure (and I am able to visualize the structure itself) using the local track feature. However, whenever I try to pain the structure using the bigWig track in the numerical painting option, I keep getting the error "bigwig url for paint is empty, abort... X". 

In addition, it seems I can't adjust the resolution from 20000, but my structures use a resolution of 1 mb.

I have uploaded the structure and the bigwig to drive, if that helps.
structure: https://drive.google.com/file/d/1UflCvfk6T90folRWO2SNxJH3--SUeR1f/view?usp=sharing
bigWig: https://drive.google.com/file/d/1b-cRbpRZ1aPTWQLmRZ_YkjRFA8uJUexH/view?usp=sharing

Thank you very much!

**Comment by lidaof** [comment]
Hi @mozesjacobs the bigwig track is a little bit tricky it works with remote tracks when selecting `loaded tracks`, passing a file Blob from browser to 3D viewer might causing performance issue..so I didn't add that option..i guess maybe i can allow upload of bigwig to 3d viewer as well.
so far, I put your bigwig file under https://target.wustl.edu/dli/tmp/mozesjacobs/ and you can use the URL to paint with 3d, feel free to send me more bw files and i will put them there.

for resolutions, you file only contains the default 200k resolution, you would need to adjust the default parameters when generating g3d file.

```
$ g3dtools meta struct_inferred.000.g3d 
{
    "version": 2,
    "genome": "unknow_genome",
    "name": "unknow_name",
    "resolutions": [
        20000
    ]
}

```

**Comment by mozesjacobs** [comment]
Ohh gotcha! Great, thank you!

**Comment by mozesjacobs** [comment]
I'm only able to paint the main picture, but not the thumbnail. Is it possible to paint the thumbnail too?

**Comment by lidaof** [comment]
right now only main structure can be painted, more coding needed for the feature you mentioned. I will add it to my todo list :)

**Comment by mozesjacobs** [comment]
Okay, thank you!

**Comment by mozesjacobs** [comment]
Hi again! Could you upload this bigWig file to the browser for me? https://noble.gs.washington.edu/proj/pastis-protocol/lad_notlad.bw

Thank you!!

**Comment by lidaof** [comment]
@mozesjacobs sure thing, done

**Comment by mozesjacobs** [comment]
Thank you!!!!

**Comment by lidaof** [comment]
close for now, feel free to open new issue. thank you!
