### ISSUE TITLE
can not upload datahub (json format)

### ISSUE THREAD

**Issue by KHBHH** [lidaof/eg-react#268]
Hi, 

I am trying to upload a datahub (json format), that has 2 bigWig files by going to Tracks > Local Tracks > Add local hub 

I am trying to upload 3 files:
1) hub.config.json
2) bigWig file 1
3) bigWig file 2

And I get an error in red background in the above, that my folder does not contain hub.config.json (which in real it does). The error is as such: "Aborting, can not find `hub.config.json` file" 
What can be the error behind this? Besides, I am using the latest version of the Washu genome browser (v53.7.0).

FYI: The below is the content of my file: hub.config.json

[
    {
        "filename": "GSM5652233_Liver-Hepatocytes-Z000000R3.hg38.bigWig",
        "type": "bigwig",
        "name": "test bigwig liver",
        "options": {"height": 100}
    },
    {
        "filename": "ENCFF234SHU.bigWig",
        "type": "bigwig",
        "name": "test bigwig",
        "options": {"color": "pink"}
    }
]

**Comment by lidaof** [comment]
Great! I was troubleshooting as it works on my computer and was wondering why :)
Thank you @KHBHH !
