### ISSUE TITLE
Error: Installation on windows 

### ISSUE THREAD

**Issue by KHBHH** [lidaof/eg-react#269]
Hi,

I am trying to install washu app on my local PC using Windows 11. I npm version 8.9.0 and node version 18.2.0.

But I am having trouble when I do 'npm install'

You can see the last screenshotted error in below link:

<img width="946" alt="image" src="https://user-images.githubusercontent.com/39968446/172467192-0f45319f-0afe-4a8e-abcb-e134dbf0e9ac.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/39968446/172466382-d8980b1d-f9e7-4c6f-ad5d-b9496b4b348d.png">

I would appreciate some guidance and thanks for your help!

**Comment by lidaof** [comment]
Hi @KHBHH, it looks like the visual studio installation is required..last month I started with a fresh windows 11 and it worked and I put what I did here: https://eg.readthedocs.io/en/latest/installation.html#setup-on-windows, maybe you can take a look and give it a try? Thanks!

**Comment by lidaof** [comment]
Hi @KHBHH so far we only have tested on react-app-rewired, i am not sure if react-scripts would work or not.
Would you delete your current app code and re-pull from github do `npm install` and `npm start`?

**Comment by KHBHH** [comment]
Hi @lidaof, I reinstalled the whole code. I had to install new version  of jest package (went to node_nodules, deleted jest packages) and ran npm i jest@24.9.0, after that, I was still having error when doing  npm start, I changed the start in package.json from "start": "react-app-rewired  start" to "start": "react-app-rewired --openssl-legacy-provider start", and now I can run it locally on my PC. Just wanted to share this information, as I think the new version of Nodejs was causing some trouble to connect to the localhost.

Thank you!

**Comment by lidaof** [comment]
Hi @KHBHH Glad you figured it out, that's very good to know and thanks for sharing!

**Comment by lidaof** [comment]
for track file hosting, you would need enable CORS for your s3 bucket, you can check more information from https://eg.readthedocs.io/en/latest/tracks.html#enable-cors-on-amazon-s3-bucket

**Comment by KHBHH** [comment]
Hi @lidaof , great to know about S3. How can I upload the app on S3? just upload the whole folder of the app (eg-react-master)? I would appreciate if you could guide me through the process as I am new to AWS. Thanks!

**Comment by lidaof** [comment]
Hi @KHBHH sure, there are lots of tutorial online, you can simply following aws's documentation: https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteHosting.html, feel free to ask me any question you may have.

**Comment by KHBHH** [comment]
Hi @lidaof, thank you for your support. I would also appreciate your advice about the following: As I would like washu to run on my AWS (my jobsite's):
- which way do you think is better? having web static hosting on S3? or creating a docker to live on AWS? (FYI: we also have our data on S3 as well)..
- In either way, which instance of App should I use? The one that I am already successfully running locally? Or the one downloaded from your github (no changed made to it)?

**Comment by lidaof** [comment]
Hi @KHBHH you are welcome!
I guess all combinations should work. performance-wise I think running a static website in S3 with files after `npm run build` should be best. running the local version is easier for regular custom updates. you are ok to run the version with changes you made, just beware that if you pull a future version you might need to make similar changes again. In that case, you can make your own branch and merge future updates from the master branch.

**Comment by KHBHH** [comment]
Hi @lidaof, 

I uploaded the frontend code to my s3 bucket on AWS, and trying to enable static web hosting. Which is in the index file that I should use? Should be the one in the /frontend/public/index.html , right? When I click on this file, nothing shows up...

Also, is it enough to have the frontend folder in my S3 bucket to run the app on my aws instance? Or I should have the whole eg-react-master folder on S3?

I would appreciate your guidance, thanks!

**Comment by lidaof** [comment]
Hi @KHBHH i assume you can run the local dev server successfully with `npm start`? then you need run `npm run build`, this will generate a `build` folder (if it doesn't exist) then you can upload all file under `build` folder to s3 for static website hosting, use `index.html` for both index.html and error.html. and that's enough for hosting a browser mirror site.

let me know you encounter any issue.

**Comment by KHBHH** [comment]
Hi @lidaof, thank you for getting back to me.

So I did run npm build, and it created a folder (build) inside the frontend folder. I uploaded the contents of the build folder into my S3 bucket. Then I did the following:
- enabled static web hosting on my s3 bucket where I have the contents of build folder 
- I turned the 'Block all public access' off
- enabled CORS as described in your documentation (by adding the json file)
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
- gave bukcet policy as such:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::chroma-compeng-dev/*"
        }
    ]
}

**Comment by KHBHH** [comment]
Hi @lidaof 

So I checked my console, the following shows: 

![image](https://user-images.githubusercontent.com/39968446/173618029-f134e0a4-fdbf-4510-b9bf-d9dec86b3e37.png)

**Comment by lidaof** [comment]
Hi @KHBHH, I think what you did are right. I pasted my settings below. I don't think you need CORS settings for static web hosting, you do need CORS for the track hosting folder.
Can you double-check the settings and we can troubleshoot further?

<img width="433" alt="image" src="https://user-images.githubusercontent.com/102806/173617126-0111ba3b-4585-4927-b9f9-eb114a8d64d1.png">
<img width="856" alt="image" src="https://user-images.githubusercontent.com/102806/173617246-74fb9977-3ea8-40c2-a005-e73333f7904d.png">
<img width="856" alt="image" src="https://user-images.githubusercontent.com/102806/173617364-c44c5e30-19cc-49a9-9084-13ee856ff350.png">
<img width="530" alt="image" src="https://user-images.githubusercontent.com/102806/173617581-153fa0c7-5fac-44ae-b0f6-cfd6d1fdc0bf.png">

**Comment by KHBHH** [comment]
Hi @lidaof ,

I have the bucket policy just as you have now, and the following is the objects of my bucket.. (which are basically the contents of build folder):

![image](https://user-images.githubusercontent.com/39968446/173622828-c73a9a53-2576-4d6d-8aac-4257d1996ac2.png)

And I am still getting a blank page!

**Comment by lidaof** [comment]
Hi @KHBHH 
can you try this https://www.npmjs.com/package/http-server and servers the build folder to see if you can see the page?

**Comment by KHBHH** [comment]
Hi @lidaof ,

And when I am in my build folder and I do the following: http-server ./

I get this blank page as below: 

![image](https://user-images.githubusercontent.com/39968446/173627599-ee372195-f272-4758-869f-4859e67fa631.png)

**Comment by lidaof** [comment]
Hi @KHBHH can you zip the build folder and send it to me at lidaof@gmail.com? thanks!

**Comment by KHBHH** [comment]
Hi @lidaof,

I just sent my build folder zipped, I appreciate the support again, thanks!
