### ISSUE TITLE
Adding my public datahub pre-loaded to washu?

### ISSUE THREAD

**Issue by KHBHH** [lidaof/eg-react#273]
Hi,

I have my instance of WashU running on my s3 bucket through Cloudfront. I want to add pre-loaded data/tracks (which lives in one of my S3 buckets), so that whenever the user accesses the app, they can have the option to load the data, as in the example shown below:

<img width="890" alt="image" src="https://user-images.githubusercontent.com/39968446/175545945-09ce1d27-bbc4-4a94-ba46-585d71cd0531.png">

How can I add pre-loaded data? Which file/code do I need to work with? I would appreciate your guidance, thank you!

Right now I have a single track (bigwig file from hg38 genome) that I want to add (as pre-loaded data)...

**Comment by lidaof** [comment]
Hi @KHBHH you would need to edit `hg38.js` file, and then the publicHubList variable.

**Comment by KHBHH** [comment]
Hi @lidaof , thank you, can you share with me the path of hg38.js file please? Thanks again!

**Comment by lidaof** [comment]
sure, frontend/src/model/genomes/hg38/hg38.js

**Comment by KHBHH** [comment]
Hi @lidaof , thank you, can I just update my hg38.js file which already is in my S3 bucket?

Or I should go all over the process again to create build folder (npm build run) etc?

**Comment by lidaof** [comment]
HI @KHBHH when you update hg38.js, you would need to run the build step again and upload the newly built files to the S3 bucket.

**Comment by KHBHH** [comment]
Hi @lidaof , thank you for your advices, it has been so helpful, and it worked!

**Comment by lidaof** [comment]
Hi @KHBHH,

1, you can modify the `defaultTracks` in hg38.js, this controls the default tracks once you load the genome
2, the url info is displayed by the function from line 342 in `frontend/src/components/trackContextMenu/TrackContextMenu.js`, you can edit the code to make it hidden (like comment out line 142)

Just a friendly reminder we do have some policy in the [license](https://github.com/lidaof/eg-react/blob/master/LICENSE.txt) regarding code modification :)

**Comment by lidaof** [comment]
close for now, feel free to open new issue. thank you!
