### ISSUE TITLE
How can I add pre-loaded bed file (if I do not have the index and just .bed file)?

### ISSUE THREAD

**Issue by KHBHH** [lidaof/eg-react#274]
Hi, 

I am trying to include pre-loaded data in .bed format, and when I put the type as "categorical", it does not work, giving error that it is looking for the index. I also tried to put the type as "text" and did not work. How can I have this kind of data pre-loaded in public datahub, what type should it be?

I have included this data in the json file as but I do not know what type should I assign to it?

{
    "type": "?",
    "url": "https://xxxxxxxxxxxx.cloudfront.net/CPG.bed",
}

Thank you, I appreciate your help!

**Comment by lidaof** [comment]
HI @KHBHH in your case mentioned, the type is `bed`, please refer to the documentation: https://eg.readthedocs.io

**Comment by lidaof** [comment]
Hi @KHBHH if you visit the url you sent it says access denied

<img width="773" alt="image" src="https://user-images.githubusercontent.com/102806/176760530-54488149-1475-4613-b69a-a0b1a80a4cee.png">

**Comment by lidaof** [comment]
Hi @KHBHH you can put the .tbi in the same folder with the .gz file, no need to specify in datahub for .tbi

**Comment by KHBHH** [comment]
Hi @lidaof, yes I understand that. But my question is a bit different, I have my bed file just as (.bed) without its index or gz format. I understand that won't work in anyway right? My file is just (.bed) as like a text file.

**Comment by KHBHH** [comment]
Hi @lidaof, thank you!

**Comment by lidaof** [comment]
Hi @KHBHH bed file in remote URL need to be compressed to bgzip and with an index .tbi file, sometimes bed file are pretty big, the browser cannot load the entire bed file into ram, that will freeze the page and brings low performance. Small bed file can be submitted for visualization with the local text feature, please see https://eg.readthedocs.io/en/latest/text.html
