### ISSUE TITLE
New genome assembly

### ISSUE THREAD

**Issue by FarmOmics** [lidaof/eg-react#276]
Can you add the chicken new genome assembly (http://ftp.ensembl.org/pub/release-107/fasta/gallus_gallus/ and ) to browser? The previous assembly (galgal6) supported  by the browser missed many chromosomes, but the new one includes all chromosomes. I do believe the new one will be more useful for the whole cmmunity. Thank you so much!

**Comment by guandailu** [comment]
Indeed, UCSC does not update it yet. We are looking for a brower platform that can visualize multi-omics data. Thanks so much!

**Comment by lidaof** [comment]
Hi @guandailu is it ok to use this file http://ftp.ensembl.org/pub/release-107/fasta/gallus_gallus/dna_index/Gallus_gallus.bGalGal1.mat.broiler.GRCg7b.dna.toplevel.fa.gz for the genome fasta?
do you prefer chrom names in chr1 or 1?

**Comment by guandailu** [comment]
Really thanks for your help, Daofeng! The fastq is correct and I preferred to chromosome name only with numbers, e.g. 1, 2,3…
thanks again!

**Comment by lidaof** [comment]
Hi @guandailu so sorry for the delay...i finally finished add this assembly to the browser, I named it `bGalGal1`, can rename it if you prefer another name.

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/102806/183836268-9101a1f9-9cb0-46aa-ba72-28b5b9fb05ef.png">

**Comment by guandailu** [comment]
Thanks you so much! By the way, a better genome assembly name is: GRCg7b.

**Comment by lidaof** [comment]
great! I will get it updated on the next update. Thank you @guandailu

**Comment by amygu20** [comment]
Dear @lidaof,

Thank you so much for update the new chicken genome, this is very helpful! The new genome actually separated the chicken into broiler and layer. The GRCg7b is the genome for the broiler. Could you please also upload the layer GRCg7w (http://ftp.ensembl.org/pub/release-107/fasta/gallus_gallus_gca016700215v2/dna_index/Gallus_gallus_gca016700215v2.bGalGal1.pat.whiteleghornlayer.GRCg7w.dna.toplevel.fa.gz). Thank you again!

**Comment by lidaof** [comment]
Hi @guandailu , this genome is renamed to `GRCg7b`. Thank you!

> Thanks you so much! By the way, a better genome assembly name is: GRCg7b.

**Comment by lidaof** [comment]
close for now, feel free to open new issue. thank you!
