### ISSUE TITLE
Does Anyone Know the Public IP Address of epigenomegateway.wustl.edu

### ISSUE THREAD

**Issue by b-snel** [lidaof/eg-react#279]
We're trying to add this genome browser to our IP address whitelist so our nginx served data can only be seen by the epigenomegateway.

Does anyone know which IP/IP range is used by https://epigenomegateway.wustl.edu/? Also any ports it might use to reach out and grab remote files?

**Comment by lidaof** [comment]
Hi @b-snel our IP address is 128.252.217.134, port wise I guess 80 and 443?
