### ISSUE TITLE
How to insert an image in the header of the page?

### ISSUE THREAD

**Issue by KHBHH** [lidaof/eg-react#280]
I would like to insert an image next to washu logo as in here? Which file should I need to edit in order to do so?

<img width="863" alt="image" src="https://user-images.githubusercontent.com/39968446/184387913-12877060-a68e-4138-a1cd-ad45d2fe6ade.png">

Thank you for the guidance, much appreciated!

**Comment by lidaof** [comment]
HI @KHBHH you would need to modify the 'Nav.js' file. You can install react-devtools which can help you find which component to edit.

**Comment by KHBHH** [comment]
Hi @lidaof , what file should I edit to insert an image when I just run washu app?

<img width="941" alt="image" src="https://user-images.githubusercontent.com/39968446/187242706-2987ac5b-a1e4-4c40-ac15-3d6737d2e5a6.png">


Thank you for your guidance.
