### ISSUE TITLE
New Chicken (layer) genome assembly 

### ISSUE THREAD

**Issue by amygu20** [lidaof/eg-react#282]
Dear @lidaof,

Thank you so much for update the new chicken genome, this is very helpful! The new genome actually separated the chicken into broiler and layer. The GRCg7b is the genome for the broiler. Could you please also upload the layer GRCg7w (http://ftp.ensembl.org/pub/release-107/fasta/gallus_gallus_gca016700215v2/dna_index/Gallus_gallus_gca016700215v2.bGalGal1.pat.whiteleghornlayer.GRCg7w.dna.toplevel.fa.gz). Thank you again!

_Originally posted by @amygu20 in https://github.com/lidaof/eg-react/issues/276#issuecomment-1217462268_

**Comment by lidaof** [comment]
Hi @amygu20 , you are welcome! Will add that.

**Comment by amygu20** [comment]
Thanks a lot Daofeng

**Comment by lidaof** [comment]
Hi @amygu20 sorry for the delay, `GRCg7w` is added to the browser. Thank you!

**Comment by amygu20** [comment]
Thank you so much Daofeng, Happy new year!
