### ISSUE TITLE
bedcolor help

### ISSUE THREAD

**Issue by UgoBor** [lidaof/eg-react#285]
Hi Daofeng,
Im using a bedcolor file to show on the browser RNASeq data, as remote track; in red are labeled the upregulated genes and in blue the downregulated.
Uploaded as local track the file shows the results with the proper colours but with the same file, as remote track, the colour on the forth column are used as names instead.
Even indexed after bgzip/tabix sorting, the results is the same.

Any suggestions?
Thank you
Ugo

The bed file is is this form:
chr1	10108212	10206993	#0000FF
chr1	17797269	17836568	#FF0000
chr1	21288799	21300391	#FF0000
chr1	25385059	25388163	#0000FF

And the JSON snippet is:
{
      "type": "bedGraph",
      "url": "http://genome-br1./table_sig_color_chr_sorted.bed",
      "name": "wtko_rna-seq",
      "showOnHubLoad": true,
      "metadata": {
                                 "sample": "cortex",
                                 "assay": "RNAseq"
        }
}

**Comment by lidaof** [comment]
Hi @UgoBor thanks for using the browser! You would need use `"type": "bedcolor"`, and the url file need be processed with bgzip/tabix.

**Comment by UgoBor** [comment]
sorry, my bad! the "type": is indeed bedcolor!
the file is processed with bgzip/tabix. I process the file before moving it in its final destination. Could be this the problem?

**Comment by lidaof** [comment]
No worries @UgoBor . The url you pasted `http://genome-br1./table_sig_color_chr_sorted.bed` seems not a valid url?
