### ISSUE TITLE
Bug with Highlights in Session File

### ISSUE THREAD

**Issue by joreynajr** [lidaof/eg-react#286]
Hello,

I've started working with Session Files but I found a funny bug. Let's say I highlight chr16:28845327-28864126, save the session, and reopen the session in a new browser instance. If I do this then I will definitely see a highlight for chr16:28845327-28864126 but if I navigate to any other chromosome with the same exact coordinates then I'll see a highlight at chrOTHER:28845327-28864126 even though it was not in my original session. I think the issue may lie within the JSON files which don't store the chromosome location:

![image](https://user-images.githubusercontent.com/14253227/194943791-8a747d25-3557-4f0e-9cc1-13f3caa1e07a.png)

Just hoping this can be fixed so I don't end up with highlights where they are not supposed to be. 

Thanks in advance!

Joaquin

**Comment by lidaof** [comment]
Hi @joreynajr , thanks for reporting :)
The start and end are not for the start or end position of a particular chromosome, they are actually for the whole genome context coordinates. you can the see the numbers are much bigger, so you should be be safe to go to other regions which should not be highlighted if you didn't highlight them.

<img width="424" alt="image" src="https://user-images.githubusercontent.com/102806/194982260-943bd8ac-1abd-43ce-9f9f-779cc6ba7446.png">

**Comment by joreynajr** [comment]
Hi @lidaof, was I was hoping to do is create a python function where I could generate sessionFiles with a particular set of highlights. This would be very powerful from a visualization standpoint and there might be a workaround but I think it would be a great feature to have.

**Comment by lidaof** [comment]
Hi @joreynajr do you mean if you have a chrX:xxx-xxxx region, you want to know how to convert to start/end in your python script? it will depend on the genome, you can line up all the chromosomes, then for example 0 position in chr2 will be used by end of chr1 instead, same applied to other chrom and positions. let me know if I misunderstood your request. thanks!

**Comment by joreynajr** [comment]
No worries @lidaof, I think I found a nice workaround! Thanks for your quick responses and the great software!

**Comment by lidaof** [comment]
Great, thanks! @joreynajr
