### ISSUE TITLE
Roadmap data hub - Data fetch failed 

### ISSUE THREAD

**Issue by xinmin-zhang** [lidaof/eg-react#287]
For a project I am working on, WashU Epigenome browser has been key to providing important epigenome information. I have been using tracks from human hg38, Public data hubs -> Reference human epigenomes from Roadmap Epigenomics Consortium->All Chromatin states tracks 

Today somehow these tracks cannot be loaded. The track shows error message "Data fetch failed. Reload page or change view to retry."
I tried reloading and changing view, but these didn't help. 
Do you know what the issue is and can you please suggest a fix? 
![image](https://user-images.githubusercontent.com/25138733/194965640-119a99d9-ed55-439b-ac19-214db658274b.png)

Thanks, 
Xinmin

**Comment by lidaof** [comment]
Hi Xinmin,

Unfortunately the server hosting the data has disks failure and has trouble
booting. I am traveling and will try to fix it as soon as possible when I
am back to that server.

**Comment by xinmin-zhang** [comment]
Hi Daofeng, 
Thanks for the quick response. I look forward to the data server back online. 
Xinmin

**Comment by lidaof** [comment]
Hi @xinmin-zhang the server is back online. (I am still troubleshooting the disk failure, we might replace some disks in the near future which might cause temporary down time)

**Comment by xinmin-zhang** [comment]
Great, thanks!
