### ISSUE TITLE
Embedding for Github Instructions work but not ReadTheDocs

### ISSUE THREAD

**Issue by joreynajr** [lidaof/eg-react#288]
Hi,

Just leaving a comment. I found that the WashU embedding instructions on Github work out of the box but that's not true for the ReadTheDocs instructions: https://eg.readthedocs.io/en/latest/installation.html#embedding. 

For this second implementation, it seems like the main issues have to do with sourcing for `igv.min.js`, `epgg.js`, `epgg_v47.2.8.css`. Whatever the case I think it would be helpful to replace the ReadTheDocs implementation with the Github version or something of this nature.

Thanks again for the software,

Joaquin

**Comment by lidaof** [comment]
Hi @joreynajr will fix that! Thanks for reporting it.
