### ISSUE TITLE
who to use the higlass private  API cool track ？

### ISSUE THREAD

**Issue by WANGchuang715** [lidaof/eg-react#298]
![image](https://user-images.githubusercontent.com/67625036/207493960-9301b163-e2cf-4525-8691-076ad794a07f.png)
I noticed that currently only the public API cool track can be used,but I want to use my own data by building  the higlass private  API.
I changed the HIGLASS_API_URL of this file （eg-react/frontend/src/dataSources/CoolSource.js）to be private, but still can't display the track. 
I hope to get your help.

**Comment by lidaof** [comment]
Hi, @WANGchuang715 actually it's the first time to know about such kind of issue. I guess it's probably due to the CORS issue, when you open the web browser console and load the cool track, did you see some error message? if yes, can you post it here?

**Comment by WANGchuang715** [comment]
> The problem has been solved, I made a mistake when writing the HIGLASS_API_URL.
