### ISSUE TITLE
Can I set "set scale with height" in hub json file?

### ISSUE THREAD

**Issue by changxinw** [lidaof/eg-react#302]
Hi Daofeng,

Happy new year.

I'm setting up a longrange track in a hub file with an arc display mode. I was wondering if I can set the option "set scale with height" in the hub json file? Sometimes the track height might be too low to display an arc.

Thanks,
CW

**Comment by lidaof** [comment]
Hi @changxinw happy new year!
You can set `clampHeight` to `true` in the track `options`, let me know if it doesn't work.
thank you!

**Comment by changxinw** [comment]
That works. Thank you very much.
