### ISSUE TITLE
 ABcompartment  question

### ISSUE THREAD

**Issue by Zheng19w** [lidaof/eg-react#308]
chr     start   end     LaiWu
chr1    0       100000  1.36118
chr1    100000  200000  1.37243
chr1    200000  300000  1.28345
chr1    300000  400000  1.16653
chr1    400000  500000  1.15569
chr1    500000  600000  1.39406
chr1    600000  700000  0.82206
chr1    700000  800000  0.882045
chr1    800000  900000  0.863725
chr1    900000  1000000 0.64599
chr1    1000000 1100000 0.621465
chr1    1100000 1200000 0.650945
chr1    1200000 1300000 0.511245
chr1    1300000 1400000 0.721395
chr1    1400000 1500000 0.80348
chr1    1500000 1600000 0.90032
chr1    1600000 1700000 0.984115
chr1    1700000 1800000 0.940865
chr1    1800000 1900000 0.6253

Dear professor : 
                           How do I display ABcompartment in the washu browser, As in the above list, the fourth column is the PC1 value.

**Comment by lidaof** [comment]
Hi @Zheng19w you can format it either as bigwig or bedgraph.gz, it can be viewed locally or on your own webserver. 
please check here https://eg.readthedocs.io/en/latest/tracks.html#prepare-track-files. feel free to ask for any further questions.

**Comment by Zheng19w** [comment]
Thank you for your reply
