### ISSUE TITLE
Does WashU now support users to customize genomes? 

### ISSUE THREAD

**Issue by thekingofall** [lidaof/eg-react#309]
Hello, does WashU now support users to customize genomes? I now have some custom genomes that I would like to use on the local version of the WashU genome browser, wondering if this can be done? I've searched your documentation, and I can't seem to find a way to customize the WashU genome.If possible, could you please guide me?

**Comment by lidaof** [comment]
Hi @thekingofall the docs for adding a new genome is located here: https://eg.readthedocs.io/en/latest/add.html. for your own gene annotation, you would need setup your backend documented here https://eg.readthedocs.io/en/latest/installation.html#setup-your-own-backend-api-optional. hope this helps. Feel free to reach out further.

**Comment by thekingofall** [comment]
你好,老茅已收到你的来信，稍后我会仔细查看，谢谢(这是自动回复，不用回复过来）

**Comment by thekingofall** [comment]
你好,老茅已收到你的来信，稍后我会仔细查看，谢谢(这是自动回复，不用回复过来）
