### ISSUE TITLE
how can I road my files?

### ISSUE THREAD

**Issue by TakatoG** [lidaof/eg-react#311]
Hi,
I made a washU.txt file from CHiCAGO, so I loaded it in WashU browser.
However, it remained blank...

How can I my files to load??
I manipulated Tracks>Local text tracks.

Thank you.

**Comment by lidaof** [comment]
Hi @TakatoG wondering if your file contains 1, 2, 3 as chrom name, should be chr1, chr2 etc? if not, can you send me your file (or part of it)? thanks!

**Comment by TakatoG** [comment]
Hi!
Thank you for your replay. I'm a a beginner of bioimformatics..

I tested CHiCAGO's file as follows;
https://www.bioconductor.org/packages/release/bioc/vignettes/Chicago/inst/doc/Chicago.html

and I got .txt file.

([_washU_text.txt](https://github.com/lidaof/eg-react/files/10950410/_washU_text.txt))

Can I load this? 
Thank you.

**Comment by lidaof** [comment]
Hi @TakatoG ,

Sorry for late reply. Current this format is not supported directly, but can be added easily in next release.
if you can do scripting, you can convert your file to the follow below:
```
chr1    713605  715737  chr1:720589-722848,2
chr1    717172  720090  chr1:761197-762811,2
chr1    720589  722848  chr1:713605-715737,2
chr1    755977  758438  chr1:758539-760203,2
```
then you can load the reformatted text file through: Tracks-> Local text tracks-> choose `long-range text`
<img width="442" alt="image" src="https://user-images.githubusercontent.com/102806/224790961-3eac3c7a-9bf0-4383-8588-a6d7862a4250.png">

Hope this helps. I will add the direct support in next release (a week or two).

**Comment by TakatoG** [comment]
Thank you for reply.
Is it possible that convert the file?
Could you tell me how to convert the file?

Thank you.

**Comment by TakatoG** [comment]
Hi,
<img width="632" alt="スクリーンショット 2023-03-16 19 23 10" src="https://user-images.githubusercontent.com/104481317/225588668-2b5fbd82-850a-4879-a93c-f1998a0f414f.png">

Thank you very much for teaching me!
However do you know why this happen??

**Comment by TakatoG** [comment]
Hi,
Thank you very much for teaching me!
However do you know why this happen??
<img width="1426" alt="スクリーンショット 2023-03-16 19 24 10" src="https://user-images.githubusercontent.com/104481317/225588936-c5e99fe3-a640-4cab-b559-4d4de559ba7d.png">

**Comment by lidaof** [comment]
this is called heatmap style, you can right click and switch to arc style

**Comment by TakatoG** [comment]
Hi.
Thank you for teaching me!
Really appreciate.
