### ISSUE TITLE
Trouble loading example Roadmap data hub in browser

### ISSUE THREAD

**Issue by AkshayBalaji** [lidaof/eg-react#313]
Hi, I am trying to understand how the `metadata` object works in the hub.config json file, and I was trying to run the example Roadmap data hub provided in the documentation to do so, pasted below:
`{
    "url": "https://egg.wustl.edu/d/hg19/GSM997242_1.bigWig",
    "metadata": {
        "Sample": [
            "Adult Cells/Tissues",
            "Blood",
            "Other blood cells",
            "CD4+_CD25-_Th_Primary_Cells"
        ],
        "Donor": [
            "Donor Identifier",
            "Donor_332"
        ],
        "Assay": [
            "Epigenetic Mark",
            "Histone Mark",
            "H3",
            "H3K9",
            "H3K9me3"
        ],
        "Institution": [
            "Broad Institute"
        ]
    },
    "type": "bigwig",
    "options": {
        "color": "rgb(159,0,72)"
    },
    "name": "H3K9me3 of CD4+_CD25-_Th_Primary_Cells"
}`

Could you clarify 1) how to load this data hub properly in the browser and 2) how this metadata should reflect in the browser? Thank you!

**Comment by lidaof** [comment]
Hi @AkshayBalaji a data hub is a collection/list/array of the track objects you pasted, you can out a datahub json file in a web URL or upload it to the browser, please see https://eg.readthedocs.io/en/latest/usage.html#adding-a-custom-track-or-data-hub, for 2) you can click the metadata button above the tracks, and a color bar will display at the right of the tracks, colors indicates metadata defined in your json file, like assay/sample information.

Hope this helps.
