### ISSUE TITLE
Not able to load AWS S3 public BigWig files in the browser

### ISSUE THREAD

**Issue by AkshayBalaji** [lidaof/eg-react#317]
Hi, I'm having an issue with loading bigwig files stored on AWS S3 as remote tracks. Every time I try it, the track fails to load and the browser gives an error saying "Data fetch failed." Our bigwig files are public access and load successfully in igv, so we know it's not an issue with the file itself. Do you know what might be causing this and troubleshooting ideas? Thank you!

**Comment by lidaof** [comment]
Hi @AkshayBalaji it's probably due to cors settings....have you tried this https://eg.readthedocs.io/en/latest/tracks.html#enable-cors-on-amazon-s3-bucket? Thank you!

**Comment by AkshayBalaji** [comment]
Hi @lidaof ahh, I have a feeling that's the answer! I have not tried that yet and will see if that works, thank you so much!

**Comment by lidaof** [comment]
Hi @AkshayBalaji Great, let me know if that helps. Thank you!
