### ISSUE TITLE
Add new species to the epigenome browser

### ISSUE THREAD

**Issue by DustinSokolowski** [lidaof/eg-react#328]
Hello!

Thank you for the wonderful tool. I was hoping to be able to compare the mm10 genome and my new assembly. As such, I was hoping that you could add my assembly like you did with [228](https://github.com/lidaof/eg-react/issues/228)?

If you are still doing this, then here is my fa and gff3 file. The genome is stored on rapid ensembl.

Genome: https://ftp.ensembl.org/pub/rapid-release/species/Heterocephalus_glaber/GCA_944319715.1/ensembl/genome/Heterocephalus_glaber-GCA_944319715.1-unmasked.fa.gz
annotation: https://ftp.ensembl.org/pub/rapid-release/species/Heterocephalus_glaber/GCA_944319715.1/ensembl/geneset/2022_09/Heterocephalus_glaber-GCA_944319715.1-2022_09-genes.gff3.gz

Thanks so much!
Dustin

**Comment by lidaof** [comment]
Hi @DustinSokolowski I will work in it and let you know once it's done. Thanks!

**Comment by DustinSokolowski** [comment]
Thank you,

I really appreciate it.

**Comment by DustinSokolowski** [comment]
Hello Dr. Li,

Thank you again for taking the time to add our assembly to the browser.

I was wondering if there is a way to pull the syntenic blocks from the genomealign files. For example, getting the co-ordinates for the blue and purple bars below. 
![image](https://github.com/lidaof/eg-react/assets/56414662/e98beae7-8bd3-4b95-88cf-c2dcbe60906d)

My impression is that as I zoom out on the browser, the browser automatically changes the bp resolution on the genomealign file. This being said, the genomealign file is a custom object, if I'm not mistaken, so I'm unsure if there's an easy way to pull the most "zoomed out" coordinates. If not, do you have a recommended way of finding these coordinates from the axt file?

Thanks!
Dustin

**Comment by lidaof** [comment]
Hi @DustinSokolowski sorry for the delay in adding your species...trying to finish something before one of the consortium annual meetings
for your question about comparative browser and genomealign track, I am copying Xiaoyu @xzhuo  , he should have the answers for you.

**Comment by DustinSokolowski** [comment]
Thank you, and enjoy the meeting!

**Comment by xzhuo** [comment]
Hi @DustinSokolowski, we had several meetings in the last few weeks, sorry for the late reply... The browser will switch between "fine mode" (base to base vertically aligned) and "rough mode" (connected large blocks) based on resolution. The threshold is 10bp/pixel. It will display "rough mode" if the resolution is lower, and it will display the "fine mode" if the resolution is higher. I don't think there is an easy way to manipulate that on the main website, but if you are willing to install a local instance I can show you which parameter to change to adjust the view. 
Cheers,
-Xiaoyu

**Comment by DustinSokolowski** [comment]
Hey Xiaoyu, 

Sorry for the slow reply back, I was also traveling for conferences actually. This sounds excellent! Just to be clear, am I able to then pull the co-ordinates from the block? I am basically wondering if I can use the GenomeCov file to look at genome-wide synteny.

Best,
Dustin

**Comment by xzhuo** [comment]
Hi Dustin, if you want the alignment, you can download the genome-align track (the URL is available by right-clicking) and unzip it. The alignment format is described here: https://eg.readthedocs.io/en/latest/tracks.html#genome-align-track. It should not be too hard to extract coordinates from it. 
I hope it answers your question,
Best,
-Xiaoyu

**Comment by DustinSokolowski** [comment]
Hey! I'm sorry for being unclear. What I'm looking for are the co-ordinates of the wide "nets" you have when then genome-align track is in rough mode. So in the example above, I'm hoping to be able to get the co-ordinates on the pink bars, as well as the co-ordinates associated with the blue bars, but genome wide. Would I need a local instance for this or is there a straightforward netting of the genome-align track that you perform?

![image](https://github.com/lidaof/eg-react/assets/56414662/0bfc7876-8d99-47e0-a713-15b4ef7dc7b1)

**Comment by xzhuo** [comment]
Do you mean you want the coordinates of the merged alignment blocks? Sorry, we don't have that in any file... The browser will merge alignment blocks on the same chromosome within a certain distance (when converted to the display distance < 200 pixels). Maybe you can merge them yourself from the genome-align file by applying a fixed distance?

**Comment by DustinSokolowski** [comment]
Hey, Exactly! 

Hmm okay. We will try to make a script to extract these blocks. If the blocks successfully match up well to the browser, I'll send it your way in case other people are interested in them. Thank you for your patience.

Best!
Dustin
