### ISSUE TITLE
How to draw boundary for TADs

### ISSUE THREAD

**Issue by KunFang93** [lidaof/eg-react#329]
Hi,

Thanks for providing this wonderful browser! I wondered if you could shed some light on how to draw TADs boundary like the following figures? Thanks in advance~
![F4 large](https://github.com/lidaof/eg-react/assets/15643651/9d1eb714-5900-4cd7-b23f-8b26909c7e03)

Best,
Kun

**Comment by xzhuo** [comment]
Thanks for your appreciation! But I draw the boundary with affinity Designer / Adobe Illustrator ...
