### ISSUE TITLE
SARS-CoV-2 RNA modification

### ISSUE THREAD

**Issue by shuaibm33** [lidaof/eg-react#331]
I am trying to visualize the list of RNA modification from Kim et al (on washu epigenome browser) as this is part of the public data hub. But it does not work (please attached screen shot).
<img width="1562" alt="Screen Shot 2023-08-24 at 2 40 07 PM" src="https://github.com/lidaof/eg-react/assets/33518653/6b40c409-75fd-486b-a73e-35ba06e0e10b">

**Comment by lidaof** [comment]
Hi @shuaibm33 sorry for the trouble and delayed response. It should be fixed now.
Thanks for using the browser.
