### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by NiniWang** [lidaof/eg-react#332]
I am tring to use the browser to make a comparetive epegenomic browser and also load different track from different species using two differet species genomes that you don't have on the browser database. Is it possible to do that following the document? I just met some bugs at very first step to install the browser. See the screenshot below,
![1693388506104](https://github.com/lidaof/eg-react/assets/35753568/74a5e81a-b6b3-408e-b4c9-4b8783ee2253)

I checked the configuration of the webpack webpack.config.js, there is nothing about the "query". Should I use a specific version of webpack? Or how could I fix this problem? Thanks

**Comment by lidaof** [comment]
Hi @NiniWang typescript 3.4.5 should work, sorry this version is a bit old. Or you can download [this file](https://wangftp.wustl.edu/~dli/test/frontend.zip), after decompress, run `npm start` directly.
 if you are using node v18, type `export NODE_OPTIONS=--openssl-legacy-provider`  before npm start

**Comment by NiniWang** [comment]
Thank you for your reply. I downloaded the file that you sent, and run `npm start`. I think this problem fixed, but I met a new problem. 
![1693470520071](https://github.com/lidaof/eg-react/assets/35753568/bc9e4244-e5e1-4a23-b652-ced01c4d27cd)
And I intalled this `react-app-rewired` by `npm install react-app-rewired@1.x --save-dev`, but after this all the other packages be installed again and replaces packages inside frontend folder that I already have, causing the first problem again. How could I  solve this problem?

**Comment by lidaof** [comment]
Hi @NiniWang can you try this? after decompressing the zip file I sent to you, go to that folder, run `sudo npm -g react-app-rewired`, then `npm start`. let's see if it works.

**Comment by NiniWang** [comment]
Hi Daofeng, sorry to bother you again. I run `sudo npm install -g react-app-rewired`, but I got an erro. Then I try `npx create-react-app my-app`, it works. I run `npm start` again. But the port 3000 can not be opened, and is replaced by port 3001. There is nothing on port3001.
![1693562564924](https://github.com/lidaof/eg-react/assets/35753568/54812a59-3a0b-43cc-aefc-cfb6c03d8d63)

**Comment by lidaof** [comment]
when you see the screen says `you can view my-app in the browser` means the app is running on 3001 port, you should see something if you open localhost:3001 on that time, do you see blank or error?

**Comment by NiniWang** [comment]
Yes, but it's blank
![1693576790077](https://github.com/lidaof/eg-react/assets/35753568/468d1541-256e-42dc-a902-3a63f6252b5c)

**Comment by lidaof** [comment]
this is correct, as you are creating a blank app using create-react-app.

how about try run npm start in the frontend folder I sent to you?

**Comment by NiniWang** [comment]
I think I got the right port, but there is still nothing on the website and some error message.
![image](https://github.com/lidaof/eg-react/assets/35753568/6c3de644-19eb-4c1b-a0de-ad65053909fb)

<img width="1385" alt="Screenshot 2023-09-04 at 14 27 35" src="https://github.com/lidaof/eg-react/assets/35753568/8f03a42b-aacd-4fe7-a793-857bfb61d72e">

**Comment by NiniWang** [comment]
no, there is same information with the 3000/browser

**Comment by lidaof** [comment]
i might need to remotely see your computer to troubleshoot, do you think we could setup a zoom meeting some time?

**Comment by NiniWang** [comment]
If it's possible that would be great! Could I have your wechat number maybe it's easy for us to setup a meeting? my wechat number:  _Nini2020_

**Comment by lidaof** [comment]
sure, mine is `lidaof`

**Comment by lidaof** [comment]
issue seems resolved through zoom meeting, closed for now.
