### ISSUE TITLE
hosting track by CyVerse

### ISSUE THREAD

**Issue by Xianglmoffitt** [lidaof/eg-react#334]
Hello,

I tried to follow the tutorial described in https://wiki.wubrowse.org/Track_hosting, to submit a track hosted by CyVerse. But CyVerse has updated, there is no more "send to Genome Browser" option. Instead, they have a "public link" option to generate a public access link. I can download the file through this public link. But the data fetch failed when I used it in the browser. My test link is "https://data.cyverse.org/dav-anon/iplant/home/xiangcyverse/wasu_longrange_test" which is a longrange interaction txt file.

Could you please help me solve how to fetch data from CyVerse? Thank you!

**Comment by lidaof** [comment]
Hi Xiang, the documentation you mentioned is for the legacy version of the browser, which is http://epigenomegateway.wustl.edu/legacy/, so I assume you want to use the legacy browser, you would need to format your long-range file with bgzip/tabix, and put the .gz and .gz.tbi file in same folder under cyverse, then use the public link of .gz file in the legacy browser for the custom track, that should work. let me know if this works or not. 
Thank you!

**Comment by Xianglmoffitt** [comment]
Hi Daofeng, it works on the latest browser but not work on the legacy one. It is what I need. So the important part is to generate a .gz and .gz.tbi file through bgzip and tabix. I thought it was some permissions issues from CyVerse that leads to the failure of fetching data. Now I have an idea how to host a remote datahub on WashU browser. Thank you so much! I will close this issue.

**Comment by lidaof** [comment]
Glad it works! Thank you for letting me know :)
