### ISSUE TITLE
Cannot load the hub. Error: HTTP undefined

### ISSUE THREAD

**Issue by zhichunlizzx** [lidaof/eg-react#344]
I met some problems when using http://epigenomegateway.wustl.edu/browser/-"Remote track"-"Add remote data hub" function，the url of the hub is http://39.107.224.252/BioPresentation/G1/G1_t.json. Looking forward to your answer.
![微信图片_20240202101137](https://github.com/lidaof/eg-react/assets/48573702/bebdeca6-28ab-44f4-af9d-4f47c59f1f67)

**Comment by lidaof** [comment]
Hi @zhichunlizzx the JSON file you provided is not a valid JSON format, please use some online JSON editor to validate it, for example, https://jsoneditoronline.org/. 

(The syntax is for the old version of the browser, sorry for the confusion, the current documentation is at https://eg.readthedocs.io/en/latest/)
