### ISSUE TITLE
Cannot start my own backend API

### ISSUE THREAD

**Issue by G1298192734a** [lidaof/eg-react#346]
I can't start my server.Looking forward to your help.
![image](https://github.com/lidaof/eg-react/assets/162153862/d0b562aa-3778-4025-8847-0a8927f58f52)

Hi!Dr.Li,I'm a student and I'm following the browser documentation to learn how to use it.
firstly,I installed this browser on the windows using conda.I then tried importing a species that was not present on the browser.I enable cors through http-server,this went well.
![image](https://github.com/lidaof/eg-react/assets/162153862/b75b94df-b950-4f76-ab0c-83a8938a61c4)
![image](https://github.com/lidaof/eg-react/assets/162153862/202023df-cdf8-4ab5-913f-f6728767026a)
secondly,I tried setuping backend API because I found I can't search genes.
I installed mongodb and started,downloaded the backend package through yarn,transferred the data to the mongodb database and went well
![image](https://github.com/lidaof/eg-react/assets/162153862/04dfe941-2226-499d-a827-495232ef5546)
![image](https://github.com/lidaof/eg-react/assets/162153862/9b374a03-bda7-4c34-b6ad-57e1944a9191)
But when I started my API,an error appeared,that day was Wednesday.I am still stuck in it until now.
I don't know much about java but I try to find where the problem is
![image](https://github.com/lidaof/eg-react/assets/162153862/fcd2cc75-1a9e-4b32-9806-43fbfe035c0f)
![image](https://github.com/lidaof/eg-react/assets/162153862/ea7a6b17-a5f2-4eb3-b153-805731fec493)

Thanks!

**Comment by lidaof** [comment]
Hi @G1298192734a Thanks you for trying the browser! I actually never seen this error before....need to google a little bit. Which node version are you using? can you try node v16?

**Comment by G1298192734a** [comment]
I'm using node v20 and npm v10

**Comment by G1298192734a** [comment]
You are right! After using node16, everything is normal now. You directly helped me solve the problem, which is really great. thanks for your help

**Comment by G1298192734a** [comment]
I will continue to try your browser and may bother you if there are any problems in the future.

**Comment by lidaof** [comment]
Thanks for the update @G1298192734a . Feel free to ask anytime!

**Comment by G1298192734a** [comment]
![image](https://github.com/lidaof/eg-react/assets/162153862/bca2d1fd-a29d-4179-9e4d-8e11996cbf1e)
The error is still there，I feel that maybe the program is still using the default typescript, and the one I installed is global.

**Comment by G1298192734a** [comment]
![image](https://github.com/lidaof/eg-react/assets/162153862/20ed7db9-7ec0-4977-9e26-7d6c084e8cca)
Not right either

**Comment by G1298192734a** [comment]
Update typescript to the latest version locally instead of globally，i get the epgg.js and epgg.css.
but
![image](https://github.com/lidaof/eg-react/assets/162153862/97027031-ed04-405c-ae30-057e58336a88)

**Comment by lidaof** [comment]
Hi @G1298192734a can you modify your mirror based on this version https://wangftp.wustl.edu/~dli/test/frontend.zip, no need to run npm install

**Comment by G1298192734a** [comment]
After using the frontend you provided, I can get epgg.js and epgg.css without any problems.But they still can't work, and other js files generated under dist/js can be used.
So I feel like I don’t understand the files generated by the script enough.However, my epgg.js is 9.1M and the one in the example is only 2.3M. Is there any other processing?
![image](https://github.com/lidaof/eg-react/assets/162153862/25392937-fcd3-4acc-b798-5bb7fc811d3f)

**Comment by lidaof** [comment]
Hi @G1298192734a i am not quite sure, I guess probably due to different compress settings...but I used all default settings....what's the error msg in your version?

**Comment by G1298192734a** [comment]
There is no error message and the program is normal.It's just that it can't be displayed after I fill in the html.
When I tried to replace the files in it, I found that it should be a problem with epgg.js.
![image](https://github.com/lidaof/eg-react/assets/162153862/9653aa69-7ba2-428a-ae8d-a79b34b50a92)
![image](https://github.com/lidaof/eg-react/assets/162153862/1fac7f8d-5684-48c0-acbe-e6a6c6d8ac28)
![image](https://github.com/lidaof/eg-react/assets/162153862/d4da04f9-59b1-47c2-8f79-fd5925afcd51)
![image](https://github.com/lidaof/eg-react/assets/162153862/71a7bde0-7566-4982-997e-22f14367c5b4)

**Comment by G1298192734a** [comment]
@lidaof,Hi! I believe there is no error in the build-emb step.
![image](https://github.com/lidaof/eg-react/assets/162153862/8b666be8-cfdd-4dd9-bef8-19b2308f6f1b)
And I feel like the epgg.js used for html should be under umd. Could you tell me how umd is generated?
![image](https://github.com/lidaof/eg-react/assets/162153862/d6a29c30-3d2c-4137-b053-4d1e867bbf1f)

**Comment by G1298192734a** [comment]
Maybe the error msg you want to see is this
![image](https://github.com/lidaof/eg-react/assets/162153862/0fa17f68-e071-468f-b779-c3fafcc0be2b)

**Comment by lidaof** [comment]
Hi @G1298192734a thanks for the screenshot...i have no clues so far....sorry, will do some tests on my side.

**Comment by G1298192734a** [comment]
@lidaof  Hello,today I'm really glad that I found some ideas through the browser's error msg. First, change c=t.length in epgg.js to c=t?.length. The screen can be displayed, but the backend data still cannot be read.
![image](https://github.com/lidaof/eg-react/assets/162153862/3149f2ee-8a2c-4f1d-b303-b4098c785ed5)
![image](https://github.com/lidaof/eg-react/assets/162153862/bd7e2ef3-9ada-4a1c-bfee-ea2f08dd55a7)

**Comment by G1298192734a** [comment]
just the default
![image](https://github.com/lidaof/eg-react/assets/162153862/9833bb3a-e209-4483-9b4e-a98179958c49)

**Comment by lidaof** [comment]
what's the error msg when start your own backend? did you use node v16 as well?

**Comment by G1298192734a** [comment]
Just now my backend was still running normally, but when I restarted it reported an error
![image](https://github.com/lidaof/eg-react/assets/162153862/f5c41fee-25c0-4cb6-aa81-1b90c3532aea)
The version of this node is 16.4

**Comment by G1298192734a** [comment]
Sorry, I killed the wrong task and the running backend was not turned off.

**Comment by G1298192734a** [comment]
browser error msg is the same as before.
![image](https://github.com/lidaof/eg-react/assets/162153862/f478b810-d2a4-4199-a2b7-47bd91fec9a1)

**Comment by G1298192734a** [comment]
@lidaof Hi,Dr.Li! I just fixed the backend problem by adding an nginx proxy instead of reading the local backend directly and couldn't be happier.
![image](https://github.com/lidaof/eg-react/assets/162153862/16496133-ef9c-44c1-be12-0d694d8e3274)
Then there is only one question left。When I click the Genomic Region Locator，The results are as follows：
![image](https://github.com/lidaof/eg-react/assets/162153862/be04817e-75e2-4dc7-85aa-7f8e1ae3a911)

**Comment by lidaof** [comment]
interesting! good to know the reverse proxy fixed your problem!

**Comment by G1298192734a** [comment]
But I think my handling of epgg.js may still be wrong，
because I don’t know what I modified.

**Comment by G1298192734a** [comment]
In addition, I want to import cool files, but it is a bit difficult to use higlass. I wonder if you can give me some suggestions and whether I should open an new issue?

**Comment by lidaof** [comment]
Hi @G1298192734a for cool files you would need to setup a higlass server, you can check more at https://docs.higlass.io/higlass_server.html

**Comment by G1298192734a** [comment]
OK，I will try it later. I appreciate your time. Your reply is really helpful for me.
All the best.
