### ISSUE TITLE
Access to legacy browser?

### ISSUE THREAD

**Issue by albertoriva** [lidaof/eg-react#348]
Hello,

I am getting a 404 error when trying to access the legacy browser:

"The requested URL /legacy/ was not found on this server."

Is this temporary, or is the old browser gone?

**Comment by lidaof** [comment]
Hi @albertoriva It's temporary, we are having some issues with the database server who provides mysql support for the legacy browser, working on it, should be back online next 1-2 weeks, sorry for the inconvenience.

**Comment by lidaof** [comment]
Hi @albertoriva sorry for the inconvenience again, the legacy browser should be back now. Let me know if there is any issue.
(there are indeed failed drives on that server, we are going to replace them, so there maybe some short time in the near future)

**Comment by albertoriva** [comment]
Hello Daofeng,

Thank you for your note, glad to hear that the browser is back.

By the way, I would really like to be able to switch to the new browser,
but I still can't get it to understand https URLs in track hubs. Any
updates on that issue?

Thank you!

Alberto

**Comment by lidaof** [comment]
Hi @albertoriva , our pleasure.

Both browsers can be accessed with http or https URL, we know some lab doesn't have https enabled web server, so if your data is hosted with http protocol, you can use the http version of the browser.

**Comment by albertoriva** [comment]
Sorry I wasn't clear. I was referring to loading a remote data hub using a
JSON file. This is what happens when I try:

[image: image.png]


The same hub works perfectly in the legacy browser. Here's the address:

https://lichtlab.cancer.ufl.edu/reports/MDS//NS3526-noIgG/NS3526/hub.json


Thank you!

**Comment by lidaof** [comment]
HI @albertoriva i see, yes, so far I haven't found a good JS library can parse password protected URL files..will keep exploring...thanks!

**Comment by albertoriva** [comment]
Daofeng,

But this URL is not password protected...

Alberto

**Comment by lidaof** [comment]
Hi @albertoriva i mean the URLs in your json file, for each track file

**Comment by albertoriva** [comment]
Right, sorry for the confusion. I remove the passwords from the URLs, and
it still gives the same error (while it loads perfectly in the legacy
browser).

Thank you!

**Comment by lidaof** [comment]
Ha, i see, yes, i see the problem is you need to enable CORS on your webserver.
The new browser users entirely JavaScript, the legacy browser uses a C backend which fetches data doesn't need CORS..sorry for the inconvenience....It's the JS default security setup.
https://eg.readthedocs.io/en/latest/tracks.html#configure-your-webserver-to-enable-cors

**Comment by albertoriva** [comment]
Yes, it works now! Thank you!!

Alberto
