### ISSUE TITLE
Axis Labels Overlapping 

### ISSUE THREAD

**Issue by EvoAlias** [lidaof/eg-react#44]
Don't allow bottom axis label to encroach on next track's labels. 
<img width="282" alt="screen shot 2018-08-09 at 1 48 11 pm" src="https://user-images.githubusercontent.com/8665173/43919234-f0a9f88e-9bda-11e8-95af-0318c51e624b.png">

**Comment by lidaof** [comment]
your track height maybe too low~

**Comment by lidaof** [comment]
should be improved in latest build

**Comment by EvoAlias** [comment]
Bottom label still overlaps the line for the next track. Also there is weird whitespace below bedgraph tracks (with - and + values).
<img width="42" alt="screen shot 2018-10-25 at 1 09 34 pm" src="https://user-images.githubusercontent.com/8665173/47521018-7286ee80-d857-11e8-8cb5-92bd9d725420.png">

<img width="81" alt="screen shot 2018-10-25 at 1 09 58 pm" src="https://user-images.githubusercontent.com/8665173/47521025-787ccf80-d857-11e8-93c2-3120b9efb25e.png">

**Comment by lidaof** [comment]
maybe send me your session id?
you also see the downside of moving top label down and bottom one up might cause overlap with the center 0

**Comment by lidaof** [comment]
should be improved on latest build.
Please reopen is problem still exists.
