### ISSUE TITLE
Change Custom hub button color to look like a button. 

### ISSUE THREAD

**Issue by EvoAlias** [lidaof/eg-react#48]
Currently this button blends right in with the background. 
<img width="369" alt="screen shot 2018-08-09 at 1 58 33 pm" src="https://user-images.githubusercontent.com/8665173/43919731-74b82aa0-9bdc-11e8-8514-90d9df33e816.png">

**Comment by lidaof** [comment]
The custom track/hub UI was updated for this matter.
