### ISSUE TITLE
Zoomed out is not centered 

### ISSUE THREAD

**Issue by EvoAlias** [lidaof/eg-react#51]
If I look at a central point and zoom out this point moves to the right of the zoom out and is not centered.

View 1: 
<img width="1699" alt="screen shot 2018-08-09 at 5 04 57 pm" src="https://user-images.githubusercontent.com/8665173/43979669-2469e072-9cb1-11e8-923f-7c113aec4dc7.png">

View 2: 
<img width="1694" alt="screen shot 2018-08-09 at 5 05 15 pm" src="https://user-images.githubusercontent.com/8665173/43979680-30c87810-9cb1-11e8-9870-d9a238aa3a77.png">

View 3: 
<img width="1687" alt="screen shot 2018-08-09 at 5 05 35 pm" src="https://user-images.githubusercontent.com/8665173/43979684-36512ab6-9cb1-11e8-976a-ccc964e89af8.png">

**Comment by xzhuo** [comment]
I think it has been fixed? @EvoAlias

**Comment by EvoAlias** [comment]
solved
