### ISSUE TITLE
Hot Keys for Frequently Used Buttons

### ISSUE THREAD

**Issue by EvoAlias** [lidaof/eg-react#62]
I  would suggest:

Command H or D for the Drag Tool
Command S or R for the Reorder/Swap Tool
Command M for the Magnify Tool
Shift < or Shift > to pan one full panel left or right.

**Comment by lidaof** [comment]
Thanks.
Did any of this conflict with system hotkeys?

**Comment by lidaof** [comment]
by the way, PC doesn't have command key..

**Comment by EvoAlias** [comment]
CTRL for PC? A bunch of these do conflict...maybe do command option (CTRL ALT for PC)?

**Comment by lidaof** [comment]
`Alt + H` or `Alt + D` for the Drag Tool

`Alt +  S` or `Alt + R` for the Reorder/Swap Tool

`Alt +  M` for the Magnify Tool

`Alt + Z`  and `Alt + X` to pan one full panel left or right.

**Comment by EvoAlias** [comment]
YES AMAZING!!!
