### ISSUE TITLE
Set y-axis of numerical track as 0

### ISSUE THREAD

**Issue by peterch405** [lidaof/eg-react#64]
I have a directional RNA-seq dataset that in the previous version I was displaying by setting the max value of the reverse strand track to 0 which would set the forward and reverse track back to back. On this new version is doesn't seem possible to set the value to 0. Could this be changed please? Or is there another way to display strand specific RNA-seq data?

**Comment by lidaof** [comment]
what's you data look like when you use the default auto scale? or you can send me your URL?
thanks.

**Comment by EvoAlias** [comment]
Hey,

Have you tried combining the files into a bedgraph file (Forward strand (+) Reverse strand (-)), sorting it, compressing it, and then putting it on the browser? You can then have one track for Naive and one for Primed.

**Comment by peterch405** [comment]
Do you mean an extra column that specifies strand? As far as I know bedgraph is only a 4 column format. If you mean combining the values so that negative are reverse strand and positive are forward strand then that does not work as you cannot have the same position with multiple values (i.e. both forward and reverse strand value).

**Comment by lidaof** [comment]
I guess your reverse strand file only have negative values? in that case you combine to one file as @EvoAlias suggested. Thanks.
