### ISSUE TITLE
Upload file from txt - new WashU browser

### ISSUE THREAD

**Issue by LaureTomas** [lidaof/eg-react#71]
I want to ask if it is avaible the feature to upload files in txt format to the browser, because in the old version there is an app to do so but in the new version I couldn't find it

**Comment by lidaof** [comment]
Hi @LaureTomas, the new browser design is serverless (basically there is no server behind it to process big files). while we are working on a third party API for file upload purpose. We will work on this. Will update you.

**Comment by andreagillespie** [comment]
Is there any update on this? I am also trying to upload text files as was an option in the old browser, would be great to use this feature in the new browser.

**Comment by lidaof** [comment]
Hi @andreagillespie sorry the text format is not supported yet currently, while any accepted track type (bigwig, bedgraph.gz) files can be uploaded locally. please see https://eg.readthedocs.io/en/latest/local.html

What track type in text format do you need? bed? We have been thinking for this function, while text file need to be loaded to browser in whole, not like binary file we can read in parts. I can work on this.

**Comment by andreagillespie** [comment]
I need capture Hi-C interaction tracks. It was nice to use the text format option because I could upload them from my local machine.

**Comment by lidaof** [comment]
can you please send me an example of text file to lidaof@gmail.com? I will work on this.

**Comment by lidaof** [comment]
Implemented finally. sorry for the long delay @andreagillespie
