### ISSUE TITLE
Bigwig does not display on new WashU

### ISSUE THREAD

**Issue by ewijaya** [lidaof/eg-react#72]
Hi, 

I tried to upload a bigwig file (downloadable [here](https://s3-ap-northeast-1.amazonaws.com/stemrim-pub/ewijaya/181019_NB501621_0358_AH2J5VBGX9/cutc_bigwig/37oC/MK_31_S2_001_genome.bwt2pairs.sorted.bigWig)), from Custom Track.

But it gave me 'data fetch' error. Please advice how can we resolve the problem?

<img width="404" alt="screen shot 2018-11-22 at 14 55 17" src="https://user-images.githubusercontent.com/9668738/48884234-dd334600-ee66-11e8-80e8-7b8516185855.png">

Thanks and hope to hear from you again.

Regards
E.W.

**Comment by lidaof** [comment]
Hi @ewijaya ,

looks like you need to enable CORS on your webserver, if you use Ubuntu with Apache2 you can take a look at:
https://eg.readthedocs.io/en/latest/tracks.html#configure-your-webserver-to-enable-cors

Thanks.

**Comment by ewijaya** [comment]
Hi @lidaof, 

I tried on your original server: http://epigenomegateway.wustl.edu/browser/
with the linked bigWig file above.
It gave that `Data fetch failed` error.

Please advice how to resolve.

Regards,
E.W.

**Comment by lidaof** [comment]
Hi @ewijaya , I am going to try some stuff on amazon s3 and will update you asap.

**Comment by lidaof** [comment]
Hi @ewijaya ,

in you Amazon S3 bucket, please enable CORS and put this configuration: (text after the image)

![image](https://user-images.githubusercontent.com/102806/49030482-099fd880-f16d-11e8-976a-9a557b680aa3.png)

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>```

please let me know if it works for you.

**Comment by ewijaya** [comment]
Hi @lidaof ,

Yes. It works. Thanks.

E.W.

**Comment by lidaof** [comment]
Thanks for reporting back @ewijaya . I am closing this.
