### ISSUE TITLE
Cannot add link to 3D genome browser

### ISSUE THREAD

**Issue by ClytiaXm** [lidaof/eg-react#74]
Thanks for updating the WashU Epigenome Browser. However, I found that the new version of the browser did not support to save a track as weblink as the old version did. Therefore, I cannot add the track to other webservers, such as the 3D genome browser. I tried to use the weblink created by the old browser, however, it just didn't work as before and linked to a default track (annotations of IMR90). Is there any method to solve this problem? Thanks very much.

**Comment by lidaof** [comment]
Hi @ClytiaXm , sorry I am a little bit confused. What do you mean by link to 3D genome browser?
if you have embedded browser, you can change the URL to old browser URL which is http://epigenomegateway.wustl.edu/legacy/, then things will work again?

**Comment by ClytiaXm** [comment]
Daofeng,
Thanks for replying my question. I wanted to add epigenetic annotations from WashU browser to the 3D genome browser (http://promoter.bx.psu.edu/hi-c/view.php) by adding the weblink of my track from WashU, as shown in the belowing figure. When I used the weblink made from the old WashU browser (by: APP-session-link in the old browser), the correct annotations could not be shown as before.  I read the "Embedding" section in the help ducumention, but I still could not understand how to use it to solve my problem. It will be greatly appreciated if you can kindly give me some suggestions.

ClytiaXu
2018-12-14




xm19910326@126.com
 
From: Daofeng Li
Date: 2018-12-14 00:08
To: lidaof/eg-react
CC: ClytiaXm; Mention
Subject: Re: [lidaof/eg-react] Cannot add link to 3D genome browser (#74)
Hi @ClytiaXm , sorry I am a little bit confused. What do you mean by link to 3D genome browser?
if you have embedded browser, you can change the URL to old browser URL which is http://epigenomegateway.wustl.edu/legacy/, then things will work again?

**Comment by lidaof** [comment]
Hi ClytiaXu,

Really sorry somehow I cannot see your screenshot. You are from Feng's lab,
right?
we can talk over the phone tomorrow if you want? I think it will be easier
to solve the problem.
Thanks
Daofeng

**Comment by ClytiaXm** [comment]
Daofeng,
I'm not from Feng's lab ^_^. I added the screen shot and some descriptions about my problem in the attachment.
Thanks for your patience.
ClytiaXu


xm19910326@126.com
 
From: Daofeng Li
Date: 2018-12-14 13:32
To: lidaof/eg-react
CC: ClytiaXm; Mention
Subject: Re: [lidaof/eg-react] Cannot add link to 3D genome browser (#74)
Hi ClytiaXu,

Really sorry somehow I cannot see your screenshot. You are from Feng's lab,
right?
we can talk over the phone tomorrow if you want? I think it will be easier
to solve the problem.
Thanks
Daofeng

**Comment by lidaof** [comment]
Hi @ClytiaXm , i see i see.
Can you send the screenshot to my gmail lidaof@gmail.com? seems there is still no screenshot in your github reply. Thanks.

**Comment by lidaof** [comment]
closing for now, feel free to reopen it or open a new issue.
