### ISSUE TITLE
Old HiC pairwise format is gone

### ISSUE THREAD

**Issue by gracilis** [lidaof/eg-react#81]
Hi, 

 It used to be that you could visualize HiC data in the below format. Indeed, CHiCAGO outputs data in this format specifically for visualization in the WashU browser. The WashU browser can no longer load these files. 

chr1,860493,861124	chr1,902800,903730	5.44
chr1,860493,861124	chr1,996884,997701	5.37
chr1,860493,861124	chr1,1024143,1025479	8.5

**Comment by lidaof** [comment]
Hi @gracilis , sorry for that trouble. I am not aware of this format is still being used honestly :)

I will do some test to see if I can write data fetching code for this format, meanwhile the format should be used at the old browser http://epigenomegateway.wustl.edu/legacy/

**Comment by lidaof** [comment]
the format can view as local text tracks after some adjustments. but I can also do a specific type for this. Thank you!
closing for now, feel free to reopen it or open a new issue.
