### ISSUE TITLE
how to add new genome

### ISSUE THREAD

**Issue by jos4uke** [lidaof/eg-react#82]
Hi @lidaof 

I was wondering how to add a new genome to eg-react.
Arabidopsis genome is not available in the current genome list.

The install documentation, https://eg.readthedocs.io/en/latest/installation.html, only provides information about how to setup annotation files following hg19 or mm10 templates.
I tried the api service to check if tair10 genome is available but it seems not.

I would like to add several plant genomes but don't know where to start.
Can you give me guidelines on how to setup my own api backend with my own genomes?
Especially how to add genome sequence and annotation files.

Regards
Joseph

**Comment by lidaof** [comment]
Hi @jos4uke , sure thing!
Thanks for interest. We got a similar request from another people as well.
I will work on the documentation and post you asap.
thanks again!

**Comment by jos4uke** [comment]
Hi @lidaof 

it would be great
thanks a lot for your work, it is very useful! 

All the best

**Comment by lidaof** [comment]
Hi @jos4uke , sorry for the delay.
the doc about add a new genome is added at https://eg.readthedocs.io/en/latest/add.html, please let me know if you have any question. Thanks.

**Comment by jos4uke** [comment]
Hi @lidaof , no problem

I will test your documentation and give you feedback on 3 plant genomes 

Thanks a lot for your help

**Comment by jos4uke** [comment]
Hi @lidaof 

sorry it took me a while to reply and give you a feedback on the doc.
I had to solve the proxying issue.  
  
The doc only explained how to configure things on the frontend side.  
And I had to go further on setting up the new genome to add on the backend side because I deployed my own api.  
Still it didn't work yet but seems to be another issue. I will explain this.   
  
To summarize what I have done so far to add arabidopsis genome:  
  
On the `frontend side`:    
1. I set up a public directory on the same server I deployed eg (http://server_name:8080/public/tair10 to host files), I use port 8080 because I have the legacy eg on port 80    
2. into '/public/tair10' I downloaded, convert the genome fasta file into 2bit file, and generate the .chrom sizes also  
3. I prepared the annotation tracks with Ruler and Genes lists  and put into eg-react/frontend/src/model/genomes/tair10/annotationTracks.json  
4. I created the genome configuration file eg-react/frontend/src/model/genomes/tair10/tair10.js with: 
    * genome name 'tair10', 
    * chromosome names and sizes obtained from the .chrom.sizes file  
    * default region set to "1:11310415-11320096"  
    * default tracks with Ruler and 'tair10' ('TAIR10Genes' refered to the db table name I supposed)  
    * TAIR10 hash with all info above added the path to the genome 2bit file  
    * export TAIR10  
5. I added the genome to the system  by updating eg-react/frontend/src/model/genomes/allGenomes.ts  
    * import TAIR10 in the header like for the other genomes  
    * add TAIR10 to the allGenomes list  
    * update the treeOfLife with arabidopsis  (logo url, assemblies and color)  
6. recompile frontend react app  
  
On the `backend side`:  
1. I updated the genome config file backend/setup/genomeConfig.js with:  
    * 'tair10' with db table name 'TAIR10Genes' and 'TAIR10_GFF3_genes.bed' as the gff3 converted to bed   
    * update genomeConfig list with 'tair10'  
2. I created a genome data directory and add genome annotation bed file  
    *  'eg-react/backend/genomeData/tair10'  
    *  convert tair10 gff3 to bed  using gff3ToGenePred and genePredToBed utilities, and clean for chromosome names  
    * copy the cleaned bed into eg-react/backend/genomeData/tair10  
3. Rerun the setup to import the new genome annotation into db  
4. Restart backend  
  
I also configured nginx server to enable CORS on the '/public' directory even though the frontend and the genome file are on the same server.  
  
I successfully get arabidopsis display on the index page:  
  
![washu_epigenome_react_add_arabido](https://user-images.githubusercontent.com/1325049/55715916-fe4f9a00-59f5-11e9-8460-11b53eeadaa4.png)  
     
But I faced an issue that once clicked on 'Go', epigenome is not showing up and remains blank even though no errors occured:   
   
![washu_epigenome_arabido_not_showing_up](https://user-images.githubusercontent.com/1325049/55716187-9fd6eb80-59f6-11e9-8e99-ab141286c11b.png)   
   
So I am not sure if this issue came from adding genome steps in frontend/backend sides or maybe from nginx. If you have any tips about that I would be glad hearing your opinion.

Jos

**Comment by lidaof** [comment]
Hi @jos4uke , I don't see any error from your steps, great.
So you didn't see any error from the web console? have you tried a hard reload in case it's a cache problem?

**Comment by jos4uke** [comment]
Hi @lidaof 

i didn't try yet a hard reload. I use firefox and also did my tests in private window. I think if ignores or flushes the cache. And then I did a Ctrl + F5 to hard reload but same result.

**Comment by jos4uke** [comment]
Here is the webconsole screenshot after the hard reload:  
  
![washu_epigenome_arabido_not_loading](https://user-images.githubusercontent.com/1325049/55737545-a4ff5f00-5a25-11e9-96d9-f5b8f065e14f.png)

**Comment by lidaof** [comment]
can other genomes be loaded?

**Comment by jos4uke** [comment]
I only tested mm10, hg19 and zebrafish  and they all be loaded

I was thinking regarding chromosome names, all of the working genomes have chrXX naming convention.  
But with arabidopsis from TAIR10, the chromosome names were 1, 2, 3,4,5, choloroplast and mitochondria although in the gff they are Chr1, Chr2, Chr3, Chr4, Chr5, ChrC, ChrM.  
So maybe it is related to that chromosome naming.
If i updated it to the ChrX naming, maybe it could fix this issue.

**Comment by lidaof** [comment]
you could try that.

**Comment by jos4uke** [comment]
well I updated all chromosome names in the original fasta and updated all needed files 
but no change
I really don't know what to do right now

**Comment by lidaof** [comment]
can I see your tair10.js? We will also need add tair10 as well.

**Comment by jos4uke** [comment]
sure here it is

eg-react/frontend/src/model/genomes/tair10/tair10.js
```javascript
import Chromosome from '../Chromosome';
import Genome from '../Genome';
import TrackModel from '../../TrackModel';
import annotationTracks from "./annotationTracks.json";

const genome = new Genome("tair10", [
	new Chromosome("Chr1", 30427671),
	new Chromosome("Chr2", 19698289),
	new Chromosome("Chr3", 23459830),
	new Chromosome("Chr4", 18585056),
	new Chromosome("Chr5", 26975502),
	new Chromosome("ChrC", 154478),
	new Chromosome("ChrM", 366924),
]);

const navContext = genome.makeNavContext();
const defaultRegion = navContext.parse("Chr1:11310415-11320096");
const defaultTracks = [
    new TrackModel({
        type: "geneAnnotation",
        name: "TAIR10Genes",
        genome: "tair10",
    }),
    new TrackModel({
        type: "ruler",
        name: "Ruler",
    }),
];

const TAIR10 = {
    genome: genome,
    navContext: navContext,
    defaultRegion: defaultRegion,
    defaultTracks: defaultTracks,
    twoBitURL: "http://a09787.ips2.u-psud.fr:8080/public/tair10/tair10.2bit",
    annotationTracks,
};

export default TAIR10;

```

**Comment by lidaof** [comment]
looks okay to me...can i see annotationTracks.json as well?

**Comment by jos4uke** [comment]
and here is 

eg-react/frontend/src/model/genomes/tair10/annotationTracks.json
```javascript
{
    "Ruler": [
        {
            "type": "ruler",
            "label": "Ruler",
            "name": "Ruler"
        }
    ],
    "Genes": [
        {
            "name": "TAIR10Genes",
            "label": "TAIR10 genes",
            "filetype": "geneAnnotation"
        }
    ]
}

```

**Comment by jos4uke** [comment]
I did noticed in the danRer10.js that cytobands property is present but empty

```javascript
const DAN_RER10 = {
    genome,
    navContext,
    cytobands: {}, // the cytoBandIdeo from UCSC is basically empty
    defaultRegion,
    defaultTracks,
    twoBitURL: 'https://vizhub.wustl.edu/public/danRer10/danRer10.2bit',
    annotationTracks,
};

```  
  
But in my tair10.js, I did remove the cytobands property, maybe the frontend is looking for it?

**Comment by lidaof** [comment]
ha...this all look good to me....i don't know why right now..cytobands are optional...
another thing to try...do you want to do a git pull and updated to latest code? the latest code is in `matplot` branch...haven't merged to master yet.

**Comment by lidaof** [comment]
if you add back cytobands as danRer10, is it working?

**Comment by jos4uke** [comment]
I am trying right now to recompile the frontend with this modification
I will tell you in a few minutes

and yes I can make a git pull if it can help, if you tell me how to do it or send me a link

**Comment by lidaof** [comment]
oh, it's pretty easy
```
git pull
git checkout matplot
```

**Comment by jos4uke** [comment]
ok that's really easy : )

**Comment by jos4uke** [comment]
So I go ahead now and get the frontend to display 
but with some "Track crashed" issue, do you think there is something wrong with the tracks definition?
  
![washu_epigenome_arabido_track_crashed](https://user-images.githubusercontent.com/1325049/55744897-55755f00-5a36-11e9-8b56-dfb77cf7ecd8.png)

**Comment by lidaof** [comment]
i see, seems we don't really check if cytoband existed or not...good to know.

if you go to network tab, can you see the data returned from the backend api?

**Comment by jos4uke** [comment]
Yes I saw the data returned in the network tab. But there is something weird, the ruler set the region on the chromosome Chr1:10105131-12525381, but the TAIRGenes track queried a region Chr1:7684881-14945631
Do you think this could be causing the track crashed?
  
![washu_epigenome_arabido_track_crashed_badQueryRegion_2](https://user-images.githubusercontent.com/1325049/55746130-3f1cd280-5a39-11e9-9d4e-113f6c99ae71.png)

**Comment by lidaof** [comment]
i see the gene records seem not right,
when you load mongo database, the text file columns need be in this order:

```
const GENE_FILEDS = // The mapping from column names to field names in the database
    // 'id,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonStarts,exonEnds,name,transcriptionClass,description';
    'chrom,txStart,txEnd,cdsStart,cdsEnd,strand,name,id,transcriptionClass,exonStarts,exonEnds,description';
```

**Comment by jos4uke** [comment]
well in fact in mm10, I have the same kind of requests so it is not that

**Comment by jos4uke** [comment]
Yes you are right there is something wrong with the gene fields they are all messed up
thanks I will look back to the bed file

**Comment by jos4uke** [comment]
I compared the bed files between zebrafish and arabidopsis and they are not the same format: 11 and 12 columns respectively, is it a special bed you are expecting?     
  
eg-react/backend/genomeData/danRer10/DANRER10_RefSeq_Gene.bed
```bed
chr1	6641	11878	6679	11755	-	rpl24	NM_173235		6641,6891,9557,10080,11549,11750	6760,6955,9694,10191,11625,11878	Additional Info: 60S ribosomal protein L24
chr1	11966	16373	11976	15963	+	cep97	NM_198371		11966,12372,12794,13033,13218,13503,14031,14289,14698,15351,15675	12034,12521,12953,13135,13332,13667,14190,14402,15137,15427,16373Additional Info: centrosomal protein of 97 kDa
...
```  
  
and
  
eg-react/backend/genomeData/tair10/TAIR10_GFF3_genes.bed
```bed
ChrM	366085	366700	ATMG01410.1	0	-	366085	366700	0	1	615,	0,
ChrM	363724	364042	ATMG01400.1	0	+	363724	364042	0	1	318,	0,
ChrM	361349	363284	ATMG01390.1	0	-	363284	363284	0	1	1935,	0,
...
```

**Comment by jos4uke** [comment]
ok I found the specification for the `refbed` format on https://epigenomegateway.readthedocs.io/en/latest/tracks.html#bed  
  
I should have read that first : )

**Comment by lidaof** [comment]
i think this is fine, for these columns you don't have, just use blank, but the columns counts in each row should be consistent.

**Comment by lidaof** [comment]
Hi @jos4uke , I also added araTha1 (same as TAIR10) into our browser, i use all lowercase chr1, chr2 for  chromosome names for consistency. feel free to use our API if you want. while our genome name is araTha1 as I am following UCSC naming. I got genome file from here: http://genome.ucsc.edu/goldenPath/help/examples/hubExamples/hubAssembly/plantAraTha1/araTha1/

**Comment by jos4uke** [comment]
thank you @lidaof it should be very helpful 
I also need to deploy epigenome because we also have non model plant organisms.
And even for arabidopsis, all the mappings and analysis done so far were done using the chromosome naming in the gff, so it would be time consuming to rehead all the files.

**Comment by jos4uke** [comment]
Hi @lidaof  
no problem thanks for helping me and get it to work

I was wondering if you know another utility to convert a standard gtf to refbed, I found the one you provide in the backend  scripts but seem to only expect Ensembl or Gencode gtf input.
I was thinking about modifying it to accept a standard gtf but if you know a better way to do it I would be happy.

**Comment by lidaof** [comment]
you can use the file i formatted here: https://github.com/lidaof/eg-react/tree/matplot/backend/genomeData/araTha1
you may need change chromosome name...i just wrote my own python script for this purpose...

**Comment by jos4uke** [comment]
thanks @lidaof 

I also have to do it for 2 other plant genomes, would you mind to share your python script ?

**Comment by lidaof** [comment]
of course @jos4uke , my scripts already put under https://github.com/lidaof/eg-react/tree/matplot/backend/scripts

**Comment by jos4uke** [comment]
thank you so much @lidaof 
Best
