### ISSUE TITLE
unable to pull remote tracks into genome browser

### ISSUE THREAD

**Issue by jgbaum** [lidaof/eg-react#85]
Hi @lidaof,

I'm trying to help @vivekliai to resolve the issue he discussed in #75 (apologies for previously posting a comment in that closed ticket before opening this one).  I have done a bit of testing to confirm that the issue is not related to URLs containing authentication info.  I've gone ahead and placed a bigwig file on an apache server located [here](https://downloads.iedb.org/misc/test_track.bigWig).

That server (CentOS 7) has been configured with CORS support, according to the [instructions provided by WashU](https://epigenomegateway.readthedocs.io/en/latest/tracks.html).  I've verified that CORS is working at test-cors.org [here](https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fdownloads.iedb.org%2Fmisc%2Ftest_track.bigWig&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote)

However, I've been unable to get the track to load in the new genome browser.  Here is a screenshot of the javascript console error that I'm getting:

![image](https://user-images.githubusercontent.com/6494933/52022743-23340800-24af-11e9-8071-bda31448a6c6.png)

If I take one of the range URLs mentioned in the console logs and try to pull it via wget (from a different domain), it pulls without error:

![image](https://user-images.githubusercontent.com/6494933/52022858-9473bb00-24af-11e9-985c-b6935f2f9b93.png)

I've even gone a step further and configured a separate Ubuntu system to serve the files via apache (as your instructions mention Ubuntu specifically), but the same behavior is observed.

So I'm at a point where I can use your input regarding what settings changes we might be able to make or any other advice you can offer to get the track to load properly via a URL, as uploading the tracks is not a long-term, sustainable option for us.

Note that this track loads just fine in the legacy genome browser, whether hosted on informaticsdata.liai.org or downloads.iedb.org, both with and without authentication information in the URL.

Please let me know if there's any other information I can provide to help resolve this issue.  Your assistance is greatly appreciated1

Thanks,

J

**Comment by lidaof** [comment]
Hi @jgbaum , thanks for all the testing and feedback.
I am sorry for this, I don't have a CentOS box before and that CORS setup just worked at our Ubuntu server. Which version of Ubuntu are you using now?
I also find a new server, get CentOS 7 installed and tested the settings in our doc, it indeed not work with the browser, sorry again.
I have been google'ing solutions for the whole day now, I hope I would find some solution soon. Will update you.

**Comment by lidaof** [comment]
Hi @jgbaum , could you try add this to the main configuration file `/etc/httpd/conf/httpd.conf`:

```
Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Headers: Range
Header set Access-Control-Max-Age: 86400
```
![image](https://user-images.githubusercontent.com/102806/52084966-ea586980-2568-11e9-9a09-345cb465a428.png)

in `/etc/httpd/conf.modules.d/00-base.conf`, the header module should be enabled:

![image](https://user-images.githubusercontent.com/102806/52085050-15db5400-2569-11e9-8865-1ad651df3ecb.png)


I tested this, seems works out! 
Thanks.

**Comment by jgbaum** [comment]
Hi @lidaof,

I've updated the settings in our apache config and the track now seems to be loading properly. Thanks for your quick reply!

-J
