### ISSUE TITLE
unable to add custom data hub

### ISSUE THREAD

**Issue by jgbaum** [lidaof/eg-react#87]
Hi,

I've been trying to upload a JSON datahub to the new epigenome browser, but an unable to do so either via URL or by hitting the 'browse' button to upload a file.

If I put in the URL to my JSON file, I get this error message:
![image](https://user-images.githubusercontent.com/6494933/52151297-7630cb00-2627-11e9-889f-068d15188840.png)

If I click on 'Browse' and select my file, the filename doesn't appear in the box and there is no way to click 'upload':

![image](https://user-images.githubusercontent.com/6494933/52151345-a6786980-2627-11e9-9123-0e9d3a692cf8.png)

So, I have no way to upload a JSON file at the moment.  Please let me know if you need any additional details to address this.

Thanks!

-Jason

**Comment by lidaof** [comment]
Hi @jgbaum , could you please share the data hub URL?
I just tested my side seems fine.

**Comment by jgbaum** [comment]
Sure, here you go:

https://downloads.iedb.org/misc/test_hub.json

Also, if you choose 'browse', are you able to upload a track?  Nothing happens for me in Chrome or Safari.

**Comment by lidaof** [comment]
Got permission error:

![image](https://user-images.githubusercontent.com/102806/52152338-b13cf980-263b-11e9-95d9-70ea01cbadcb.png)

**Comment by lidaof** [comment]
If you click Browser, a File select dialog should popup to allow you select the data hub json file.

**Comment by jgbaum** [comment]
Sorry, fixed the permissions issue...now I'm getting this:

![image](https://user-images.githubusercontent.com/6494933/52152431-3bc92d00-262b-11e9-8d1b-821daf7e1e33.png)

**Comment by jgbaum** [comment]
Regarding the 'browse'...I get to the file dialog and select my file and click 'open', but then nothing seems to happen and I do not see the expected tracks.

**Comment by lidaof** [comment]
I see, it's because the JSON5 parse failure:
![image](https://user-images.githubusercontent.com/102806/52152813-67eda980-263d-11e9-9b3f-f53a5399e4d7.png)

can you remove the `#` lines?

Also you are using the syntax for our old browser, the new version do require a slightly different syntax: https://epigenomegateway.readthedocs.io/en/latest/datahub.html

specify `showOnHubLoad` to be `true`to enable the track display after load the hub. 
https://epigenomegateway.readthedocs.io/en/latest/datahub.html#showonhubload

**Comment by jgbaum** [comment]
OK, thanks...I'm now able to use both options to load my track file!

Would it be possible to pass those parsing errors on to users?  I think that would help to make things clearer.  In any case, everything is working for me as expected now.  Thanks so much for your quick and thoughtful replies!

**Comment by lidaof** [comment]
You are very welcome @jgbaum.
We will consider about the function that puts the error message somewhere on the page to the users.
