### ISSUE TITLE
hammock track support?

### ISSUE THREAD

**Issue by jgbaum** [lidaof/eg-react#88]
Hi,

One of the labs here have prepared 'hammock' tracks that were previously supported by the legacy WashU epigenome browser.  However, this format doesn't seem to be supported by the new browser.  Can you recommend the proper conversion for these tracks so that the data can be viewed in the new genome browser?

Thanks!

-J

**Comment by lidaof** [comment]
Hi @jgbaum , yes, hammock is actually like a collection of different track types in legacy browser. We are working on this format.
What type of data are you trying to look at? peak? you can send me a URL or few lines of the file?
Thanks.

**Comment by jgbaum** [comment]
Hi @lidaof,

Sorry for the late reply.  It turns out our user can simply convert his tracks to BED and he's satisfied going that route.  Thanks again for your assistance!

-J

**Comment by lidaof** [comment]
Thanks for updating. @jgbaum
