### ISSUE TITLE
questions about adding new genomes

### ISSUE THREAD

**Issue by songtaogui** [lidaof/eg-react#91]
Hi, @lidaof 

This is the follow-up of [the issue here](https://github.com/epgg/eg/issues/91):

> Hi @songtaogui , sorry for late reply. This repo is for old browser and I assume your question is for new browser?

> the gene track information are stored in mongodb database in the backend services. you can check the backend folder for more information. which genome are you working on? if it's in our list, you don't need to run the backend services.

I would like to build three genomes, one of them is the [Maize APG v4](https://plants.ensembl.org/Zea_mays/Info/Index), the other two were not publicly released. I haven't found any tutorial for dealing with data in the backend folder [at this site](https://epigenomegateway.readthedocs.io/en/latest/). But I do find a wiki on [adding a soybean geome to the browser](http://wiki.wubrowse.org/Add_a_private_genome#Add_soybean_Gmax_189), it seems this is the wiki of the old browser, but can I follow the wiki to generate the necessary backend files from my `genome.fasta` and `gene_annotation.gff` in the new browser? Or is there a tutorial for the new browser ?

Thank you,

Best wishes,

Songtao Gui

**Comment by lidaof** [comment]
Hi @songtaogui , you are welcome. In that case you need run your own backend services: https://epigenomegateway.readthedocs.io/en/latest/installation.html#setup-your-own-backend-api-optional

maybe you can take a look at the files from mm10 and make the gene file the same format? or I can take a look at your files too. Adding new genome in new browser is at https://epigenomegateway.readthedocs.io/en/latest/add.html

all the example genome data are at backend/genomeData, there is also some scripts at backend/scripts which we used to convert public annotations to our format.

Feel free to ask any further question. Thanks.

**Comment by songtaogui** [comment]
Hi @lidaof ,

Thank you for the kindly help and sorry for the late reply.

I will try to setup the backend files.

Thank you.

**Comment by Austin-s-h** [comment]
Hello, sorry to reopen a stale topic, but I was wondering if I could have some assistance with a similar problem.

I currently have a docker installation of the browser that I've modified to add the latest assembly of the Chicken genome (galGal6). I have properly modified things so I can access the genome, but I am not able to add annotation.

I have created the modified bed file necessary for viewing, and either uploading it as a local track (.gz and the index .gz.tbi as a regbed), hosting it locally and accessing it via https, or adding a galGal6 folder to the backend MongoDB with the (I think) proper configuration fails to load the annotation. 
The track appears, but no genes show up. I'm really stumped here and I feel like I've tried quite a few things. If you could provide some support that would be excellent.

Here is the header of an example .bed (/eg-react/backend/genomeData/danRer10/DANRER10_RefSeq_Gene.bed) 
```
chr1	6641	11878	6679	11755	-	rpl24	NM_173235		6641,6891,9557,10080,11549,11750	6760,6955,9694,10191,11625,11878	Additional Info: 60S ribosomal protein L24
chr1	11966	16373	11976	15963	+	cep97	NM_198371		11966,12372,12794,13033,13218,13503,14031,14289,14698,15351,15675	12034,12521,12953,13135,13332,13667,14190,14402,15137,15427,16373	Additional Info: centrosomal protein of 97 kDa
chr1	27687	34330	27841	34247	+	eed	NM_001017766		27687,29800,30079,31228,31399,31658,31813,32109,32377,32982,33505,34120	27955,29953,30172,31294,31525,31740,31905,32243,32483,33141,33579,34330	Additional Info: polycomb protein eed
chr1	36733	39191	36848	39035	+	hikeshi	NM_001017577		36733,37983,38492,38757,38980,39079	36878,38221,38644,38876,39067,39191	Additional Info: protein Hikeshi
chr1	39324	44525	39821	43400	-	tmem39a	NM_199632		39324,39447,40318,40796,41250,41933,42172,42478,43287,44331	39435,40061,40439,40984,41572,42088,42256,42701,43430,44525	Additional Info: transmembrane protein 39A
chr1	44838	49831	45511	49692	-	ildr1a	NM_200393		44838,45787,47420,47660,47952,48434,48889,49637	45550,46371,47549,47807,48072,48584,49060,49831	Additional Info: immunoglobulin-like domain containing receptor 1 precursor
chr1	65705	71523	67043	71475	-	gpa33a	NM_001115105		65705,67620,67833,68048,68861,69270,71432	67548,67753,67950,68213,69075,69443,71523	Additional Info: cell surface A33 antigen precursor
chr1	109797	119138	109843	117618	+	zgc:163025	NM_001089558		109797,110643,111175,111530,112244,115047,115237,117070	109928,110807,111200,111644,112391,115139,115358,119138	Additional Info: uncharacterized protein LOC100038778 precursor
chr1	119959	125246	119975	124755	+	f7	NM_131819		119959,120112,120863,120961,121701,122110,122328,124204	120036,120276,120888,121078,121842,122232,122449,125246	Additional Info: coagulation factor VII precursor
chr1	127257	134079	127263	133723	+	f7i	NM_173228		127257,128804,129072,130897,131178,131859,132323,133112	127324,128968,129097,131011,131316,131957,132444,134079	Additional Info: coagulation factor VIIi precursor

```

And my similarly processed .bed
```
chr1	5272	10061	5272	8715	-	ENSGALG00000054818	ENSGALT00000098984	coding	9773,9313,8673,6754,5272	10061,9364,8904,6829,5524	Gene ID:ENSGALG00000054818 Gene Type:protein_coding Transcript Type:protein_coding
chr1	5272	9659	5272	8715	-	ENSGALG00000054818	ENSGALT00000097423	coding	8673,6754,5272	9659,6829,5524	Gene ID:ENSGALG00000054818 Gene Type:protein_coding Transcript Type:protein_coding
chr1	5535	8775	5535	8715	-	ENSGALG00000054818	ENSGALT00000102920	coding	8673,6754,5535	8775,6829,5952	Gene ID:ENSGALG00000054818 Gene Type:protein_coding Transcript Type:protein_coding
chr1	9440	14305	9853	11564	+	ENSGALG00000053455	ENSGALT00000107923	coding	9440,10255	10053,14305	Gene ID:ENSGALG00000053455 Gene Type:protein_coding Transcript Type:protein_coding
chr1	9680	14305	9884	11564	+	ENSGALG00000053455	ENSGALT00000104861	coding	9680,9767,10181	9683,10070,14305	Gene ID:ENSGALG00000053455 Gene Type:protein_coding Transcript Type:protein_coding
chr1	27208	33555	27322	33428	+	ENSGALG00000045540	ENSGALT00000085567	coding	27208,32229,32539,33080,33286	27503,32331,32721,33187,33555	Gene ID:ENSGALG00000045540 Gene Type:protein_coding Transcript Type:protein_coding
chr1	31438	243537	53989	243055	+	ENSGALG00000051297	ENSGALT00000075758	coding	31438,32229,53983,54189,242816	31484,32331,54090,54263,243537	Gene ID:ENSGALG00000051297 Gene Type:protein_coding Transcript Type:protein_coding
chr1	39056	42408	39725	42408	-	ENSGALG00000042023	ENSGALT00000087980	coding	41657,40822,40432,39966,39056	42408,40924,40614,40073,39867	Gene ID:ENSGALG00000042023 Gene Type:protein_coding Transcript Type:protein_coding
chr1	39079	42408	39861	42408	-	ENSGALG00000042023	ENSGALT00000052586	coding	41657,40432,39966,39079	42408,40924,40073,39867	Gene ID:ENSGALG00000042023 Gene Type:protein_coding Transcript Type:protein_coding
chr1	58426	58617	58426	58617	+	RF00004	ENSGALT00000094382	nonCoding	58426	58617	Gene ID:ENSGALG00000047594 Gene Type:snRNA Transcript Type:snRNA
```

Could you give any insight as to why nothing is appearing? I have made an archive of my frontend and backend folders available [HERE](https://drive.google.com/drive/folders/1tRTF4OgI1N6d1lgIypQPQtQU2DgnrFCj?usp=sharing).

**Comment by lidaof** [comment]
Hi @Austin-s-h , don't be sorry :) Thanks for using the browser.
The file format you pasted looks good.
So when you say the track appears, is it blank or show data fetch error?

**Comment by lidaof** [comment]
also when you are running your backend, are you able to query gene from your own backend?
did you modify this line `export const AWS_API = "https://api.epigenomegateway.org";` in GeneSource.js file?

**Comment by Austin-s-h** [comment]
![Screenshot from 2019-06-06 14-56-15](https://user-images.githubusercontent.com/44502805/59058774-50ccfb80-886b-11e9-952c-612f8581d64c.png)
![Screenshot from 2019-06-06 14-56-37](https://user-images.githubusercontent.com/44502805/59058775-50ccfb80-886b-11e9-9401-811f441f2e31.png)

So the track appears, but it doesn't seem to throw any error. It is just blank. This happens when I try to load the refbed manually as well, so I'm really confused. 
I am currently using the 2bit genome file from ucsc, but I also added the genome with a local file. Could it be that the refbed isn't compatible with this genome file for some reason?
I did not change that line of code, and I'm not quite sure what you mean to query genes.
If you mean to search in the genome browser itself, I am not able to. It hangs up with a 'loading...' box that never resolves.

**Comment by lidaof** [comment]
ha, from the screenshot i see the location string uses chromosome name as 1 instead of chr1
can you make the chromosome names match between galGal6.js and your refbed file?

**Comment by lidaof** [comment]
also I am going to add chicken genome as well in our main browser, in case you need it.

**Comment by Austin-s-h** [comment]
It was my understanding that the refbed file was required to add "chr" to all of the chromosome names during the conversion. Do you think that because the genome doesn't use this convention that this is the problem? I will be able to test this shortly.

**Comment by lidaof** [comment]
Hi @Austin-s-h the chromosome names need to be consistent between refbed and genome file, so if both w/ or w/o chr, it will be fine.

**Comment by Austin-s-h** [comment]
Hi again!
I've update my genome and refbed file to have no "chr" in them, but that hasn't solved the issue...
Instead, when I manually load this edited refbed file, the track crashes and returns the following errors. 
[WashUError.pdf](https://github.com/lidaof/eg-react/files/3266208/WashUError.pdf)

**Comment by Austin-s-h** [comment]
```1 of 101 errors on the page
RangeError: End cannot be less than start
OpenInterval
src/model/interval/OpenInterval.ts:26:18

  23 |  */
  24 | constructor(public readonly start: number, public readonly end: number) {
  25 |     if (end < start) {
> 26 |         throw new RangeError("End cannot be less than start");
     |              ^  27 |     }
  28 |     this.start = start;
  29 |     this.end = end;

_parseDetails/exons<
src/model/Gene.ts:105:35

  102 | const parsedExonStarts = _.trim(exonStarts, ',').split(',').map(n => Number.parseInt(n, 10));
  103 | const parsedExonEnds = _.trim(exonEnds, ',').split(',').map(n => Number.parseInt(n, 10));
  104 | const exons = _.zip(parsedExonStarts, parsedExonEnds)
> 105 |     .map(([start, end]) => new OpenInterval(start, end));
      |                           ^  106 | 
  107 | for (const exon of exons) { // Get UTRs and translated exons from the raw record
  108 |     const codingOverlap = codingInterval.getOverlap(exon);

_parseDetails
src/model/Gene.ts:105:13

  102 | const parsedExonStarts = _.trim(exonStarts, ',').split(',').map(n => Number.parseInt(n, 10));
  103 | const parsedExonEnds = _.trim(exonEnds, ',').split(',').map(n => Number.parseInt(n, 10));
  104 | const exons = _.zip(parsedExonStarts, parsedExonEnds)
> 105 |     .map(([start, end]) => new OpenInterval(start, end));
      |     ^  106 | 
  107 | for (const exon of exons) { // Get UTRs and translated exons from the raw record
  108 |     const codingOverlap = codingInterval.getOverlap(exon);

get translated
src/model/Gene.ts:77:17

  74 | 
  75 | get translated() {
  76 |     if (this._translated === null) {
> 77 |         this._parseDetails();
     |             ^  78 |     }
  79 |     return this._translated;
  80 | }

getExonsAsFeatureSegments
src/model/Gene.ts:136:12

  133 |         return new FeatureSegment(this, relativeStart, relativeEnd)
  134 |     }
  135 |     return {
> 136 |         translated: this.translated.map(convertOneExon),
      |        ^  137 |         utrs: this.utrs.map(convertOneExon)
  138 |     };
  139 | }

render
src/components/trackVis/geneAnnotationTrack/GeneAnnotation.tsx:95:40

  92 | const centerLine = <line x1={xStart} y1={centerY} x2={xEnd} y2={centerY} stroke={color} strokeWidth={2} />;
  93 | 
  94 | // Exons, which are split into translated and non-translated ones (i.e. utrs)
> 95 | const {translated, utrs} = gene.getExonsAsFeatureSegments();
     |                                ^  96 | const placedTranslated = FEATURE_PLACER.placeFeatureSegments(placedGene, translated);
  97 | const placedUtrs = FEATURE_PLACER.placeFeatureSegments(placedGene, utrs);
  98 | const exonRects = this._renderCenteredRects(placedTranslated, HEIGHT, color); // These are the translated exons

dispatchTrackUpdate
src/components/trackContainers/TrackDataManager.tsx:160:17

  157 | 
  158 | dispatchTrackUpdate(track: TrackModel, newTrackState: Partial<TrackData>) {
  159 |     const id = track.getId();
> 160 |     this.setState(prevState => {
      |         ^  161 |         const update = {};
  162 |         const prevTrackData = prevState[id] || INITIAL_TRACK_DATA;
  163 |         update[id] = {

fetchTrack/<
src/components/trackContainers/TrackDataManager.tsx:139:25

  136 | const rawData = await dataSource.getData(visRegion, this.props.basesPerPixel, trackConfig.getOptions());
  137 | 
  138 | if (this.isViewStillFresh(view)) {
> 139 |     this.dispatchTrackUpdate(track, {
      |         ^  140 |         alignment,
  141 |         visRegion,
  142 |         data: trackConfig.formatData(rawData),

fulfilled
http://172.17.0.2:3001/static/js/bundle.js:204697:58```

It looks like that partially cut off, here is the full code.

**Comment by lidaof** [comment]
Hi @Austin-s-h, this error means there is issue in your refbed file, that the starts of exon coordinates (10th column) are bigger than the end coordinates (11th column), can you check? or you can send me the whole file i can check for you. 

Meanwhile can you change the chrom to string type in mongodb database? you can use the method here: https://github.com/lidaof/eg-react/issues/102#issuecomment-483958662

**Comment by Austin-s-h** [comment]
Hi! Sorry for the delayed response. I don't have time to troubleshoot a local copy of the browser right now, but did you manage to upload the chicken genome onto the main browser?

Specifically, if you could upload both galGal6 and galGal5 that would be perfect.

**Comment by lidaof** [comment]
Hi @Austin-s-h, we have added chicken genome galGal6 and galGal5, feel free to let me know any question. thanks.
<img width="883" alt="Screen Shot 2019-07-15 at 11 27 22 AM" src="https://user-images.githubusercontent.com/102806/61232319-a52d8b80-a6f3-11e9-9614-77c55f8734e7.png">

**Comment by lidaof** [comment]
closing for now, feel free to reopen it or open a new issue.
