### ISSUE TITLE
sessions: custom tracts not really saved

### ISSUE THREAD

**Issue by hewitt645** [lidaof/eg-react#92]
I loaded in my tracks via CyVerse, they are not really  saved in the session. The information about them remains, but I get "data fetch" error and no data displayed

**Comment by lidaof** [comment]
Hi @hewitt645 , I just tested session function seems fine. Can you send me the session bundle id? I can search if it saved in firebase database. Thanks.

**Comment by hewitt645** [comment]
Session ID: Figure 1

****please make note of my new room and phone numbers*****
Sylvia C Hewitt
Receptor Biology, NIEHS
Room E430
111 Alexander Dr
Research Triangle Park, NC 27709
*****Phone 984 287 4317
FAX 301 451 5657

**Comment by lidaof** [comment]
Hi @hewitt645 , bundle id should be a string like this `f16021c0-44fb-11e9-a635-6f227c4b0001`.

**Comment by hewitt645** [comment]
Well, it is loading correctly now. How do I get the bundle ID?

****please make note of my new room and phone numbers*****
Sylvia C Hewitt
Receptor Biology, NIEHS
Room E430
111 Alexander Dr
Research Triangle Park, NC 27709
*****Phone 984 287 4317
FAX 301 451 5657

**Comment by lidaof** [comment]
If you go to Apps-> Session, then there should be a copy button next to the bundle id

**Comment by hewitt645** [comment]
Thank you so much

****please make note of my new room and phone numbers*****
Sylvia C Hewitt
Receptor Biology, NIEHS
Room E430
111 Alexander Dr
Research Triangle Park, NC 27709
*****Phone 984 287 4317
FAX 301 451 5657

**Comment by lidaof** [comment]
Sure, you are welcome!
