### ISSUE TITLE
Epigenome roadmap data from Public Data Hubs does not load

### ISSUE THREAD

**Issue by grace-hansen** [lidaof/eg-react#93]
Hi,

   Wen I try to load data from the Epigenome roadmap that's hosted on the WashU browser, it fails to load. 

This is what I do to load the data:
Tracks --> Public Data Hubs --> Reference human epigenomes from Roadmap Epigenomics Consortium: Complete Consolidated Dataset --> Adult Cells/Tissues,Fat,Adipose Nuclei --> "H3K4me1 narrowPeak of Adipose Nuclei"

The browser just shows an empty red box where the track should be with an error message saying "Unknown track type: "hammock". 

 I think that a lot of the Epigenome Roadmap data are stored as hammock files, and those no longer exist on the browser, so there's an error.

**Comment by lidaof** [comment]
Hi @gracilis you are correct, we are actually working on this. The hammock peak format is not supported yet, but will be. Sorry for the trouble.

**Comment by lidaof** [comment]
Hi @gracilis , sorry for later notice. the hammock track had be added. It will be shown like regular bed track for now. More track configurations are under development.
