### ISSUE TITLE
Track properties for longrange Score Scale and refbed max rows

### ISSUE THREAD

**Issue by songtaogui** [lidaof/eg-react#94]
Hi, @lidaof 
What properties should I use to control the `Score Scale` ("fixed or auto") and the related `Score min/max value` of the `longrange` track type? I have tried "yScale|ScoreScale|scoreScale", non of these works. And what properties for `refbed max rows` ?

Thank you, 

Best wishes
Songtao Gui

**Comment by lidaof** [comment]
hi @songtaogui , sorry for the missing documentation
it's scoreScale/scoreMax/scoreMin
the 2nd question is maxRows

I will update the docs as well.

**Comment by songtaogui** [comment]
@lidaof 
Thank you, it works !

And I have other questions:
I would like to add/change search link of other databases to the `refbed` info box ( ① in the figure below), 
also I would like to change the description "Transcription class" to "class" (② in the figure below) when displaying non-transcription-features. Is it possible to achieve these by editing some script(s) and re-build the browser?
![image](https://user-images.githubusercontent.com/14274330/54472087-ce99e180-47fd-11e9-9cee-bcc10f3e95b4.png)

Thank you again for your kindly help.

Songtao Gui

**Comment by lidaof** [comment]
nice @songtaogui .

For the link and class change you will need modify FeatureDetail.js and GeneDetail.js (which should be pretty straightforward) in the source code and rebuild. 

Thanks.

**Comment by songtaogui** [comment]
@lidaof 

Sorry for the late reply. I have achieved my goals by editting the two js files, thank you.

And I was wondering that is there an URL parameter that specified the display-regions, because I would like to link the regions information elsewhere to the WASHU browser.

Thank you.

**Comment by lidaof** [comment]
yep, can you try `position`?

**Comment by songtaogui** [comment]
yeah, it works！
Thank you for everything. # 👍

**Comment by lidaof** [comment]
Sure, I am closing this one. Feel free to ask if you get new issue.
