### ISSUE TITLE
HiC data has huge whitespace

### ISSUE THREAD

**Issue by gracilis** [lidaof/eg-react#96]
Hi,

 This is a new issue--as of a week ago, this did not occur.

 When I load HiC data in longrange format, they load fine but the track space is huge--it covers most of the screen and prevents other tracks from being visible. This is true whether HiC data are in heatmap or arc form. A picture is attached.

![image](https://user-images.githubusercontent.com/42852986/54955726-19ada600-4f1c-11e9-8f67-e4456875452a.png)

**Comment by lidaof** [comment]
Hi @gracilis , yes, I am working on making the height configurable, it should be fixed very soon. 
We enabled canvas to render the arcs which should make the hic track faster.
Sorry for the trouble.

**Comment by gracilis** [comment]
Thanks!

**Comment by lidaof** [comment]
@gracilis thanks for understanding.
Please refresh to v48.4.2, I have enabled height config for the long range tracks, right click the track you can customize the default 500px to any height. Thank you.
