### ISSUE TITLE
No tooltip text in arc

### ISSUE THREAD

**Issue by souryacs** [lidaof/eg-react#97]
Scrolling through longrange tracks in the new browser does not show any tooltip text (such as interacting regions) when the cursor touches any arc.

**Comment by lidaof** [comment]
Hi @souryacs , yes, last week when I switched to canvas for fast rendering the tooltip is gone right now. I am working on this, hope to get it back asap. Thanks for reporting.

**Comment by souryacs** [comment]
Still the problem persists. It would be very helpful to know the interacting regions and interaction scores from the arcs, just like the old browser. Please check.

**Comment by lidaof** [comment]
Hi @souryacs , sure thing...i will start work on this issue right now. sorry for that delay.

**Comment by lidaof** [comment]
Hi @souryacs , tooltip has been added to arc and heatmap display. please let me know if there is any issue. thank you!
![image](https://user-images.githubusercontent.com/102806/58991598-44369d80-87ae-11e9-9d7f-7ad5a0fa7d0e.png)

**Comment by lidaof** [comment]
closed for now. feel free to reopen or submit any new issue.
