### ISSUE TITLE
Negative score arcs - color2 property

### ISSUE THREAD

**Issue by souryacs** [lidaof/eg-react#98]
I tried to put positive and negative significance scores in longrange format data as:

chr1    8937499 8937501 chr1:9302499-9302501,-2
chr1    9302499 9302501 chr1:8937499-8937501,-2
chr1    16767499        16767501        chr1:16817499-16817501,3
chr1    16817499        16817501        chr1:16767499-16767501,3

The idea was to use "color" and "color2" in the longrange track properties to differentiate among two kinds of interactions (i.e. +ve and -ve scores). 
I've set displayMode:"arc", scoreScale:"fixed", scoreMax:10, scoreMin:-10, color:"#1E90FF", color2:"#1EFF6A". 
But currently all interactions (even negative scored loops) are displayed in "color" (i.e. with only one color).

**Comment by lidaof** [comment]
Hi @souryacs , do you have a .gz file for testing this, if yes, could you please send me your test file?
if you don't have, that/s fine too. I am debugging on this. Thanks for reporting.

**Comment by lidaof** [comment]
Hi @souryacs , can you please refresh the bowser code, and this problem should be fixed.
Sorry for the bug and thanks for reporting.

**Comment by souryacs** [comment]
Many thanks @lidaof  for your quick response. I can distinguish between two scores now.

**Comment by lidaof** [comment]
Thank you @souryacs for confirmation, closing now. Feel free to open any new issue.
