### ISSUE TITLE
how to set local track files in a default track facet table

### ISSUE THREAD

**Issue by liyq601** [lidaof/eg-react#99]
Hi @lidaof, I have hundreds of local track files.  Is there a way to set a default track facet table like JBrowse? So I need not to upload these tracks every time.

**Comment by liyq601** [comment]
Yes, I have. My purpose is to make these tracks as default tracks in the facet table. When I visit the browser, what I need to do is just to select some tracks instead of uploading them. I want to share my data with other lab members or labs, but it's difficult and impossible to send all these tracks to them. So I want to achieve this function.

**Comment by lidaof** [comment]
Hi @liyq601, while, the data are at your local computer, how can you share the browser tracks without sharing the data? the local hub is reading the file from your local drive actually..if you and your lab members are at same intranet, i recommend setup a local web apache server in your computer, use the URL to build the hub, then this hub can be shared to anyone in same intranet as you. Does this make sense?  can you send me the jbrowser link to the function you want ? maybe we don't have this function yet :)

**Comment by liyq601** [comment]
Hi @lidaof , thanks for your answer. I also thought this way(setup a local web server). I just wonder whether there are other easier ways to make it.

**Comment by lidaof** [comment]
sure thing. @liyq601 I did look around jbrowse documentation, but didn't find the function you mentioned...

**Comment by liyq601** [comment]
sorry, @lidaof  maybe I do not describe the question clearly. but it does not matter. I will set up a local web server to achieve this function. Thanks

**Comment by lidaof** [comment]
sure thing, closing now, Feel free to open new issue. thank you @liyq601
